### ISSUE TITLE
Search box elements in wrong order

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Skosmos#1011]
## What steps will reproduce the problem?
1. Go to Finto.fi
2. Type "kis" to the frontpage search box, with default settings (from all vocabularies in all languages) and press enter

## What is the expected output? What do you see instead?
When the search result list appears, the elements of the search box arrange in wrong order. 
The order is 

- "Content language", "from all [vocabularies]", "[in] Any language"

![image](https://user-images.githubusercontent.com/8804680/85022939-b4774d80-b17c-11ea-9120-70b0b55ae7ed.png)

Order should be

- "from all [vocabularies]", "Content language", "[in] Any language", or 
- "Content language", "[in] Any language", "from all [vocabularies]", 

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox 68.9.0esr (64-bit)

**Comment by kouralex** [comment]
This has been fixed by introducing the same behavior as there exists for front page, therefore, I am closing this now. In case the selected behavior does not fulfill the requirements, I suggest reopening this.
