### ISSUE TITLE
Adding HTML IDs / classes to the property value list

### ISSUE THREAD

**Issue by CaptSolo** [NatLibFi/Skosmos#1034]
Enhancement proposal: 
Add HTML IDs / classes to the property list elements so that they can be addressed from Skosmos plugins. Currently, 

Example: a plugin needs to address the value of the `dc:identifier` property (in order to add a link next to the identifier value). It would be easier if relevant property values had an HTML class attribute (e.g. `class="dc_identifier"`) that allows plugin developers to directly address these HTML elements.

`<span class="dc_identifier">LNC10-000194258</span>`

**Comment by kinow** [comment]
Maybe also use a prefix, like `skosmos`, `sk`, etc. So that if plugin developers add new elements, there's less chance of conflicts with ID's and classes (e.g. Vuetify uses `v-` for ID/classes, I work on a project that uses Vuetify, so we use `blabla-` for our ID's and classes, which some times have the same value as in Vuetify, except by the prefix)

**Comment by CaptSolo** [comment]
Related discussion: https://groups.google.com/forum/#!topic/skosmos-users/-2x7rJyoNF0

**Comment by osma** [comment]
This would also allow doing custom per-vocabulary adjustments to the Skosmos concept page using CSS, for example hiding certain properties. The `body` tag already contains a dynamic `vocab-xxx` CSS class where `xxx` is the vocabulary ID.

**Comment by osma** [comment]
I've started designing the implementation. How about using `prop-` as the prefix (similar to `vocab-` used in the body tag, see above comment) and turning non-alphanumeric characters to underscores, so e.g. `dc:identifier` would become `prop-dc_identifier` ?

**Comment by CaptSolo** [comment]
> I've started designing the implementation. How about using `prop-` as the prefix (similar to `vocab-` used in the body tag, see above comment) and turning non-alphanumeric characters to underscores, so e.g. `dc:identifier` would become `prop-dc_identifier` ?

That sounds good.
