### ISSUE TITLE
Global search in Finto not global

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#1035]
When using global search box on top of Finto frontpage with "from all" and "English" set as default and not chosen with a mouseclick, the results only cover a few vocabularies: "education" brings results only from Iconclass. Cf. "education" search when browsing YSO brings 45 results, with KOKO 137 results.

When "English" (or any other language) is chosen with a mouseclick, global search seems to be working ok.

**Comment by MikkoAleksanteri** [comment]
This seems to be working correctly now (was perhaps fixed in https://github.com/NatLibFi/Skosmos/pull/1354), at least I could not reproduce the described behaviour. Closing this issue, please reopen if necessary.
