### ISSUE TITLE
Upgrade UI to use Bootstrap 5

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1045]
The current Skosmos UI uses Bootstrap CSS version 3.

We should upgrade to Bootstrap 4, which among other things uses flexbox for layout. This should make it easy to fix alignment issues such as those described in issue #1006.

Upgrading Bootstrap is a large undertaking as all the HTML templates and CSS files are affected.

Bootstrap 4 drops support from some older browsers. We should verify that this doesn't cause problems for users of important Skosmos installations such as Finto.

**Comment by kinow** [comment]
@osma I spoke yesterday with a friend who uses Bootstrap too about this task, but he told me he was using Bootstrap 5. Should we aim at moving to Bootstrap 5 here instead?

From what he told me, it looks like it's in beta state, but apparently it contains two versions, one Bootstrap 5 with JS, and another pure CSS, that doesn't require JQuery.

WDYT?

**Comment by kinow** [comment]
Beta 2 was released 10/feb this year.

There is a chance that beta 3 will be promoted to stable released - Bootstrap v5.0.0-beta3 (possibly promoted to v5 stable)

Their projects page includes [5.3.0b](https://github.com/twbs/bootstrap/projects/34) and [v5.stable](https://github.com/twbs/bootstrap/projects/27) details.

**Comment by kinow** [comment]
Got the news last week that Bootstrap 5.0.0 was out. So if that's OK I will reading what's necessary to upgrade the UI to Bootstrap 5 :+1: - https://getbootstrap.com/

**Comment by osma** [comment]
OK - in the current circumstances, aiming for Bootstrap 5 sounds like a good idea! So yes, please @kinow :)
One benefit of Bootstrap 5 is that it's independent of jQuery. Since we are now also trying to upgrade many jQuery based components as well as jQuery itself, decoupling that from the Bootstrap upgrade would probably make things easier.

**Comment by kinow** [comment]
Taking a look at how complex this would be. Draft PR coming soon with initial work. For now working on https://github.com/kinow/Skosmos/tree/bootstrap-5.

- [x] use composer to install Bootstrap 5
- [ ] verify what is working, and what is not
  * [ ] languages dropdown broken :red_circle: 
- [ ] verify what needs updating

WIP: will keep updating this comment…
