### ISSUE TITLE
Layout breaks (ontology page)

### ISSUE THREAD

**Issue by miguelahonen** [NatLibFi/Skosmos#1064]
## At which URL did you encounter the problem?
http://dev.finto.fi/soto/sv/?clang=fi
http://dev.finto.fi/yso-paikat/fi/
http://dev.finto.fi/koko/en/
..all of the ontology pages

## What steps will reproduce the problem?
1. Straight links like above or via the front page

## What is the expected output? What do you see instead?
Expected:
Something like this:
![image](https://user-images.githubusercontent.com/50104570/93741576-5f245f80-fbf5-11ea-8010-19cef4d7f518.png)

Instead:
![image](https://user-images.githubusercontent.com/50104570/93741194-9c3c2200-fbf4-11ea-815a-cf479cc24863.png)
## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox and Chrome (Ubuntu/Cubbli 18.04

**Comment by kouralex** [comment]
I am closing this as this applied to a specific installation of Skosmos (now fixed), not to Skosmos example installation itself.
