### ISSUE TITLE
Missing "skos:altLabel" Spanish translation causes the synonym section to be hidden when browsing in Spanish

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#1065]
Missing/empty translation here : https://github.com/NatLibFi/Skosmos/blob/98c5a158dedcfa2f021d6a8f586fe8e577f4f263/resource/translations/skosmos_es.po#L531

## At which URL did you encounter the problem?

http://vocabularies.unesco.org/browser/thesaurus/es/page/concept850?clang=es

## What steps will reproduce the problem?
Go at http://vocabularies.unesco.org/browser/thesaurus/es/page/concept850?clang=es
Then go at http://vocabularies.unesco.org/browser/thesaurus/en/page/concept850?clang=es in English. See the synonym displayed in English, but not in Spanish.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by osma** [comment]
This was fixed a while ago in PR #1150, when we pulled fresh translations from Transifex in early April. This went into the Skosmos 2.10 release. The corresponding `msgstr` is now this:

    msgstr "Etiquetas alternativas"

There were other changes as well including this typo fix:

    - msgstr "Por parentezco"
    + msgstr "Por parentesco"
