### ISSUE TITLE
No issue, but appreciation for your work

### ISSUE THREAD

**Issue by niva83** [NatLibFi/Skosmos#1075]
Dear SKOSMOS team,

This is a fastest way to say "Many thanks for your great work".
I really appreciate the simplicity and features of SKOSMOS.

I've just recently have set it up at Technical University of Denmark, department of Wind Energy, to [serve our controlled terminologies](https://data.windenergy.dtu.dk/ontologies/view), and have been showing tools in several workshops in Denmark organized by DeiC (Danish e-Infrastructure Cooperation).

Best,

Nikola

**Comment by osma** [comment]
Thanks @niva83 for your kind words! And sorry for taking so long to respond, this didn't seem urgent at the time :) 

Please consider joining the skosmos-users Google Group if you haven't already. It's a better place for user community discussion than GitHub issues.

Cheers,
Osma

**Comment by niva83** [comment]
@osma sure! I will do that, in mean time I have spin up several SKOSMOS instances in Denmark.
One runs on DeiC server:
http://ontology.deic.dk/

another one for [FAIR DATA COLLECTIVE](http://fairdatacollective.org/):
http://vocab.fairdatacollective.org/
