### ISSUE TITLE
Expose SKOS XL metadata of labels

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#109]
Supporting SKOS XL would involve at least:

- having a separate page for term information
- making terms clickable so one can get to that page

Would be useful for AGROVOC, and also possibly in the future for YSO if we add more term metadata using SKOS XL.

It's still fine to require SKOS Core labels to be explicitly materialized.

**Comment by osma** [comment]
Here's how PoolParty supports SKOS XL labels, i.e. as clickable links with popups. We should do something similar.
https://help.poolparty.biz/doc/white-papers-release-notes/poolparty-release-notes/release-notes-poolparty-5-3

**Comment by osma** [comment]
Now that #477 (reified definitions) is done, this should be a bit easier to accomplish following the same pattern.

The first step would be to modify the concept info query so that it returns the SKOS XL metadata, even though it is not shown in the UI. This issue should be about the data side. I've opened another issue (#533) about making the SKOS XL metadata visible in the UI.

**Comment by osma** [comment]
SKOS XL metadata is available at least in EuroVoc, AGROVOC and GACS.

EuroVoc example concept: http://skosmos.dev.finto.fi/euro/en/page/344
EuroVoc XL labels typically contain eu:termReleasedWithVersion properties.

AGROVOC example concept: http://skosmos.dev.finto.fi/agrovoc/en/page/c_24392
AGROVOC XL labels typically have vocbench:hasStatus and dct:created properties, sometimes also others.

GACS example concept: http://skosmos.dev.finto.fi/gacs/en/page/C597
GACS labels for organisms typically have agvoc:scientificName properties.

**Comment by tfrancart** [comment]
Also interested in this, in a scenario where VocBench is the back-office thesaurus editing tool, and handles everything in SKOS-XL.
