### ISSUE TITLE
Code quality: Organize JS variables into a single SKOSMOS variable instead of global population

### ISSUE THREAD

**Issue by kouralex** [NatLibFi/Skosmos#1090]
At the moment Skosmos "leaks" JS variables into global namespace (see https://github.com/NatLibFi/Skosmos/blob/master/view/scripts.twig for a more detailed information) which causes global namespace pollution. 

Similar in nature to #799, it might make sense to postpone fixing this issue in next major Skosmos version as the globally declared variables are probably used in plenty of plugins, thus, being a backwards incompatible fix.

Similarly, there could be a guideline for Skosmos plugings to register them under, for example, SKOSMOS.plugings or similar. 

Any comments @osma @joelit ?

**Comment by osma** [comment]
This was implemented in PR #1438.
