### ISSUE TITLE
Feedback form should have a headline/subject box

### ISSUE THREAD

**Issue by YSO-kokous** [NatLibFi/Skosmos#1093]
Feedback messages sent via finto.fi's feedback form all have the headline "Finto feedback" when viewed in an email service. This makes managing feedback difficult (e.g. it's difficult to find a specific feedback message). Headline box would be a huge improvement.

**Comment by YSO-kokous** [comment]
KANTO maintenance (KANTO is a vocabulary published in finto.fi) has contacted Finto and suggested that messages sent via Finto feedback form should be more specific, possibly including the label of the concept through which the feedback has been sent. This, however, might not be the best solution, universally speaking. Feedback doesn't always concern just one specific concept but instead is often more general.

**Comment by miguelahonen** [comment]
- [ ] Getting to know the code
- [ ] Programming the first version
- [ ] The first review
- [ ] Implementation of the improvements identified in the review
- [ ] The second review
- [ ] ...
- [ ] Unit tests
- [ ] Push

**Comment by osma** [comment]
Fixed in PR #1130, closing
