### ISSUE TITLE
Security warning in php composer.phar install

### ISSUE THREAD

**Issue by CaptSolo** [NatLibFi/Skosmos#1099]
When installing Skosmos following the [Install tutorial](https://github.com/NatLibFi/Skosmos/wiki/InstallTutorial):

`sudo php composer.phar install --no-dev`

composer.phar displays a warning message:

`Do not run Composer as root/super user! See https://getcomposer.org/root for details`

Is it OK to `git clone` the repository and run `composer.phar` without `sudo`? (If yes, it would be good to mention it in the tutorial)

**Comment by kouralex** [comment]
Yes, it is OK to do so. `sudo`ing is only mandatory if one (the user) cannot write to the (possibly root-owned) directory. Running Composer as super user is - nonetheless - not recommended.

I will update the wiki page accordingly, thank you for spotting this.
