### ISSUE TITLE
Hierarchy tab looking all funny

### ISSUE THREAD

**Issue by YSO-kokous** [NatLibFi/Skosmos#1109]
When viewing YSO concept ryhmät (eng. groups) (http://www.yso.fi/onto/yso/p1127) and changing the language from Finnish to English, the hierarchy tab changes, ie. the hierarchy lines are no longer visible. See attached screenshot:

![YSO hierarchy tab looking all funny](https://user-images.githubusercontent.com/26646278/102351175-ad57bd80-3fae-11eb-8530-1e5766ffbecb.jpg)

**Comment by osma** [comment]
This is a JS bug, the interpreter is crashing.

**Comment by osma** [comment]
Apparently this was solved by PR #1188, closing the issue.

**Comment by osma** [comment]
Still crashing JS.

**Comment by osma** [comment]
I tried reproducing this on Finto.fi and on my local Skosmos installation, but I couldn't. I guess that last time when I wrote "Still crashing JS" above was some sort of caching issue. The problem should be fixed in 2.12 already so I'm closing the issue.
