### ISSUE TITLE
The  skosmos:hasMultiLingualProperty setting doesn't work as intended

### ISSUE THREAD

**Issue by oddrunpauline** [NatLibFi/Skosmos#1115]
Sometimes it is useful to view information about a concept even though the information exists **only in another language than the selected content language**.  Typical examples are skos:note fields, which may exist only in the default language, while terms are offered in several languages. 
In SKOSMOS, this should be obtained by using the skosmos:hasMultiLingualProperty configuration setting

Example: The setting _skosmos:hasMultiLingualProperty skos:definition,  skos:scopeNote_
should imply  that all skos:definition and skos:scopeNote instances - in our case  written in the language Norwegian bokmål (nb)- are shown on their parent concept page also whenever another language, e.g. English is the selected content language.
See also [SKOSMOS user group conversation](https://groups.google.com/g/skosmos-users/c/QAJu_boLICw/m/iseYnt1tBAAJ).

Currently, in spite of the setting above, definitions and scopeNotes are shown only when content language is nb (like the language of the notes)

**Comment by kouralex** [comment]
Thank you for the report.

I have identified the issue around the following lines of code and will soon come forward with a fix. https://github.com/NatLibFi/Skosmos/blob/254c2c66566527e873750fd36171086dc2d79417/model/Concept.php#L580-L583
