### ISSUE TITLE
Add generator meta tag in HTML output to show Skosmos version

### ISSUE THREAD

**Issue by nichtich** [NatLibFi/Skosmos#1116]
I tried to automatically detect whether a page is run by Skosmos. Could you please add a HTML header such as

~~~html
<meta name="generator" content="Skosmos 2.8" />
~~~

**Comment by osma** [comment]
Thanks for the suggestion.

Is the version number important? Not that it's a big secret, it's already displayed on the [about page](http://finto.fi/en/about).

Any change you could provide a PR implementing this? ;)
