### ISSUE TITLE
PHP code style cleanup and automated code style checks

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1154]
It would be good to follow [PSR-12](https://www.php-fig.org/psr/psr-12/) (successor to PSR-2) code style. At some point in the past we used to run code linting tools but many changes have happened since and we have probably since accumulated are a lot of style violations.

I suggest that we should do the following:
1. Use a cleanup tool such as PHP-CS-Fixer to fix style violations in the codebase
2. Add a PSR-12 violation detector (e.g. PHP-CS-Fixer, PHPCS, PHPMD, PHPStan...) into the test suite, ensuring that proper code style is enforced

Point 1 will probably cause a massive commit with lots of changes all around the codebase. Any open PRs may end up in a conflict state. So we will have to wisely choose the correct timing for such a change.

Some relevant tutorials / blog posts:
* https://akki.ca/blog/how-to-add-psr-2-code-check-as-unit-test/
* https://thevaluable.dev/code-quality-check-tools-php/

**Comment by osma** [comment]
Now implemented in skosmos-3 branch:

- PHP-CS-Fixer has been installed as a dev dependency using Composer
- PHP code (including tests) has been reformatted using PHP-CS-Fixer
- Added a GitHub Action rule to check that the code (not including tests) follows PSR-12

**Comment by joelit** [comment]
Commited to Skosmos-3 branch. Closing issue.
