### ISSUE TITLE
Hierarchy doesn’t show all root terms in languages other than English

### ISSUE THREAD

**Issue by matthew-morris-cessda** [NatLibFi/Skosmos#1161]
We noticed a new behaviour in version 2.9 and 2.10.

The English term always shows the full hierarchy of terms regardless on how the concept is accessed.

![image](https://user-images.githubusercontent.com/68543725/116095079-5ecad600-a6a8-11eb-8760-ed7b32aa3292.png)

This is not consistent with what happens with other languages. For example, when using Finnish – when selecting from the language index the full hierarchy is shown:
 
![image](https://user-images.githubusercontent.com/68543725/116095154-6f7b4c00-a6a8-11eb-8027-906aa1c21bb9.png)

However, when accessing the concept directly, or switching from English, only the root term in the and all descending elements in the hierarchy are shown:

![image](https://user-images.githubusercontent.com/68543725/116095174-75712d00-a6a8-11eb-91d8-608e6ceed147.png)

## What is the expected output? What do you see instead?
 
To help users remain orientated when using ELSST, the hierarchy should always show the entire tree. This was different in Skosmos 2.8: <https://thesauri.cessda.eu/elsst/en/page/?clang=fi&uri=https%3A%2F%2Felsst.cessda.eu%2Fid%2F6a30bfcc-1517-470b-a38d-aad09e3cb316>
    
![image](https://user-images.githubusercontent.com/68543725/116095206-7efa9500-a6a8-11eb-9416-af417514f757.png)

**Comment by kouralex** [comment]
Could not reproduce with the latest release (2.11).

Can you please verify the issue with the latest release? Please remember to follow the usual upgrading procedure after checking out the newest maintenance branch: https://github.com/NatLibFi/Skosmos/wiki/Upgrading

**Comment by matthew-morris-cessda** [comment]
It turned out to be a data issue. When loading a new dataset into Fuseki the issue went away. Thanks for taking a look.
