### ISSUE TITLE
Composer could not find a composer.json file in /var/www/html

### ISSUE THREAD

**Issue by ArthurGenet** [NatLibFi/Skosmos#1179]
Hello,

I am trying to run `docker-compose up -d` but I have got this error:

```
[13/14] RUN php composer.phar install --no-dev:
#17 0.432 Do not run Composer as root/super user! See https://getcomposer.org/root for details
#17 0.435 Composer could not find a composer.json file in /var/www/html
#17 0.435 To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
------
executor failed running [/bin/sh -c php composer.phar install --no-dev]: exit code: 1
```

I am on MacOS, my `dockerfiles`folder  is located under `/Users/arthurgenet/subfolder/dockerfiles`
(I had to add a `subfolder` otherwise the context was everything in` /Users/arthurgenet`).

Do you have an idea why I have this error?

**Comment by osma** [comment]
Did you clone/download the whole repository? It sounds like you only have the `dockerfiles` folder and nothing else.

**Comment by ArthurGenet** [comment]
Ok thanks a lot that was the issue, I was just using `dockerfiles` outside of the Skosmos repository.
Have a good day :)
