### ISSUE TITLE
Searching with decomposed unicode characters

### ISSUE THREAD

**Issue by Vainonen** [NatLibFi/Skosmos#1184]
## At which URL did you encounter the problem?
http://finto.fi/finaf/fi/page/000185275

## What steps will reproduce the problem?
1. Copy a keyword used in search from a text with decomposed unicode characters 

## What is the expected output? What do you see instead?
Search will not find similar prefLabel if the decomposed unicode character in keyword is precomposed in the vocabulary.

**Comment by kouralex** [comment]
Could not reproduce. Please give a more throughout example.

**Comment by joelit** [comment]
Same here; I couldn't reporduce the reported bug. But I did get close to it - while searching with `Etholén, Hans` or `Etholen, Hans` did produce the desired search result. I could at least copy and paste the authorized search term for the entity, including the trailing white space, and try to search with that. At least that way there was no search results.

**Comment by kouralex** [comment]
That is a good theory and catch @joelit ! Could there have been a trailing white space @Vainonen ?

**Comment by joelit** [comment]
This could be reproduced by creating a decomposed unicode search string, for example:
`uconv -x any-nfd <<<'Etholén, Hans'`

Using the precomposed search term, we get a single result:
https://finto.fi/finaf/fi/search?clang=fi&q=Ethol%C3%A9n%2C+Hans

Using the decomposed search term, we got no results:
https://finto.fi/finaf/fi/search?clang=fi&q=Ethole%CC%81n%2C+Hans

This could be solved in the text index with an appropriate filter, but maybe it's better to normalize the search terms in the `ConceptSearchParameters`.
