### ISSUE TITLE
JS code executed before a resource is loaded causes hierarchy to not be loaded

### ISSUE THREAD

**Issue by kinow** [NatLibFi/Skosmos#1186]
## At which URL did you encounter the problem?

Running Skosmos from `master` (from some time ago, but also the latest version) with Docker.

## What steps will reproduce the problem?
1. Start the Fuseki+Skosmos with `docker-compose up`
2. Ingest data
3. Visit Skosmos at localhost:9090 or another URL you have configured
4. Now you should be able to reproduce on the first load a scenario where the hierarchy is empty, and you have a JS error in the browser console, similar to (copied Henk's snippet reported via mailing list):

```
Uncaught TypeError: $(...)[0] is undefined
$('script[type="application/ld+json"]')[0].innerHTML = data.graph;
```

## What is the expected output? What do you see instead?

No errors.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox on Ubuntu LTS.

**Comment by kinow** [comment]
I had seen this error before, but never created an issue. Henk posted on the mailing list and I recognized the issue. I have a theory on why that happens, but never stopped to investigate it. I never saw it happen on the dev instance of Skosmos.

**Comment by kouralex** [comment]
Duplicate of #1016

Whilst a bit different set up and end result (different parts of code are being loaded), I believe that both can be tackled with the same fix.

**Comment by kinow** [comment]
> Duplicate of #1016
> 
> Whilst a bit different set up and end result (different parts of code are being loaded), I believe that both can be tackled with the same fix.

Ah thanks @kouralex ! Let me close this one.
