### ISSUE TITLE
Skosmos version not showing in Docker install

### ISSUE THREAD

**Issue by ArthurGenet** [NatLibFi/Skosmos#1202]
## What steps will reproduce the problem?
1. Run a Skosmos instance with the latest Docker install
2. Go to "About"

## What do you see?
![Capture d’écran 2021-09-10 à 11 55 46](https://user-images.githubusercontent.com/40146654/132836358-ad4ae2bd-b5f9-45b5-99e5-763bf8c93fdf.png)

In the Dockerfile, it is written `ARG SKOSMOS_VERSION=v.2.9`

Is it the version used for the latest Docker install ?

**Comment by osma** [comment]
Thanks for the report. The Skosmos version is currently extracted from Git version tags, but these are not available when running under Docker. There should be another way of determining the Skosmos version.

**Comment by kinow** [comment]
Maybe we can include the version when building the image. Can't recall if there's an option to read the version from a static source, but if not it might require some little tweaking in the code.

**Comment by ArthurGenet** [comment]
Ok thank you for your answers, it is not a big deal, I was just wondering why it wasn't showing.

**Comment by osma** [comment]
Now the mechanism appears to be broken also without Docker: https://finto.fi/en/about

**Comment by osma** [comment]
I think we need something like bumpversion for Python projects, i.e. some way of keeping track of the Skosmos version number in a file that's accessible from PHP code.

**Comment by kinow** [comment]
I wonder if we could use `composer.json` perhaps? This diff in `composer.json`:

```diff
diff --git a/composer.json b/composer.json
index 1c3eafd8..ab866b5f 100644
--- a/composer.json
+++ b/composer.json
@@ -3,6 +3,7 @@
   "description": "Thesaurus and controlled vocabulary browser using SKOS and SPARQL",
   "type": "project",
   "license": "MIT",
+  "version": "v2.15-dev",
   "repositories": { 
     "lscache": {
       "type": "package",
```

Followed by `composer install`, then this change in the PHP code:

```diff
diff --git a/model/Model.php b/model/Model.php
index e6f58f3a..e7a08181 100644
--- a/model/Model.php
+++ b/model/Model.php
@@ -76,10 +76,7 @@ class Model
      */
     public function getVersion() : string
     {
-        $ver = null;
-        if (file_exists('.git')) {
-            $ver = rtrim(shell_exec('git describe --tags --always'));
-        }
+        $ver = \Composer\InstalledVersions::getRootPackage()['pretty_version'];
 
         if ($ver === null) {
             return "unknown";
```

Results in:

![image](https://user-images.githubusercontent.com/304786/164447143-9774f295-1bd5-414e-9396-d2dee6a739c9.png)

I found a few tools/libs[^1][^2][^3]  to bump the `composer.json` version, or that could be done manually too.

[^1]: https://www.npmjs.com/package/@pxlwidgets/php-composer-version/v/1.1.1
[^2]: https://github.com/talevskiigor/composer-bump
[^3]: https://github.com/quazardous/php-bump-version

**Comment by osma** [comment]
Great hints @kinow ! This looks like the correct and best way to do it.

>     https://www.npmjs.com/package/@pxlwidgets/php-composer-version/v/1.1.1 

This tool seems to be Node.js based, maybe not ideal since it requires that developers have a working Node environment which so far hasn't been a requirement for Skosmos development.

>    https://github.com/talevskiigor/composer-bump

This is from 2016 so may be outdated and unmaintained?

>    https://github.com/quazardous/php-bump-version

This is also from 2016.

Anyway we can do this manually as well if there's no suitable tool. We can just include it in the [Release Process](https://github.com/NatLibFi/Skosmos/wiki/Release-Process) documentation.
