### ISSUE TITLE
Exclude YSO concepts when counting the number of concepts in a domain ontology

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#123]
For each ontology published in Finto, the number of its concepts is shown in its metadata. At the moment, these figures seem incorrect. I presume the reason for this is that the number includes not only the domain ontology but also YSO to which the domain ontology is linked. These figures should be corrected, ie. YSO should be excluded from them.

**Comment by osma** [comment]
We could use the same logic as determining what goes into the alphabetical index.
