### ISSUE TITLE
Layout bug in display of notes

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1238]
## At which URL did you encounter the problem?
https://skosmos.dev.finto.fi/stw/en/page/?uri=http%3A%2F%2Fzbw.eu%2Fstw%2Fdescriptor%2F10286-6

## What steps will reproduce the problem?
1. Go to a concept which has reified notes in many languages, e.g. STW concept "Accelerators" (above URL)

## What is the expected output? What do you see instead?

The notes in both English and German are displayed on the same line:

![kuva](https://user-images.githubusercontent.com/1132830/140937803-94aedbf1-5039-4f47-93f2-381aec36d8ed.png)

Expected them to be on separate lines; though the German note wouldn't need to be displayed at all in this case since the content and UI languages are set to English.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by kinow** [comment]
I think this has been fixed already?

![image](https://user-images.githubusercontent.com/304786/141043427-f0f11f29-1509-4573-8669-9c91630f632c.png)

Screenshot above is Firefox on Ubuntu, but tested Chromium on Ubuntu, and it appears to be OK too, for English.

**Comment by kinow** [comment]
Ah! Resizing the screen caused the issue:

![image](https://user-images.githubusercontent.com/304786/141043559-673db60f-df84-4783-8697-e054aa9efdfc.png)
