### ISSUE TITLE
JavaScript error on hierarchy sort

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1270]
## At which URL did you encounter the problem?
https://dev.finto.fi/iptc/fi/index

## What steps will reproduce the problem?
1. Open console to see error messages
2. Select the Hierarchy tab on the left-hand sidebar
3. UI will say hierarchy is loading, the error log will say that hierarchy.js crashes with
`Uncaught Error: Syntax error, unrecognized expression: iptc newscodes: scene`

## What is the expected output? What do you see instead?
We should get the IPTC hierarchy sorted according to the configured notation

**Comment by joelit** [comment]
This issue could be related to IPTC having two concept schemes - <http://cv.iptc.org/newscodes/scene/> and <http://cv.iptc.org/newscodes/subjectcode/>

**Comment by osma** [comment]
Fixed in PR #1316, backported to the `v2.14-maintenance` branch, updated Finto.fi to use the fixed version.
