### ISSUE TITLE
Searching via API using the search term '0' without asterisk (0*) fails

### ISSUE THREAD

**Issue by miguelvaara** [NatLibFi/Skosmos#1275]
## At which URL did you encounter the problem?
https://api.dev.finto.fi/rest/v1/ykl/search?query=0

## What steps will reproduce the problem?
1. Go https://api.finto.fi/rest/v1/ykl/search?query=0 

## What is the expected output? What do you see instead?
It turned out that the fixes in the PR #1261 do not work completely (mostly it works :+1: ). There is still a problem with the searches with zeros ('0') if you do not use a trailing asterisk with the number zero. 

[https://api.finto.fi/rest/v1/ykl/search?query=0](https://api.finto.fi/rest/v1/ykl/search?query=0) should return a result containing the concept [https://dev.finto.fi/ykl/en/page/0](https://dev.finto.fi/ykl/en/page/0) (http://urn.fi/URN:NBN:fi:au:ykl:0) but it returns an empty result. 

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
FF

**Comment by kinow** [comment]
Strange, when I use YSO and use `query=0` it doesn't complain about the missing search parameter.

![image](https://user-images.githubusercontent.com/304786/154418920-971fd859-8f74-4f18-89fb-9823029340b5.png)

Any chance dev.finto is running an older version @miguelvaara ?

**Comment by kinow** [comment]
The header of `finto.fi` shows `v2.13`, while mine shows `v2.14-dev-27-g841dc1b2`. But `dev.finto.fi` is using the latest I think, and the search appears to work there.

In the issue description there are both api.finto and dev.finto. The dev version of the API appears to work OK?

- Instead of: https://api.finto.fi/rest/v1/ykl/search?query=0
- Using: https://api.dev.finto.fi/rest/v1/ykl/search?query=0

**Comment by kinow** [comment]
The issue description has URLs to dev.finto and to finto. The version in finto is a little behind, so it will display an older bug, saying that the query parameter is missing.

>should return a result containing the concept https://dev.finto.fi/ykl/en/page/0 (http://urn.fi/URN:NBN:fi:au:ykl:0) but it returns an empty result.

:+1:  if I search for `00` it works. `00.1` also brings the right results. But `0` is not returning the concept above :confused:

**Comment by kinow** [comment]
Found the :bug: : https://github.com/NatLibFi/Skosmos/blob/841dc1b21a9b522ca0dd0f2da641f69cdaeb4983/model/ConceptSearchParameters.php#L71

When `query=0`, the `!$term` evaluates to true, and it uses `label` instead. You can test with the URL: https://api.dev.finto.fi/rest/v1/ykl/search?query=0&label=0

PR with the fix on its way... :runner:
