### ISSUE TITLE
Need for contributing guidelines document

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1286]
## At which URL did you encounter the problem?

Skosmos wiki does not have a dedicated section for contibution guidelines.

## What is the expected output? What do you see instead?

Having a document describing reasonable conventions for handling issues and pull requests would help standardizing contributions (Mostly those that come outside sprints). This document could be linked in the PR template or in Skomos wiki

**Comment by osma** [comment]
Yes, this would be a good idea and standard practice in open source. Often this file is called `CONTRIBUTING.md` and stored within the repo itself (not the wiki). Some additional pointers:

* https://github.blog/2012-09-17-contributing-guidelines/
* https://en.wikipedia.org/wiki/Contributing_guidelines
* https://mozillascience.github.io/working-open-workshop/contributing/

**Comment by osma** [comment]
Actually we already do have a [CONTRIBUTING.md](https://github.com/NatLibFi/Skosmos/blob/master/CONTRIBUTING.md) document, but it's from 2016 and should be updated.
