### ISSUE TITLE
Possible open redirect

### ISSUE THREAD

**Issue by Amixtika** [NatLibFi/Skosmos#1289]
Go to: 

https://finto.fi/https://example.com

Select: "In English" on the top right, or any other language.

After that you will be redirected to www.example.com.

**Comment by osma** [comment]
Thanks for the issue.

I don't see this as an open redirect, as it requires the user to click on a link to https://example.com - but maybe I misunderstood something?

**Comment by Amixtika** [comment]
Hi Osma, 

The potential issue is that a user can be instructed to click on this link,  redirecting the user to a external malicous page.
