### ISSUE TITLE
Autocomplete problems after Bootstrap 5 upgrade

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1301]
## At which URL did you encounter the problem?

https://dev.finto.fi/yso/en/

## What steps will reproduce the problem?
1. Search for e.g. "cat" in YSO and wait for the autocomplete popup

## What is the expected output? What do you see instead?

This is how it works in finto.fi, running Skosmos 2.14:

![kuva](https://user-images.githubusercontent.com/1132830/164393482-e0d93808-fa7e-469e-a459-cc8869487ea3.png)

Here is how it looks with current master branch (dev.finto.fi):

![kuva](https://user-images.githubusercontent.com/1132830/164393205-8a61418f-441e-49f6-866b-67f0395f22cd.png)

There are at least three problems:

1. The entered string "cat" is shown with the wrong color. Minor CSS issue, probably in the Finto CSS file.
2. Matches on altLabels (e.g. "Catalan people") don't show the prefLabel of the matched concept ("Catalans").
3. The concept type information is missing.

This most likely broke with the Bootstrap 5 upgrade (PR #1182), which included an upgrade of the Typeahead.js widget.
Ping @kinow 

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by kinow** [comment]
>This most likely broke with the Bootstrap 5 upgrade (PR https://github.com/NatLibFi/Skosmos/pull/1182), which included an upgrade of the Typeahead.js widget.

Hi @osma! That does sound like a regression from #1182 :+1:  Will take a look next week (holiday this weekend/Monday).

**Comment by kinow** [comment]
> 1. The entered string "cat" is shown with the wrong color. Minor CSS issue, probably in the Finto CSS file.

Ah, that's an easy one to fix. @osma should we make the default to be that black/dark-gray from finto.fi, or leave as is?

Here's where we can change it to any other color: https://github.com/NatLibFi/Skosmos/blob/df06b5912e9518c1e1d7a6930f53d2e146402e71/resource/css/styles.css#L828

**Comment by osma** [comment]
> Ah, that's an easy one to fix. @osma should we make the default to be that black/dark-gray from finto.fi, or leave as is?

Right. Looking closer, it seems that this CSS block was added in PR #1182: https://github.com/NatLibFi/Skosmos/blob/df06b5912e9518c1e1d7a6930f53d2e146402e71/resource/css/styles.css#L826-L831

I'm not sure I understand the reason for this block. To me it seems that the only effective change is the text color, which is the problematic one. I tested dropping the whole block and couldn't see any problems with that. So I suggest that the block should be deleted, unless there is a reason for some of those rules.

**Comment by osma** [comment]
PR #1303 fixed the functional issues (2, 3).

Reopening because of the font color issue (1). Also the font size on the buttons ("English", "Search" in above screenshots) is slightly larger (16px / 1rem) than it used to be (14px), which I hadn't noticed before. I'll soon open a PR fixing these as well.
