### ISSUE TITLE
Support small mobile screens, e.g. iPhone 4/5

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#131]
Currently the vocabulary home page and concept display do not display well on small screens such as iPhone 4 and 5. Can be tested with http://iphone4simulator.com/ or http://iphone5simulator.com/ . Also parts of the autocomplete dropdown get cut off from the screen.

Should design and implement (using responsive CSS) solutions for these layout issues.

Requested by @catecara of FAO.

**Comment by osma** [comment]
Already works mostly OK with newer devices having larger screen resolutions. Moving to Blue Sky.

**Comment by henriyli** [comment]
The Twitter box seems to be broken on the ipad. I wonder if that's an issue with iphones as well.

![ipad](https://cloud.githubusercontent.com/assets/1152983/10534469/b90fbb80-73e1-11e5-8099-4818eb221516.jpg)
