### ISSUE TITLE
Concept-specific REST method groupMembers is missing an URI parameter in the swagger documentation

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1333]
## At which URL did you encounter the problem?

https://api.finto.fi/doc/#!/Concept45specific32methods/get_vocid_groupMembers

## What steps will reproduce the problem?
1. Try to send a request to the REST API using the swagger interactive documentation
2. You can fill in the vocab id and the request language, but no concept uri
3. The result https://api.finto.fi/rest/v1/yso/groupMembers?lang=fi will always be empty list

## What is the expected output? What do you see instead?
When querying the group members for a concept group, the uri of the concept group should be one of the parameters 

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Chromium

**Comment by joelit** [comment]
Ninja'ed by @danmichaelo in #1332 :smiley:

**Comment by osma** [comment]
A bit premature to close this when the PR is still unmerged?

**Comment by osma** [comment]
Ah, the PR was actually created just before this issue was opened. Anyway, the PR is now merged and there is no need to reopen this issue as the problem has been solved.
