### ISSUE TITLE
Enhancement: External authentication layer

### ISSUE THREAD

**Issue by YOUR1** [NatLibFi/Skosmos#1336]
Hi,

We are in need of a closed Skosmos environment that's only available through authentication (for example SAML). 

I've modified the v2.15 codebase so it suited my needs; see: https://github.com/NatLibFi/Skosmos/compare/master...ArchiXL:2.15-wikixl. 

I was wondering if this is something we would like to have in a future release?

**Comment by kinow** [comment]
>I've modified the v2.15 codebase so it suited my needs; see: master...ArchiXL:2.15-wikixl.

Is that a private repository? The link isn't working for me.

**Comment by YOUR1** [comment]
Hmm, that's weird. It's public, you can view it at https://github.com/ArchiXL/Skosmos/tree/2.15-wikixl.
