### ISSUE TITLE
Skosmos shouldn't show the modified timestamp for a concept page unless such is explicitly stated for the concept data

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1343]
## At which URL did you encounter the problem?

http://www.yso.fi/onto/yso/p508596

## What steps will reproduce the problem?
1. The concept page mentions a modified date - "Last modified 3/5/21"
2. The concept data in turtle format does not contain dct:modified of dct:created timestamps
3. The last modified data comes from the vocabulary's main concept page's info

## What is the expected output? What do you see instead?

The last modified date should be only shown when the concept has such data. Skosmos can still use the vocabulary's last modified data if such exists, to cache http requests, but this can be separate from the data displayed for a concept.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Chromium

**Comment by osma** [comment]
With the recent fix to YSO Places concept scheme level timestamps, this has now surfaced again. Many concept pages in YSO Places (e.g. [Tattariharju (Helsinki)](https://dev.finto.fi/yso-paikat/fi/page/p508739)) now show a recent modified date, even though the concept hasn't actually been modified.
