### ISSUE TITLE
Upgrade/replace malihu-custom-scrollbar ahead of jQuery upgrade

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1347]
## The current state of the package
https://github.com/malihu/malihu-custom-scrollbar-plugin
(Last update in Nov 2016)

## Suggested alternatives
https://www.jqueryscript.net/blog/Best-Custom-Scroll-Bar-jQuery-Plugins.html
https://openbase.com/js/malihu-custom-scrollbar-plugin/alternatives
Implementing the scrollbar in pure CSS might be worth exploring.

**Comment by osma** [comment]
We already have PR #1175 which is an attempt to replace malihu-custom-scrollbar with pure CSS. For some reason it has now been closed, I wonder why that happened?

**Comment by Vainonen** [comment]
Fixed in #1360
