### ISSUE TITLE
"show all X paths" message misplaced when concept has many paths

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1355]
## At which URL did you encounter the problem?

https://finto.fi/koko/en/page/p32086

## What steps will reproduce the problem?
1. Go to a concept with many (>4) paths in the hierarchy (e.g. above URL)

## What is the expected output? What do you see instead?

Expected to see four possible breadcrumb paths and the `[show all X paths]` link below them. Instead, the message appears in between the first and second paths:

![image](https://user-images.githubusercontent.com/1132830/188798640-1335e91e-4bbf-4300-9649-b131e0177a03.png)

This was likely caused by the Bootstrap 5 upgrade (ping @kinow)

(originally found by @kouralex )

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by kinow** [comment]
Huh, looks like the code is skipping 4 breadcrumbs, then hiding everything.

![Screenshot from 2022-09-07 18-30-52](https://user-images.githubusercontent.com/304786/188805401-920faaff-f056-4482-966f-3684a01a8f09.png)

But then it indeed adds the link to show more breadcrumbs after the first link.

![Screenshot from 2022-09-07 18-31-45](https://user-images.githubusercontent.com/304786/188805489-f87b3fbb-0da0-496a-9153-a005e2bf00b2.png)

Should be easy to fix :+1: Will try to prepare a PR soon.

**Comment by kinow** [comment]
@osma 

I manually removed the HTML node with that link. Then executed the code with the possible fix. Is this the correct location?

![image](https://user-images.githubusercontent.com/304786/188807703-8989b77a-b7a0-4522-9964-67892f424697.png)

The formatting is looking different than the breadcrumbs. Should I change that too?

I also couldn't find the commit that broke it. It appears to be adding the link after the first element already for some time - https://github.com/NatLibFi/Skosmos/commit/018fdc827b9425c70c10c50f195acdb61f9dc8b1. But maybe the new CSS rules broke it or made it more visible.

-Bruno

**Comment by osma** [comment]
Ah, hm. I probably misremembered the location. It's actually been on the right side of the paths, in the top right corner. Maybe there were some CSS rules placing it there that were lost in the Bootstrap 5 upgrade?

And yes, the font size and other styling should be the same as for the breadcrumbs - now the text looks bigger than it should.
