### ISSUE TITLE
images

### ISSUE THREAD

**Issue by PietroLiuzzo** [NatLibFi/Skosmos#1398]
## Description of the enhancement
I would like to show images directly in skosmos for example from skos:example

## Who are the users that would benefit from the enhancement and how?
Anyone with a thesaurus for visual resources who wants to immediately give in the thesaurus visual examples of what the concept refers to.

## What new functionalities would the enhancement make possible?
I could add in the RDF the link to an image served over IIIF for example and show it with the concept.

## Why is the enhancement important?
for my user  (art historians) the visual example is worth many descriptions... especially when trying to classify 

Eventually, perhaps this is already supported and I just did not find it.

Thanks a lot!

**Comment by kinow** [comment]
Interesting. Maybe add a JS IIIF library too to serve the images via the IIIF (I suspect your users might be familiar with that standard, @PietroLiuzzo).  Not sure if that's require something on the PHP side to process images too though.

**Comment by PietroLiuzzo** [comment]
<img width="830" alt="Screenshot 2023-01-17 at 15 41 34" src="https://user-images.githubusercontent.com/508012/212928125-24bf88a7-dc05-4214-88ea-714584777e81.png">
I would like to see directly embedded in the html page the linked images e.g. [](https://fotothek.biblhertz.it/bh/320px/bhex-2021-11-04.jpg) I use js libraries for this, like openseadragon in other context but I would not know where to change that in skosmos, I just installed it recently. Thanks a lot!

**Comment by PietroLiuzzo** [comment]
ok, I can follow this guidelines https://github.com/NatLibFi/Skosmos/wiki/Plugins perhaps

**Comment by kinow** [comment]
I was thinking exactly of openseadragon, and a simple IIIF manifest on the server side. But I **think** the Skosmos PHP side would then have to handle the re-scaling of images (haven't used IIIF in a long time, and last I used was with Cantaloupe).

The plugin idea sounds good too! Good luck @PietroLiuzzo !

**Comment by joelit** [comment]
You could build a plugin that shows images in the layout that makes sense in your use case, for example: https://finto.fi/hero/en/page/p2558
The widget source that shows images on the title row is here: https://github.com/NatLibFi/Skosmos-widget-hero
Specifically, you can re-use the render(id) -function: https://github.com/NatLibFi/Skosmos-widget-hero/blob/b498acb5046986e153d4362a606d6eb5a6bced02/widget.js#L24

The idea that Skosmos would handle caching and rescaling of embedded linked images does sound pretty tasty, too! (Maybe once the upcoming GUI overhaul is done.)

**Comment by PietroLiuzzo** [comment]
ok, so, I have managed, thanks a lot for your support! the examples were great and I could simply change the link into an img :)

**Comment by PietroLiuzzo** [comment]
<img width="1127" alt="Screenshot 2023-01-17 at 17 53 11" src="https://user-images.githubusercontent.com/508012/212961794-6ec8a4db-ffe0-43a0-b0de-df5360ecc5c3.png">
