### ISSUE TITLE
SKOS XL metadata for one language gets displayed for other languages as well

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1405]
## URL address of the page where you encountered the problem
https://dev.finto.fi/yso-paikat/fi/page/p100491?clang=en

## Description of the problem
Steps to produce the problem, and the expected outcome after it has been fixed

When a concept has a SKOS XL label with metadata in one language, it may be displayed as if the same metadata would apply also to labels in other languages if the prefLabels in different languages are identical. We just saw this in YSO Places with the place Äänekoski, whose name is identical in all three languages (fi, sv, en) but the English label comes from Wikidata, so we wanted to add SKOS XL for the English label indicating its source as Wikidata. The result looks like this:

![image](https://user-images.githubusercontent.com/1132830/219401991-55cc31b2-7c0a-4df6-aef1-f8b83fba46dd.png)

The info icons are displayed for all three languages, even though in reality the SKOS XL information only applies to the English label.

I suspect that this happens because of the way Skosmos matches SKOS XL Labels to SKOS Core labels (via skosxl:literalForm). When the labels are identical (apart from the language tag) they get mixed up.

## The browser you used when the problem appeared

Firefox

**Comment by nikopartanen** [comment]
The same issue was reported also here: #1389

**Comment by osma** [comment]
Right, this is a duplicate of #1389. Closing this one.
