### ISSUE TITLE
Tests fail at PHP 8.2

### ISSUE THREAD

**Issue by nichtich** [NatLibFi/Skosmos#1413]
## URL address of the page where you encountered the problem

Build Tests with PHP 8.2, e.g. https://github.com/NatLibFi/Skosmos/actions/runs/4221747584/jobs/7329412738

## Description of the problem

Dynamic properties are deprecated in PHP 8.2. It looks like these are only used at two places so fixing might be easy:

> Deprecated: Creation of dynamic property PluginRegister::$pluginOrder is deprecated in /app/model/PluginRegister.php on line 8
> Deprecated: Creation of dynamic property VocabularyConfig::$globalPlugins is deprecated in /app/model/VocabularyConfig.php on line 35

But I don't use PHP 8.2 locally so it's difficult to examine.

**Comment by osma** [comment]
Thanks for opening the issue and doing the initial analysis. We were aware of this but you beat us in creating the issue.
PHP version upgrades have often been quite painful (we only recently got 8.1 support sorted out), but this doesn't look that difficult on an initial glance as you pointed out.

**Comment by osma** [comment]
This was fixed for Skosmos 3 in PR #1546, merged a while ago.
Skosmos 2 will not support PHP 8.2 anyway.
Closing the issue.
