### ISSUE TITLE
Hovering over definitions

### ISSUE THREAD

**Issue by ZookieSwag** [NatLibFi/Skosmos#1417]
Is there any way to change the text in the border?

I would like it to say something else after I hover over it.

![image](https://user-images.githubusercontent.com/35275686/223824146-5711952a-8b15-4b0b-acb7-26711a19f923.png)

**Comment by nichtich** [comment]
The specific popover message is located in translation string `skos:note_help` in file `resource/translations/skosmos_en.po`. See [translation instructions](https://github.com/NatLibFi/Skosmos/wiki/Translation#updating-existing-translations). Pull requests are welcome.

**Comment by ZookieSwag** [comment]
Thank you, and sorry, one more question. In the Dockerfiles -> config -> config-docker.ttl. To add another vocabulary, would I just copy paste one of the current vocabularies in that file? Do i have to make additional changes in any other file?

Somthing like  this:
![image](https://user-images.githubusercontent.com/35275686/224117738-2aab0ca2-49d9-4779-b33e-a61b52288b31.png)

**Comment by nichtich** [comment]
Looks ok, but new vocabulary needs its own `void:uriSpace` matching concept from the vocabulary. In short, `dc:title`, `void:uriSpace` and `skosmos:sparqlGraph` should be adjusted for each vocabulary.
