### ISSUE TITLE
Skosmos hierarchy view breaks when typing new search

### ISSUE THREAD

**Issue by nikopartanen** [NatLibFi/Skosmos#1430]
## URL address of the page where you encountered the problem

https://finto.fi/yso/fi

## Description of the problem

When I type into YSO search the string "new" the hierarchy view breaks and the lines connecting the concepts disappear. The problem persists until one browses to other tabs and then back to hierarchy view, or refreshes the page. I have not found other strings than "new" which cause this issue. 

## Additional information (e.g. screenshots) about the problem

![image](https://user-images.githubusercontent.com/6486495/233069313-b2d108dc-4ce0-4ce3-a2c0-e127f4ed2630.png)

Seems to happen in both finto.fi and dev.finto.fi, also with all language versions.

## The browser you used when the problem appeared

Occurs both on Chrome and Firefox.

**Comment by joelit** [comment]
It seems the CSS for vakate/jstree breaks somehow. We'll change the implementation of the whole tree to something different in Skosmos 3.0

**Comment by joelit** [comment]
The impact of this bug is very small in Skosmos 2.x, and we won't be implementing the hierarchy with vakata/jstree in Skosmos 3.0, so it's safe to close this.
