### ISSUE TITLE
Removing dc:subject in config but still present in homepage UI

### ISSUE THREAD

**Issue by henrieglesorotos** [NatLibFi/Skosmos#1447]
## URL address of the page where you encountered the problem

https://github.com/NatLibFi/Skosmos/wiki/Configuration#:~:text=if%20not%20set-,dc%3Asubject,-optional - suggests removing this triple should remove it from the homepage. 

## Description of the problem
1. ingest data into named graph
2. create vocabulary using config.ttl 
3. remove dc.subject triple

## Additional information (e.g. screenshots) about the problem

Using forked version of skosmos. https://github.com/BeameryEdge/Skosmos 

## The browser you used when the problem appeared

Chrome

**Comment by osma** [comment]
A couple of things to check:

1. Are you using a cache in front of your triple store? Are you sure Skosmos got the updated version and not stale data from the cache?
2. Skosmos also shows a subject that corresponds to the vocabulary category, which can be set in config.ttl. So if for example you have a category "Geography" on the front page, then vocabularies in that category will show "Subject: Geography" on their front page.

The information on the vocabulary home page has many problems currently (e.g. #1416). We have just started development of Skosmos 3.x and it is going to be implemented in a different way.

**Comment by osma** [comment]
I see I may have misinterpreted the situation in my above comment. I was thinking about the vocabulary home page, not the main front page (vocabulary list).

I cannot reproduce the situation. I have a config.ttl file which sets up many vocabularies, all of them grouped by category.
I removed the dc:subject triple for one vocabulary in config.ttl and that vocabulary disappeared from the front page.

Can you provide more details what you did? For example, show a config.ttl snippet for a vocabulary that doesn't include a dc:subject triple, and a screenshot showing that the vocabulary still shows up on the front page vocabulary list.

**Comment by osma** [comment]
Closed due to lack of response. Please reopen if this is still relevant.
