### ISSUE TITLE
Twig templates for all Skosmos 3 page types

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1451]
## Description of the enhancement

Currently there are Twig templates for most, but not all, Skosmos 3 page types. We need at least initial versions of the remaining ones. It's OK if not all functionality is implemented.

- [x] front page / landing
- [x] vocabulary home
- [ ] concept
- [ ] global search results
- [ ] vocabulary search results
- [ ] about
- [ ] feedback
- [ ] error

**Comment by joelit** [comment]
Replacing this issue with:
* #1480
* #1481
* #1482 
* #1483 
* #1484 
* #1485 
* #1486
