### ISSUE TITLE
Skosmos UI loads in Arabic

### ISSUE THREAD

**Issue by namedgraph** [NatLibFi/Skosmos#1453]
Some users are reporting that the Skosmos UI loads in Arabic by default, without having chosen that language.

Will try to investigate and gather more information.

**Comment by osma** [comment]
What languages have been configured in `config.ttl` using `skosmos:languages`?

**Comment by namedgraph** [comment]
@osma we have the default value:
```
    skosmos:languages (
        [ rdfs:label "ar" ; rdf:value "ar_AE.utf8" ]
        [ rdfs:label "da" ; rdf:value "da_DK.utf8" ]
        [ rdfs:label "de" ; rdf:value "de_DE.utf8" ]
        [ rdfs:label "en" ; rdf:value "en_GB.utf8" ]
        [ rdfs:label "en_US" ; rdf:value "en_US.utf8" ]
        [ rdfs:label "es" ; rdf:value "es_ES.utf8" ]
        [ rdfs:label "fa" ; rdf:value "fa_IR.utf8" ]
        [ rdfs:label "fi" ; rdf:value "fi_FI.utf8" ]
        [ rdfs:label "fr" ; rdf:value "fr_FR.utf8" ]
        [ rdfs:label "it" ; rdf:value "it_IT.utf8" ]
        [ rdfs:label "nb" ; rdf:value "nb_NO.utf8" ]
        [ rdfs:label "nl" ; rdf:value "nl_NL.utf8" ]
        [ rdfs:label "nn" ; rdf:value "nn_NO.utf8" ]
        [ rdfs:label "pl" ; rdf:value "pl_PL.utf8" ]
        [ rdfs:label "pt" ; rdf:value "pt_PT.utf8" ]
        [ rdfs:label "pt_BR" ; rdf:value "pt_BR.utf8" ]
        [ rdfs:label "ru" ; rdf:value "ru_RU.utf8" ]
        [ rdfs:label "sv" ; rdf:value "sv_SE.utf8" ]
        [ rdfs:label "zh" ; rdf:value "zh_CN.utf8" ]
    ) ;
```
`ar` is suspiciously the 1st on the list ;) Is there some logic that makes the UI to default to the first value?

**Comment by osma** [comment]
[This](https://github.com/NatLibFi/Skosmos/blob/a6f1795c99165fd1af87b4a2b4f8509aa5dc1c37/controller/WebController.php#L76-L112) is the code that selects the language. The choice is informed by

1. SKOSMOS_LANGUAGE cookie, if it exists
2. (if inside vocabulary) default language of the vocabulary
3. Accept-Language header
4. If nothing above works, pick the first one from the language list

It looks like 4. happens, even though at least 3. should work in this case, as the request included an Accept-Language header which should have matched `en_US` and `en`.

But I think these response headers are suspicious:

```
Alt-Svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
Cf-Cache-Status: DYNAMIC
Cf-Ray: 7cb53b388a5f23e9-LHR
Server: cloudflare
X-Content-Type-Options: nosniff
```

These are not typical Skosmos/PHP/Apache response headers. Why is `Server: cloudflare` in there? Is this going through some frontend proxy? Is it possible that the response was cached earlier and the cache returns a stale response?

**Comment by namedgraph** [comment]
Yes there's a proxy in front.

We also have this in the config:
```turtle
    skosmos:language "en";
    skosmos:defaultLanguage "en";
```

Assuming `$acceptLanguage` is detected correctly, could it be that this `if` condition fails?
https://github.com/NatLibFi/Skosmos/blob/a6f1795c99165fd1af87b4a2b4f8509aa5dc1c37/controller/WebController.php#L106

If the `skosmos:languages` values are compared directly with `Accept-Language` values (without any replacement that I might have missed) it's not going to work, because they use different separators: `en_US` vs `en-US`.

**Comment by osma** [comment]
> We also have this in the config:
>
>    skosmos:language "en";
>    skosmos:defaultLanguage "en";

These are vocabulary specific settings. They are not relevant in this case, since the request was for the front page, outside of any vocabulary.

> If the skosmos:languages values are compared directly with Accept-Language values (without any replacement that I might have missed) it's not going to work, because they use different separators: en_US vs en-US.

That's a good point. I think you should use `rdfs:label "en-US"` in the config file.

**Comment by namedgraph** [comment]
Right.

But the lang codes are passed to the `\Negotiation\LanguageNegotiator` class which uses `_` because that's the PHP convention?

I'm guessing some sort of mapping has to happen between the two lang code conventions.

**Comment by namedgraph** [comment]
> I don't think there exists a PHP convention for language tags. Mostly the `en-US` style (BCP 47) is used everywhere on the internet, but Linux locale names typically use underscores as a delimiter instead (though this may vary between distributions).

PHP locale names is what I meant :)

> 
> So the `skosmos:languages` setting is effectively this mapping: the `rdfs:label` part gives the BCP 47 language tag, while the `rdf:value` gives the corresponding locale (for looking up things like date and time formats).

In this case the `en_US` and `pt_BR` language tags in `dockerfiles/config/config-docker-compose.ttl` are incorrect?
https://github.com/NatLibFi/Skosmos/blob/master/dockerfiles/config/config-docker-compose.ttl#L40

**Comment by osma** [comment]
> In this case the en_US and pt_BR language tags in dockerfiles/config/config-docker-compose.ttl are incorrect?

You are probably right. I was looking at [config.ttl.dist](https://github.com/NatLibFi/Skosmos/blob/master/config.ttl.dist) which is the default config for non-docker users. It does not have these language settings.

Can you verify that the problem is resolved if you change the underscores to hyphens in your config?

**Comment by namedgraph** [comment]
Will try :)
