### ISSUE TITLE
About Page twig-templates

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1485]
## Description of the enhancement

This issue is for making sure the initial version of the about page fulfills common requirements. It's OK if not all functionality is implemented.

- [x] Layout follows [the static example](https://github.com/NatLibFi/Skosmos/blob/skosmos-3-html/infopage.html)
 - [x] Main about.twig -template exists
 - [x] about.inc exists
 - [x] cypress tests exist

**Comment by osma** [comment]
All of these were completed long ago (back in May), closing the issue.
