### ISSUE TITLE
Feedback Page twig-templates

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1486]
## Description of the enhancement

This issue is for making sure the initial version of the feedback page fulfills common requirements. It's OK if not all functionality is implemented.

- [ ] Layout follows [the static example](https://github.com/NatLibFi/Skosmos/blob/skosmos-3-html/feedbackpage.html)
 - [ ] Main .twig -template exists
 - [ ] .inc -templates exist
 - [ ] [cypress tests](https://github.com/NatLibFi/Skosmos/blob/skosmos-3/cypress/e2e/feedback.cy.js) exist

**Comment by UnniKohonen** [comment]
Closed by mergin #1510
