### ISSUE TITLE
Error page twig-templates

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1487]
## Description of the enhancement

This issue is for making sure the initial version of the error page fulfills common requirements. It's OK if not all functionality is implemented.

- No static examples have been done
 - [x] Main .twig -template exists
 - [x] [cypress tests](https://github.com/NatLibFi/Skosmos/blob/skosmos-3/cypress/e2e/error.cy.js) exist

**Comment by osma** [comment]
This was completed in June, closing the issue.
