### ISSUE TITLE
Use dockerized Fuseki for PHPUnit tests

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#1488]
Currently we have set up PHPUnit tests so that Fuseki is installed by the [init_fuseki.sh](https://github.com/NatLibFi/Skosmos/blob/master/tests/init_fuseki.sh) script as a regular Java process. If necessary, the script downloads the Fuseki installation tarball from the Apache Jena download site, starts it up, and then loads the test vocabulary data from the `tests/test-vocab-data` directory using the s-put utility that comes with Fuseki.

For Skosmos 3, I would like to switch to a dockerized Fuseki instance instead of using a regular Java process. This would have the following benefits:

1. The same Fuseki container (together with dockerized Skosmos, both running via docker compose) can also be used for running Cypress tests
2. We can use the exact same container setup both under GitHub Actions CI and local developer machines
3. "Eat your own dogfood": it's good practice to make use of our own Dockerfiles now that we have them

# Prerequisites

We should first switch to the official Fuseki Dockerfile from Apache Jena; this is being worked on in PR #1477 by @kinow 

# How to implement

- init_fuseki.sh needs to be rewritten so it simply runs a `docker compose` command instead of the current code for downloading, installing and starting up Fuseki; also, test vocabularies should be loaded using e.g. `curl` since we don't have `s-put` available anymore
- some changes to the GitHub Actions CI configuration may be necessary
- CONTRIBUTING.md and the wiki documentation for [unit and integration tests](https://github.com/NatLibFi/Skosmos/wiki/Unit-and-integration-tests) should be modified accordingly (e.g. need to explain that Docker is necessary for running PHPUnit tests locally)

**Comment by kinow** [comment]
+1!!! Thanks @osma !

**Comment by osma** [comment]
Starting work on this, using the commits from PR #1477 as a starting point.

**Comment by osma** [comment]
Closed via #1496
