### ISSUE TITLE
`docker-compose` setup unsuitable for multiple Skosmos deployments

### ISSUE THREAD

**Issue by namedgraph** [NatLibFi/Skosmos#1511]
## Description of the problem
We want to deploy several Skosmos instances on the same machine, but the current `docker-compose.yml` has several issues that prevents this:
* unnecessary `container_name` properties on services, which makes container names conflict when the second instance is started
* `docker-compose.yml` file in a `dockerfiles` subfolder, which is used to construct container names (after explicit `container_name` are removed), e.g. `dockerfiles_skosmos_1`

My suggestion:
* remove `container_name` properties
* move `docker-compose.yml` to the top-level dir

Then we can launch Skosmos from 2 different folders, e.g. `Skosmos-A` and `Skosmos-B`, and the container names would become `skosmos-a-skosmos-1`, `skosmos-a-virtuoso-1` etc. and `skosmos-b-skosmos-1`, `skosmos-b-virtuoso-1`, respectively. That way they will not conflict.

**Comment by namedgraph** [comment]
`skosmos` container would have to be exposed to the host on different ports, but that can be easily done using `docker-compose.override.yml`:
```yaml
version: '3.7'

services:
  skosmos:
    ports:
      - 9091:80
```

**Comment by namedgraph** [comment]
I tested this and it works, except for the `docker-compose.override.yml` part 😅 Need to find a better way to override the ports, maybe use an `.env` file such as
```
SKOSMOS_PORT=9031
```
 and then something like `- ${SKOSMOS_PORT}:80`.

**Comment by osma** [comment]
Thank you for the suggestions @namedgraph . We have not (yet) been running multiple Skosmos instances in parallel using Docker Compose. The suggestions sound reasonable to me. Does @kinow have an opinion?

Previously we've tried to move all Docker-related files under `dockerfiles/` in a (perhaps futile) attempt to keep the top level directory structure as clean as possible.

**Comment by namedgraph** [comment]
`dockerfiles/` can stay, but `docker-compose.yml` should be top-level.

**Comment by kinow** [comment]
+1 on dropping the container name.

Not sure about moving the docker compose file. I haven't had that issue and am not sure if there is no other workaround, like a different way to handle the generated container names.

As for ports, we can omit the host ports (so it gets random ones assigned). Users can provide an override file if needed, and it should work in the containers network.

**Comment by namedgraph** [comment]
Added a PR with the changes that work on our private fork.

By default `docker-compose` builds container names from the name of the folder that it's located in. That's why `dockerfiles` would not make them unique.

**Comment by osma** [comment]
Thank you for the explanations @namedgraph
