### ISSUE TITLE
Changes for Cypress tests according to merged PR #1509

### ISSUE THREAD

**Issue by miguelvaara** [NatLibFi/Skosmos#1515]
## Description of the enhancement
Due to the changes produced by merged PR #1509, some adjustments also need to be made in the Cypress tests.

## Who are the users that would benefit from the enhancement and how?
Developers

(Name specific organizations, roles and/or communities if possible, and/or point to relevant discussion elsewhere)

## What new functionalities would the enhancement make possible?
The tests worked better and correctly

## Why is the enhancement important?
TDD ensures better software quality.

(Why should this be prioritized, instead of spending energy on something else? Who would do the work to make this happen?)

**Comment by MikkoAleksanteri** [comment]
Seems to be already done.
