### ISSUE TITLE
Difficulties displaying  the main thesaurus in the hierarchical view

### ISSUE THREAD

**Issue by dipso-num4sci** [NatLibFi/Skosmos#1535]
This issue is the same as https://github.com/NatLibFi/Skosmos/issues/1396, with a higher priority level.

Could someone help us to display our main thesaurus in the hierarchical view ?
Full details are given in the previously mentioned issue ( 1396 ).

Thank you very much !

**Comment by osma** [comment]
I'm closing this one and reopening the old one. It's better to keep using the original issue which contains all the history and context.
