### ISSUE TITLE
Typo on a Spanish label on the search page

### ISSUE THREAD

**Issue by Meron-E** [NatLibFi/Skosmos#1536]
## [URL address of the page where you encountered the problem](https://vocabularies.unesco.org/browser/thesaurus/es/search?clang=en&q=)
(https://vocabularies.unesco.org/browser/thesaurus/es/search?clang=en&q=)
## Description of the problem
Dear Osma,
There is a typo on a Spanish label on the search page above. It shows as 'delimte la búsqueda' instead of 'delimite la búsqueda'. We have made the correction on Transifex. Can you please update this on your next upgrade?
Best regards,
Meron
## Additional information (e.g. screenshots) about the problem
![image](https://github.com/NatLibFi/Skosmos/assets/148210172/964630c8-174b-4f63-8f78-0f3ddae08849)

**Comment by osma** [comment]
Thanks for the report. We will update all UI translations from Transifex when we make the next release 2.17, which will likely be the last release of Skosmos 2.x as we are concentrating on Skosmos 3 development.
