### ISSUE TITLE
E2E Test: Front page-> Vocab page -> search -> search results -> concept page

### ISSUE THREAD

**Issue by miguelvaara** [NatLibFi/Skosmos#1548]
## Description of the enhancement
The idea is to create an E2E test to ensure that arriving on the front page, navigating to YSO (General Finnish Ontology), using the search functionality in YSO and finally transitioning to the page of a selected concept from the search results are successful.

Create the test described below and involve testers in the process from the early stages by introducing them to the user story behind the test, and if necessary, adjust the test creation based on their feedback.

**The test should include the following steps:**

1) Go to the Finnish front page: http://localhost:9090/fi/
2) Change the UI language to English from the top bar
3) Select "YSO - Yleinen suomalainen ontologia (arkeologia)" from the vocabulary list
4) Change the language of the content to Finnish in the language selection of the concept page's search function (Forces partial page loading)
5) Write the word 'tiede' in the top bar's search box and press _enter._
6) Select the concept 'tiede' from the list and go to the concept page
7) After transitioning from the search results page to the concept page, you should land on the following page:
[http://localhost:9090/yso/fi/page/p2240](http://localhost:9090/yso/fi/page/p2240)

**Note!** The completed definition of ready for this issue will be described later, but as soon as possible, once the more general defining of the definitions of ready (for different issue types) currently in progress is completed.

## Who are the users that would benefit from the enhancement and how?
All Skosmos and Finto users benefit, potentially finally experiencing a service that operates more effectively and reliably.

(Name specific organizations, roles and/or communities if possible, and/or point to relevant discussion elsewhere)

## What new functionalities would the enhancement make possible?
More comprehensive and accurate end-to-end tests

## Why is the enhancement important?
The more comprehensive and thoughtfully designed our tests are, the better and user-friendly service becomes possible

(Why should this be prioritized, instead of spending energy on something else? Who would do the work to make this happen?)

**Comment by miguelvaara** [comment]
**Tips to help in the preparation of the test**

Forge the test described above as comprehensively as possible at the time of its creation. As the application evolves from a testing perspective, we are able to improve the test accordingly. If there are steps in creating the test that cannot be fully implemented, a step demonstrating and implementing it more modestly can be done. For example, if the application does not have a functional search field, it is possible to create a test using a URL-based search ([https://test.dev.finto.fi/yso/fi/search?query=kissa](https://test.dev.finto.fi/yso/fi/search?query=kissa)). When the search field is eventually ready, the test can be enhanced by replacing the modestly implemented test step with an improved implementation.

**Comment by osma** [comment]
Fixed in #1555, closing this
