### ISSUE TITLE
Alphabetic tab doesn't work with certain diacritic letters

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#1574]
## URL address of the page where you encountered the problem

https://finto.fi/yso/fi/index/%25C3%2584

## Description of the problem
Steps to produce the problem, and the expected outcome after it has been fixed

When viewing YSO at finto.fi, the alphabetic tab doesn't work with letters É, Š, Å, Ä and Ö. YSO has concepts starting with these letters, but none of these show up. Only the diacritic letter Ž gives results (visible when YSO content language is English). Non-diacritic letters seem to be working fine.

## The browser you used when the problem appeared

Tested with Firefox and Chrome with YSO content languages Finnish, Swedish and English. Same results.

**Comment by osma** [comment]
I think I found the problem. Some input sanitizing has been added quite recently for all kinds of information coming from the user, mainly URL parameters. What happened is that diacritical characters in the URL were being HTML escaped, e.g. `Ä` becomes `&Auml;` and this HTML entity doesn't work inside SPARQL queries.

I will create a PR with a propsed fix shortly.

**Comment by miguelvaara** [comment]
[like]  Vaara, Mika J reacted to your message:
________________________________

**Comment by osma** [comment]
Reopening; still needs to be addressed in Skosmos 3.
