### ISSUE TITLE
Switch Skosmos Git repo from (Skosmos 2) master to (Skosmos 3) main

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#1577]
## Description of the enhancement

Similarily to the switch in Annif, https://github.com/NatLibFi/Annif/issues/679, we should update the repository's master branch that has been following the current state of Skosmos 2.x development, to main branch that follows the Skosmos 3 development. 
 - Github applications for analysing the repo's code need to be updated

## Detailed list of sub-tasks

- [x] Rename master branch to skosmos-2 in GitHub GUI
- [x] Rename skosmos-3 to main in GitHub GUI
- [x] Switch repository default branch to main
- [x] Update Sonar Cloud
- [x] Update Scrutinizer
- [x] Update Code Climate
- [x] Update Codecov
- [x] Update Skosmos GitHub actions
- [x] Update server-side repos
- [x] Update webhooks
- [x] Update Skosmos documentation in Skosmos wiki
- [x] Update README.md and other similar files in the repo (skosmos-2 branch)
- [x] Update README.md and other similar files in the repo (main branch)
- [x] Write instructions for updating local development repositories
- [x] Inform the community in skosmos-users

**Comment by osma** [comment]
I changed the default branch to `main` in SonarCloud, Scrutinizer and Code Climate. We will find out soon if they are working properly after the change or not.

**Comment by osma** [comment]
Changes to documentation within the repo (README.md and SECURITY.md) are done in PRs #1578 (skosmos 2) and #1579 (skosmos 3).

**Comment by osma** [comment]
The GitHub project page now shows this message about the branch change:

![image](https://github.com/NatLibFi/Skosmos/assets/1132830/f0ce579a-38b0-4c4a-b488-d4e3585d3e19)

**Comment by osma** [comment]
I sent a [message](https://groups.google.com/g/skosmos-users/c/J771cMWj-Do/m/lqhFiK8ACAAJ) to skosmos-users explaining the changes.

All done, closing the issue.
