### ISSUE TITLE
Norwegian translations updated

### ISSUE THREAD

**Issue by olufine** [NatLibFi/Skosmos#1596]
Hi, I have just made some new translations in Transifex (Norwegian bokmål and ditto nynorsk). I have read the instructions on the [wiki](https://github.com/NatLibFi/Skosmos/wiki/Translation), but it's not clear to me what more I need to do to have it integrated into Skosmos.

**Comment by kinow** [comment]
At some point your translations will be reviewed in Transifex, and then imported by one of the Skosmos developers into the code, to be included in a future release.

**Comment by olufine** [comment]
Great! Although I do hope it doesn't take too long; one of my translations was tab label for _New and deprecated_  concepts, so it's quite visible.

**Comment by joelit** [comment]
Thanks for the translations @olufine! I published the updated Norwegian translations in [v2.17-maintenance branch](https://github.com/NatLibFi/Skosmos/compare/v2.17...v2.17-maintenance).  It is possible there will be a further skosmos 2.x release before Skosmos 3.0 is out, but it can take a bit. I hope this suffices in the mean time!.
