### ISSUE TITLE
The About page text is empty for non-core languages

### ISSUE THREAD

**Issue by CaptSolo** [NatLibFi/Skosmos#1642]
## Description of the problem
For core Skosmos languages the About page contains a short description of Skosmos along with a Github link.

For other languages the About page text is empty (e.g. [https://dati.lnb.lv/onto/lv/about](https://dati.lnb.lv/onto/lv/about)).

<img width="500" alt="image" src="https://github.com/user-attachments/assets/c3affd44-ee36-41d9-b030-a2c4b5536f15">

Related code: https://github.com/NatLibFi/Skosmos/blob/main/src/view/about-info.inc

What is the recommended approach for adding a translated description for other languages?

**Comment by osma** [comment]
Hi @CaptSolo !

Based on the screenshot and link, I suppose you are referring to Skosmos 2. The link to the "related code" you gave goes to Skosmos 3 code which is a bit different and still WIP...however, I will assume Skosmos 2 for now.

The idea is that you can copy `about.inc.dist` to `about.inc` and then customize it according to your needs, with the text and other elements you want to have on the About page of your Skosmos installation. There is a [little bit of explanation about this](https://github.com/NatLibFi/Skosmos/wiki/Configuration#aboutinc) in the wiki.

For example, for Finto.fi we have customized [our about.inc](https://github.com/NatLibFi/Finto-data/blob/master/conf/finto.fi/about.inc) with text and logos in four languages. This is a Twig template so it's possible to include some logic; there are if/else blocks checking the `request.lang` value and selecting the appropriate block. You could do the same if you want to have different content in different languages.

I hope this answered the question. I'm closing the issue, but please reopen if something is unclear!
