### ISSUE TITLE
Drop-down list scroll goes beyond browser window

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#172]
In a browser's resized mode (i.e. not full-screen), entering a search word in Finto front page's search field produces a drop-down result list whose scroll is not visible: the scroll goes beyond the browser window, or behind the general web page scroll. This was tested in a resized Firefox window with global search and the word "kissa", a word that produces a long list of results with scroll working nicely in the full-screen mode. See the screenshot:

![finto-scroll-not-shown](https://cloud.githubusercontent.com/assets/8860719/5659013/bd7f01b8-9713-11e4-9017-22945d4f4dcf.png)

**Comment by henriyli** [comment]
This should not happen anymore.
