### ISSUE TITLE
Limiting search results by parent does not seem to work

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Skosmos#173]
Try this:

1. Go to YSO ontology.

2. type "kis" to the search box and press enter

3. limit search by parent (yläkäsitteen mukaan), for example "kissaeläimet", the parent of concepts "kissa"

result:

the message "Sanasto ei sisällä termejä jotka alkavat kirjaimella ""!" appears.

**Comment by henriyli** [comment]
The form seems to submit without any parameters and thats why there's no results.
