### ISSUE TITLE
Language tag translations from CLDR

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#174]
As suggested by @danmichaelo in a comment to #144

And of course remove the language tags from the translation files since they become unnecessary (assuming that CLDR covers everything we have currently, which it should)

**Comment by osma** [comment]
Regression: The languages in the label statistics shown on the vocabulary home page are now just language tags, not the full language names they used to be.
http://dev.finto.fi/yso/fi/

**Comment by danmichaelo** [comment]
Great :clap:
