### ISSUE TITLE
Refactor away Concept.getPropertyParam

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#181]
The Concept class uses the getPropertyParam method a lot, for creating arrays representing concept properties and their values. This method should be refactored away and probably replaced with a constructor of a suitable class, probably ConceptProperty and/or ConceptPropertyValue which already exist, but they are not used everywhere.

**Comment by osma** [comment]
This will be done (probably has been already) as part of #190

**Comment by henriyli** [comment]
Implemented in the content-language branch and now merged into master.
