### ISSUE TITLE
Hierarchical concept group display

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#186]
The current display of hierarchical concept groups is quite messy. There are several states to consider, e.g. looking at the list of groups, looking inside a hierarchical group, and looking at the list of group members.

It might be better to implement the concept group display using a jsTree or similar widget, as is done for the hierarchy display. Using an external widget would require new REST methods for groups (which would be good to have in any case).

Wanted by Metatietosanasto

**Comment by henriyli** [comment]
This should now work.

**Comment by henriyli** [comment]
787d9be0753ba547cb3a262d34c33e9222a04d37
