### ISSUE TITLE
 Visually distinguish different concept types 

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#19]
Currently all concepts look the same, regardless of type.

There are a few cases where it would make sense to differentiate:
- concepts that should / shouldn't be used for annotation
- special ontology concepts vs. YSO concepts
- different source vocabularies in KOKO
- geographical concepts vs. regular concepts in YSA

Ways to distinguish:
- font colors (but this won't allow overlapping distinctions, as in KOKO)
- background colors (same as above)
- (colored?) symbols shown next to the concept

For special ontologies and YSO, this requires richer concept types than are currently available in the SKOS data. KOKO and YSA already have rich types.

**Comment by mirmaid** [comment]
Partly solved in other issues; issue is closed because it has been open but inactive for several years. If there is a related problem, a new, more clearly defined issue should be opened.
