### ISSUE TITLE
Allow setting content language separately from UI language

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#190]
In current Skosmos the UI language affects the content that is shown in many situations. We should change this, to allow the content language to be set separately from UI language (as e.g. in the [EuroVoc](http://eurovoc.europa.eu/) browser). We already have the beginnings of this in the search language selector, but this should be generalized and also applied in other situations such as the concept display.

This is a major enhancement that needs to be done in a feature branch.

**Comment by henriyli** [comment]
This has been implemented in the content-language branch and has now been merged into master.
