### ISSUE TITLE
Hierarchical groups not displayed correctly

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Skosmos#197]
Go Metatietosanasto: http://dev.finto.fi/metatietosanasto/fi/ and see the Group display tab.

Under "Toimijoiden suhteet"-group you see a group "Viittaus vastaavaan manifestaatioon".

"Viittaus vastaavaan manifestaatioon" should be under "Manifestaatioiden väliset suhteet" as seen from here: http://dev.finto.fi/metatietosanasto/fi/groups/viittaus_vastaavaan_manifestaatioon

**Comment by osma** [comment]
Will not be ready for 1.0.
