### ISSUE TITLE
Option to show more properties in search result list

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#198]
## At which URL did you encounter the problem?
http://finto.fi/sv/search?lang=&q=toimittajat&vocabs=allars+ysa

## What steps will reproduce the problem?
1. Search YSA and/or Allärs for e.g. "toimittajat"
2. Look at the search results page

## What is the expected output? What do you see instead?

The equivalent term(s) in Swedish (redaktörer + journalister in this case) is not shown in the search result list. The user must open the concept page to see the corresponding term, because in YSA and Allärs they are represented as exactMatch/broadMatch/narrowMatch links.

More generally, there may be other concept properties that would be desirable to have in search result lists. For example, scope notes and definitions are not currently shown in the search results, but for some vocabularies, they would be useful to show.

We could add a vocabulary-specific option like
```
:ysa skosmos:showPropertyInSearch skos:exactMatch, skos:broadMatch, skos:narrowMatch .
```
that enables display of the matching concepts in the search result list. This could then be enabled for YSA and Allärs, but probably doesn't make sense for other vocabularies.

Similarly to show scope notes and definitinos, one could have e.g.
```
:agrovoc skosmos:showPropertyInSearch skos:definition, skos:scopeNote .
```

Requested by @mariaforsen

**Comment by henriyli** [comment]
Showing the matching concepts still needs work, but scope notes, definitions should now work.

**Comment by henriyli** [comment]
Done.

**Comment by osma** [comment]
Doesn't work in global search, where it would be needed most at least for YSA/Allärs links
