### ISSUE TITLE
 Mixed languages for concept groups in global/multi-vocabulary search 

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#20]
## What steps will reproduce the problem?
1. Search from Allärs and YSA
2. search for 'katt'

## What is the expected output? What do you see instead?
Language of the properties is seemingly random

This is partly a data issue (YSA and Allärs groups having the same URIs but different labels), but mostly happense due to the way search is currently implemented: performing a CONSTRUCT query which mixes up information from up to 20 concepts at a time. With the current approach it is impossible to prevent this from happening occasionally.

In the next version, search should be implemented with a SELECT query that asks for only the relevant information. That should fix this issue too.

**Comment by osma** [comment]
YSA and Allärs nowadays use different group URIs, so this is no longer a problem. Closing.
