### ISSUE TITLE
Installation fails on Ubuntu 12.04 with php 5.4.36-1

### ISSUE THREAD

**Issue by armin11** [NatLibFi/Skosmos#201]
Hello,
I tried to install skosmos (master and 0.7.2) on my Ubuntu 12.04 with php5.4. The installation has nor Problems, but the Browser redirects to http://localhost/skosmos/fi/ which seems not to be available?
Apache2 mod_redirect is enabled and all other things are done as defined in the installation manual. 
All needed locales are also installed. Is there a missing php5 module?
Regrads from Germany
Armin

**Comment by osma** [comment]
Hi Armin!

Thanks for trying out Skosmos!

Based on your description it sounds like you have defined the language 'fi' in config.inc. Is this the case? How does your config.inc look?

**Comment by armin11** [comment]
Hi Osma,
I only copied the default version from config.inc,dist to config.inc and
there the fi language is active ;-) .
Do I need more files?


2015-02-10 10:09 GMT+01:00 Osma Suominen <notifications@github.com>:

**Comment by osma** [comment]
Does http://localhost/skosmos/fi/ give you an error? What kind of error?

It sounds like a possible problem with mod_rewrite - are you sure it is enabled for the directory where you have installed Skosmos?

**Comment by armin11** [comment]
Hi Osma,
thanx - this was the problem, I had to different Directory directives and
in the first one for the document root RewriteEngine On was not set :-( .
Now the Frontend appears - I will try further things ;-).
Do you have a simple vocabularies.ttl file for a single entrie in the
fuseki server as an example?
My current vocabularies file is appended.
Thanx in advance
Armin
p.s.: maybe you can adopt the documentation to include RewriteEngine On in
the relevant Directory directve ;-)



2015-02-10 10:14 GMT+01:00 Osma Suominen <notifications@github.com>:

**Comment by osma** [comment]
Strange - the .htaccess file that comes with Skosmos already has a "RewriteEngine on" directive. In my experience, the missing part is usually that you have to tell Apache to look at .htaccess files in the first place. For this you need to use the AllowOverride directive, but this is already covered in the installation guide. Are you sure that the "RewriteEngine on" directive was the missing piece for you?

As for vocabularies.ttl, I don't have an example with a single entry but you can just take the first one from the example file and delete all the others. You will also need at least one vocabulary category.

**Comment by armin11** [comment]
It was not only the RewriteEngine on - also the AllowOverride was not
defined in my DocumentRoot :-( .
But I installed it before in another place and there I didn't define the
RewriteEngine on. I think the normal installation will not be in the
document root, but in another place or directory.
Do I need to define a proxy it I'am behind one or did the application use
the http_proxy env from system?


2015-02-10 10:31 GMT+01:00 Osma Suominen <notifications@github.com>:

**Comment by armin11** [comment]
how I can add a german translation?

2015-02-10 10:36 GMT+01:00 Armin Retterath <armin.retterath@gmail.com>:

**Comment by osma** [comment]
>  I think the normal installation will not be in the document root, but in another place or directory.

Right. But if you install using the symlink method that is explained on the Installation page, it should be enough to enable AllowOverride for the DocumentRoot. Anyway I added a small clarification about this to the installation instructions.

> Do I need to define a proxy it I'am behind one or did the application use the http_proxy env from system?

Skosmos uses the EasyRdf library for outgoing HTTP connections, i.e. SPARQL queries and Linked Data access for external URIs. I'm not sure whether EasyRdf supports using a proxy in the current version, but I know that they are planning to start using the Guzzle3 library soon which I think should support proxies.

But I suppose you don't need to use a proxy for accessing Fuseki? Normally you'd run them both on the same server, so Fuseki would typically be on http://localhost:3030/

> how I can add a german translation?

That would be great! See https://github.com/NatLibFi/Skosmos/wiki/Translation

I suggest you do translations on the master branch as it has the most up to date code.

Once you've finished the translation, you can do a pull request. For example @danmichaelo recently contributed Norwegian Bokmål translation, see pull request #183.

**Comment by armin11** [comment]
tanks for the information - yes i've installed fuseki but i'm new to skos
and i need a practical example. i thought, that the trees are automatically
generated from the graph of fuseki
i imported the skos-rdf file like
./s-put -v http://localhost:3030/ds/data osiris ./Data/osiris_habitats.rdf
and get it back with:
./s-get http://localhost:3030/ds/data osiris
or
http://localhost:3030/ds/data?graph=osiris

<pre>

@prefix cc:    <http://creativecommons.org/ns#> .
@prefix owl:   <http://www.w3.org/2002/07/owl#> .
@prefix rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix dcterms: <http://purl.org/dc/terms/> .
@prefix skos:  <http://www.w3.org/2004/02/skos/core#> .
@prefix rdfs:  <http://www.w3.org/2000/01/rdf-schema#> .
@prefix foaf:  <http://xmlns.com/foaf/0.1/> .
@prefix dc:    <http://purl.org/dc/elements/1.1#> .

<http://www.natflo.de/codelist/osirishabitats>
        a               skos:Concept ;
        skos:broader    <http://www.natflo.de/codelist/osirishabitats/AA0>
, <http://www.natflo.de/codelist/osirishabitats/AA1> ;
        skos:prefLabel  "Codeliste für OSIRIS Habitate"@de .

<http://www.natflo.de/codelist/osirishabitats/AA0>
        a                   skos:Concept ;
        skos:exactMatch     <http://eunis.eea.europa.eu/eunishabitats/G1.6>
;
        skos:hasTopConcept  "osirishabitats" ;
        skos:narrower       <http://www.natflo.de/codelist/osirishabitats> ;
        skos:narrowerMatch  <http://eunis.eea.europa.eu/eunishabitats/G1.61>
, <http://eunis.eea.europa.eu/eunishabitats/G1.66> ;
        skos:notation       "AA0" ;
        skos:prefLabel      "Buchenwald"@de , "beech forest"@en .

<http://www.natflo.de/codelist/osirishabitats/AA1>
        a                  skos:Concept ;
        skos:broaderMatch  <http://eunis.eea.europa.eu/eunishabitats/G1.6> ;
        skos:narrower      <http://www.natflo.de/codelist/osirishabitats> ;
        skos:notation      "AA1" ;
        skos:prefLabel     "Eichen-Buchenmischwald"@de ;
        skos:relatedMatch  <http://eunis.eea.europa.eu/eunishabitats/G1.61>
, <http://eunis.eea.europa.eu/eunishabitats/G1.66> .

</pre>

maybe it will be easier for me to get a practical example from
finland
a simple example will be

http://finto.fi/ponduskategorier/en/

for this i get following rdf

http://api.finto.fi/download/ponduskategorier/ponduskategorier-skos.rdf -
hopefully from remote ?

but i need the vocabularies.ttl file from the productive system
http://finto.fi - for the "ponduskategorier" element

do you have this info ;-)

thanx in advance
armin


2015-02-10 11:36 GMT+01:00 Osma Suominen <notifications@github.com>:

**Comment by osma** [comment]
Do you mean this?

```
:ponduskategorier a skosmos:Vocabulary, void:Dataset ;
	dc:title "Pondus-kategoriat"@fi,
	"Ponduskategorier"@sv,
	"Pondus categories"@en ;
	dc:subject :cat_general ;
	void:uriSpace "http://www.yso.fi/onto/ponduskategorier/";
	skosmos:language "sv";
	skosmos:showTopConcepts "true";
	skosmos:fullAlphabeticalIndex "true";
	skosmos:shortName "Pondus";
	void:dataDump <http://api.finto.fi/download/ponduskategorier/ponduskategorier-skos.ttl> ;
	void:dataDump <http://api.finto.fi/download/ponduskategorier/ponduskategorier-skos.rdf> ;
	void:sparqlEndpoint <http://api.dev.finto.fi/sparql> ;
	skosmos:sparqlGraph <http://www.yso.fi/onto/ponduskategorier/> .
```

**Comment by armin11** [comment]
yes  -
 thanx - i will try further things ;-)


2015-02-10 11:53 GMT+01:00 Osma Suominen <notifications@github.com>:

**Comment by armin11** [comment]
i got a php error:

 12:09:38 Europe/Paris] PHP Fatal error:  Call to a member function
getCallable() on a non-object in
/tmp/skosmos-template-cache/46/81/796d7c5ef56fdaea06071be8236c.php on line
152
when adding the configuration to my vocabularies.ttl

 echo twig_escape_filter($this->env,
call_user_func_array($this->env->getFilter('lang_name')->getCallable(),
array((isset($context["langcode"]) ? $context["langcode"] : null),
(isset($context["lang"]) ? $context["lang"] : null))), "html", null, true);

maybe this has s.th. to do with the language?

i don't use a proxy at this time and i dont see any request to the fuseki
server when loading
http://localhost/skosmos/ponduskategorier/fi/

?



2015-02-10 12:02 GMT+01:00 Armin Retterath <armin.retterath@gmail.com>:

**Comment by osma** [comment]
> i got a php error:

I assume you are on the master branch? Have you installed the dependencies using Composer? Note that the master branch may have more dependencies than 0.7.x. It could be that you are missing the "punic/punic" extension which we recently started using (see issue #174). Try running Composer again.

> i don't use a proxy at this time and i dont see any request to the fuseki server when loading http://localhost/skosmos/ponduskategorier/fi/

Did you change the void:sparqlEndpoint setting in vocabularies.ttl? You should point it to your local Fuseki. Otherwise you will be accessing the Finto SPARQL endpoint :)

**Comment by armin11** [comment]
o no - i had the 0.7.2 - and will now go to the master ;-)

i thought, that the finto sparql endpoint is freely available? will a
distributed system be a problem?
i will go to master, change the sparql endpoint and edit the .po file ;-)

2015-02-10 12:33 GMT+01:00 Osma Suominen <notifications@github.com>:

**Comment by osma** [comment]
> i thought, that the finto sparql endpoint is freely available?

Yes it is (though it's not advertised a lot). But if you use it, don't expect to see requests to *your* Fuseki :) Feel free to use it for testing etc., but I understood you had your own SKOS data as well and wanted to use that.

> will a distributed system be a problem?

Generally, no. Of course if there's a significant round-trip time between the server running Skosmos and the SPARQL endpoint, it will lead to some delays in page generation.

**Comment by armin11** [comment]
for the german translation

now i will have lunch ;-)

2015-02-10 12:41 GMT+01:00 Osma Suominen <notifications@github.com>:

**Comment by armin11** [comment]
hi osma,
du you get the translation file? i attached it on the last mail. - you can
send me your email and i will send you the .po file again if github don't
allow attachments in the issue tracker ;-)

i now imported the ponduskategorier into the tbd and when i try to search i
get following error from fuseki:

16:25:51 INFO  [56] Query = PREFIX dc: <http://purl.org/dc/terms/> PREFIX
dc11: <http://purl.org/dc/elements/1.1/> PREFIX rdfs: <
http://www.w3.org/2000/01/rdf-schema#> PREFIX skos: <
http://www.w3.org/2004/02/skos/core#> SELECT ?cs ?label WHERE {  GRAPH <
http://localhost:3030/ds/data?graph=ponduskategorier/> {    ?cs a
skos:ConceptScheme .    OPTIONAL {      ?cs rdfs:label ?label .
FILTER(langMatches(lang(?label), 'sv'))    }    OPTIONAL {      ?cs
skos:prefLabel ?preflabel .      FILTER(langMatches(lang(?prefLabel),
'sv'))    }    OPTIONAL {      { ?cs dc11:title ?title }      UNION      {
?cs dc:title ?title }      FILTER(langMatches(lang(?title), 'sv'))    }  }
} ORDER BY ?cs
16:25:51 INFO  [56] 400 No dataset description in protocol request or in
the query string (2 ms)

my vocabularies.ttl is:
@prefix dc: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix wv: <http://vocab.org/waiver/terms/norms> .
@prefix sd: <http://www.w3.org/ns/sparql-service-description#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix skosmos: <http://purl.org/net/skosmos#> .
@prefix isothes: <http://purl.org/iso25964/skos-thes#> .
@prefix : <#> .


:ponduskategorier a skosmos:Vocabulary, void:Dataset ;
    dc:title "Pondus-kategoriat"@fi,
    "Ponduskategorier"@sv,
    "Pondus categories"@en ;
    dc:subject :cat_general ;
    void:uriSpace "http://localhost:3030/ponduskategorier/";
    skosmos:language "sv";
    skosmos:showTopConcepts "true";
    skosmos:fullAlphabeticalIndex "true";
    skosmos:shortName "Pondus";
    void:dataDump <
http://api.finto.fi/download/ponduskategorier/ponduskategorier-skos.ttl> ;
    void:dataDump <
http://api.finto.fi/download/ponduskategorier/ponduskategorier-skos.rdf> ;
    void:sparqlEndpoint <http://localhost:3030/sparql> ;
    skosmos:sparqlGraph <
http://localhost:3030/ds/data?graph=ponduskategorier/> .



:categories a skos:ConceptScheme;
        skos:prefLabel "Skosmos Vocabulary Categories"@en .

:cat_general a skos:Concept ;
        skos:topConceptOf :categories ;
        skos:inScheme :categories ;
        skos:prefLabel "Categories"@en .



2015-02-10 13:50 GMT+01:00 Armin Retterath <armin.retterath@gmail.com>:

**Comment by osma** [comment]
Wow, that was fast! But I didn't get the po file - as you guessed GitHub doesn't understand/allow attachments to issue tracker messages. Maybe you could send it to me at osma.suominen@helsinki.fi - unless you'd like to make a fork and a pull request? :) That would be awesome!

> 16:25:51 INFO [56] 400 No dataset description in protocol request or in the query string (2 ms)

My guess is that your void:sparqlEndpoint setting is wrong, it probably should be <http://localhost:3030/ds/sparql>, you're missing the /ds/ part.

You are using a rather curious graph name `http://localhost:3030/ds/data?graph=ponduskategorier/`, it's not wrong of course as graph URIs can be any valid URI, but I think it's maybe more sensible to use the base URI of the dataset as the graph name (in this case <http://www.yso.fi/onto/ponduskategorier/>)

Also you've redefined void:uriSpace to http://localhost:3030/ponduskategorier/ - this really should come from the data itself, and unless you've modified the actual triples in the data, you should keep the original value here i.e. also "http://www.yso.fi/onto/ponduskategorier/"
Things should still work with your setting but you will get nicer looking page URLs in Skosmos if this setting matches the actual data.

**Comment by osma** [comment]
I think these problems are sorted out now. Closing this issue.
