### ISSUE TITLE
Groups tab opens the whole group list when a group is open

### ISSUE THREAD

**Issue by sinipessala** [NatLibFi/Skosmos#217]
## What steps will reproduce the problem?
1. http://finto.fi/yso/fi/groups/p26564
2. Click its group (to page http://finto.fi/yso/fi/groups/p26564 )
3. Click "Ryhmät" tab
OR
3. Click "Hierarkia tab"
4. Click "Ryhmät" tab

## What is the expected output? What do you see instead?
Expected:
Since the group view is open (the concept shown is a group) the group tab should always show the concepts in that group. And the page URL should remain the same
Instead:
When "Ryhmät" is clicked, group tab shows the list of all the groups in the ontology. Also, it changes the URI of the page to be http://finto.fi/yso/fi/groups .

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by osma** [comment]
This will need to be reconsidered after implementing hierarchical groups with jsTree (#186)

**Comment by osma** [comment]
This is working now with the new hierarchical group implementation.
