### ISSUE TITLE
Infinite loop in JS code when hierarchy contains a cycle

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#221]
## At which URL did you encounter the problem?

http://localhost/Skosmos/mesh/en/page/D004989
## What steps will reproduce the problem?
1. Open concept page for "Ethics" in MeSH
## What is the expected output? What do you see instead?

Expect to see the hierarchy to the left. But instead it keeps displaying the "Loading..." message and the JavaScript console shows this error:

InternalError: too much recursion
blob:http://localhost/3d83a23a-2f05-4cc7-9df3-991e9a466a50
Line 3

The problem is triggered by a cycle in the MeSH hierarchy.

Related to #220 but that was in PHP code.
## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by henriyli** [comment]
The infinite recursion occurs when jstree tries to build the tree into the dom. There isn't really much we can do about this unless we write a cyclic object detection algorithm and run it before giving the data to jstree.

**Comment by henriyli** [comment]
The JSON.stringify/JSON.parse trick introduced in de36fd6ba54faea8bb5a8e16b212507179ae3c5b happens to prevent jstree from crashing with too much recursion. The "tree" is never given to jstree as the functions used detect the circularity before creating the object.

**Comment by kouralex** [comment]
Seems like this issue can now be closed?

**Comment by osma** [comment]
Right.
