### ISSUE TITLE
Identical entries in closely matching concepts in LCSH

### ISSUE THREAD

**Issue by sinipessala** [NatLibFi/Skosmos#228]
## At which URL did you encounter the problem?

https://github.com/NatLibFi/Skosmos/issues/182
## What steps will reproduce the problem?
1. Look at the closely matching concepts
## What is the expected output? What do you see instead?

Expected: that all of the matching concepts would be different from their label

Instead: there are two matches in LCSH with the term "Semantics"
## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by osma** [comment]
The example URL is wrong, but this one (aerodynamiikka / Aerodynamics) works: http://finto.fi/yso/fi/page/p20101

This is really (mostly) a data problem. The YSO concept does have links to those two LCSH concepts, and the target concepts have identical labels in LCSH. What could possibly be done here is to add some kind of qualifier (the LCSH URI?) to disambiguate, but whether that would help the user, I'm not so sure...

On the other hand, at least in the Aerodynamics example, [one of the LCSH concepts](http://id.loc.gov/authorities/subjects/sh99002253.html) has the note "Use as topical subdivision under individual land vehicles and types of land vehicles." I'm not sure this is a valid mapping target. It could be argued that only the ["real" Aerodynamics concept](http://id.loc.gov/authorities/subjects/sh85001295.html) should be mapped to from YSO. @satuniininen?

**Comment by osma** [comment]
Now I see that the original example concept was "semantics": http://finto.fi/yso/fi/page/p6804

Also in this case [one of the LCSH target concepts](http://id.loc.gov/authorities/subjects/sh2001008780.html) has a note "Use as a topical subdivision under individual languages and groups of languages". Maybe YSO should avoid mapping to this kind of topical subdivisions in LCSH?

**Comment by MikkoAleksanteri** [comment]
This is mostly a data related issue.
