### ISSUE TITLE
Display information about subproperties of skos:altLabel

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#234]
Various vocabularies have term types which can be considered subtypes of skos:altLabel, for example synonymLabel and deprecatedLabel. Currently they can be modelled as subproperties of skos:altLabel but in Skosmos they work essentially as normal altLabels.

We could display more information about these terms (i.e. the name of the property that was used) in the "Terms in other languages" section on the concept page. See attached mockup (edited screenshot), which depicts this example data:

```
pto:deprecatedLabel a owl:AnnotationProperty,
            rdf:Property;
      rdfs:subPropertyOf skos:altLabel ;
      rdfs:domain pto:TskConcept, pto:PaikhakConcept ;
      rdfs:label "hylättävä termi"@fi, "deprecated term"@en, "avrådd term "@sv ;
      rdfs:range xsd:string .

paikhak:test a pto:TskConcept,
        skos:Concept ;
    pto:deprecatedLabel "fiDepr"@fi, "svDepr"@sv, "enDepr"@en ;
    skos:altLabel "fiDepr"@fi, "svDepr"@sv, "enDepr"@en ;
    dc:source "testi lähde"^^xsd:string ;
    skos:definition "Testi määritelmä."@fi ;
    skos:inScheme pto: ;
    skos:prefLabel "fiPref"@fi, "svPref"@sv, "enPref"@en ;
    skos:altLabel "fiAlt"@fi, "svAlt"@sv, "enAlt"@en .
```

![deprtest2-1-edited](https://cloud.githubusercontent.com/assets/1132830/7176690/3047cff6-e429-11e4-89de-12c0ee55a307.png)

**Comment by devseppala** [comment]
For abbervations and other premissable types of labels/terms it is good to inherit them form skos:altLabel, but I think it is not a good choice for deprecatedLabel and should be avoided if possible.

skos:altLabel is a completely permissable alternative for prefLabel in describing the concept. The deprecated label/term is the complete opposite, a term that you should NOT use to describe the concept. In terminological vocabularies it is used to explicitly warn users of common mistakes. Deprecated label can also have some sub-types that specify more accurately why the term is deprecated ie. oldLabel

If in the future this data is used in some other context, it would be an easy mistake for the application/user interpret the deprecatedLabel as an allowed synonym. If deprecated label is defined as a sub-property of altLabel.

But I am not sure that if even skos-xl would solve this problem.

I don't think it would be necessary to display the deprecatedLabel property in the "Terms in other languages" section, but in that case the "DEPRECATED TERM" section should display the deprecated labels in all languages.

**Comment by osma** [comment]
I'm trying to better understand your requirements for deprecatedLabel. I tried to see how deprecated labels/terms are discussed in relevant standards to better understand what is the best way to represent them in RDF and whether there are any best practices available.

SKOS [says very little](http://www.w3.org/TR/skos-primer/#secalt) about what altLabel actually means. In particular, it does not say that "skos:altLabel is a completely permissable alternative for prefLabel in describing the concept". But the example use cases mentioned in the SKOS Primer are synonyms, abbreviations, quasi-synonyms etc., so not very close to being deprecated terms.

ISO 25964-1 also says surprisingly little about use cases for non-preferred terms (which are modelled as skos:altLabel or skosxl:altLabel in the [ISO 25964 RDF representation](http://pub.tenforce.com/schemas/iso25964/skos-thes/)). "Deprecated" terms are not discussed at all in the standard as far as I can tell (I only have a paper copy so can't perform a full text search).

In MADS/RDF there is a property [deprecatedLabel](http://www.loc.gov/standards/mads/rdf/v1.html#deprecatedLabel), defined as "A label once considered authoritative (controlled and curated) but which is no longer." It is represented as a sub-property of skos:hiddenLabel. But I don't think this matches your intent, because you explicitly want deprecatedTerms to be displayed (in all languages!), and also you don't say that they would necessarily have been authoritative in the past.

Maybe we can keep this issue open for the original purpose, representing subproperties of skos:altLabel, but open another issue for deprecated labels (or more generally, making it possible to display values in all languages for specific properties, instead of just the current language).

**Comment by osma** [comment]
Moving to Blue Sky because apparently this wouldn't solve the use case for deprecated labels, which was the original intent.

**Comment by devseppala** [comment]
I completely agree the standard is rather vague about the usage of altLabel and I am glad that you do see my point. I admit I somewhat exaggerated my description of altLabel-property, but I think that impression is easy to get when reading the standard.

Looking at your standards references, I must mention that TSK works with terminological vocabularies, which are different from thesauris and library oriented klowledge organization systems. They have similarities, but also fundamental differences. To some extent this problem stems from the fact that SKOS has not been designed with terminological vocabularies in mind.

Just for reference, standards more relevant to terminological field include:
http://en.wikipedia.org/wiki/ISO/TC_37

NTRF:
http://www.nordterm.net/filer/NTRF/Ntrf.pdf

Anyhow, we do have the need to use deprecatedLabels, and if the only way to get them to use in reasonable time is to define them as a sub property of altLabel, then i guess that is what should be done.

The visual presentation of these labels in the screen capture is OK. However, I just noticed that the finnish altLabel is not displayed. It could be just that my skosmos test system is not set up correctly.

**Comment by osma** [comment]
Yes, I am aware that terminological vocabularies have their own rules. Thank you for the NTRF reference, I wasn't aware of that standard. It is a very traditional record format but indeed they have the notion of deprecated terms (DTE).

However, it is not obvious how terminological vocabularies could be represented in RDF. I haven't seen any relevant standards. I tried to look up "deprecatedLabel" and similar properties/classes in [Linked Open Vocabularies](http://lov.okfn.org/dataset/lov/) but could only find SKOS and MADS/RDF.

> Anyhow, we do have the need to use deprecatedLabels, and if the only way to get them to use in reasonable time is to define them as a sub property of altLabel, then i guess that is what should be done.

Actually, a better approach is probably to use a separate, custom property for these (possibly a subproperty of skos:hiddenLabel) and to define it as a multilingual property (see issue #234).

**Comment by devseppala** [comment]
If you want to look up more information on the usage of deprecated terms in vocabularies, these are the relevant ISO standards (TC37):

ISO 10241-1 Terminological entries in standards - Part 1: General requirements and examples of presentation

ISO 12620 Terminology and other language and content resources - Specification of data categories and management of a Data Category Registry for language resources

ISO 26162 Systems to manage terminology, knowledge and content - Design, implementation and maintenance of terminology management systems

**Comment by devseppala** [comment]
For future reference, I just happened to look at TBX-basic specification and noticed that it has four different data types for term classification under the administrativeStatus property: preferred, admitted, notRecommended and obsolete.

http://www.terminorgs.net/downloads/TBX_Basic_Version_3.1.pdf#page=17

http://www.isocat.org/rest/dcs/331

**Comment by osma** [comment]
Thank you for the references @devseppala !

I wonder if there are any defined RDF representations for TBC-Basic or other TC37-related standards...

**Comment by devseppala** [comment]
Just Googled "TBX RDF" and found some interesting results such as this:
http://www.w3.org/community/bpmlod/wiki/Converting_TBX_to_RDF

However, this kind of complete representation of TBX in RDF-syntax does get rather complex.

Also, TBX-basic does not simplify the structure of a concept entry, it only limits the available data categories (used to describe the concept) to finite set.
http://www.isocat.org/rest/dcs/331

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
