### ISSUE TITLE
REST methods should not try to set locale

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#237]
## At which URL did you encounter the problem?
http://localhost/Skosmos/rest/v1/ic/label?uri=http://iconclass.org/46C1261&lang=fr
http://localhost/Skosmos/rest/v1/ic/broader?uri=http://iconclass.org/46C1261&lang=fr
http://localhost/Skosmos/rest/v1/ic/broaderTransitive?uri=http://iconclass.org/46C1261&lang=fr
http://localhost/Skosmos/rest/v1/ic/narrower?uri=http://iconclass.org/46C1261&lang=fr
http://localhost/Skosmos/rest/v1/ic/narrowerTransitive?uri=http://iconclass.org/46C1261&lang=fr
http://localhost/Skosmos/rest/v1/ic/children?uri=http://iconclass.org/46C1261&lang=fr
http://localhost/Skosmos/rest/v1/ic/related?uri=http://iconclass.org/46C1261&lang=fr

(there may be more cases but at least these are problematic)

## What steps will reproduce the problem?
1. Try to use REST methods with a lang parameter that is not among the UI languages

## What is the expected output? What do you see instead?

Getting a warning like this:
Warning: Unsupported language 'fr', not setting locale in /var/www/Skosmos/controller/Controller.php on line 73

The problem is that language information is passed via locale using the getAndSetLanguage and setLanguageProperties methods. But not all content languages can be passed via locale.

This is a generalization of #231 which fixed the hierarchy method but not the others.

**Comment by henriyli** [comment]
I'm not sure what to do with the statistics methods. They don't seem to be using the language for other than including it into the response. Type returns gettext translated labels so there you actually need to set the locale.

**Comment by osma** [comment]
All the important cases seem to be fixed. I don't think we need to do anything for the remaining methods (statistics etc). If it turns out there is a problem, we can open a new issue.
