### ISSUE TITLE
Support for multilingual properties

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#238]
When displaying concept property values on the concept page, normally the values are filtered so that only values in the current selected language are shown, except for skos:prefLabel and skos:altLabel which have their own specialized display that also shows other languages ("terms in other languages").

For some properties such as deprecatedLabel and (possibly) skos:scopeNote and skos:definition in some vocabularies, it could be useful to show also values in other languages.

We could have a vocabulary-specific configuration setting such as this in vocabularies.ttl:

```
:pto a skosmos:Vocabulary, void:Dataset ;
    skosmos:hasMultilingualProperty pto:deprecatedLabel .
```

Then those properties would be shown with all language values, not just the current one.

This is related to #234. Visibility of deprecatedLabel in all languages requested by @devseppala

**Comment by devseppala** [comment]
Sounds like a very welcome feature, +1

It would be perfect if a similar configuration variable could be made to control the display of other properties than prefLabel and altLabel in the alphabetical index?

**Comment by osma** [comment]
> It would be perfect if a similar configuration variable could be made to control the display of other properties than prefLabel and altLabel in the alphabetical index?

This is not so easy, because the alphabetical index (and text search which you would probably want too) uses the text index for performance, and the text index needs to know which RDF properties to index. So supporting anything else than prefLabel/altLabel/hiddenLabel in the alphabetical index and text search means also reconfiguring the text index, not just Skosmos. Also the SPARQL queries in many places assume the SKOS label properties, it would be quite difficult to make them more generic.

**Comment by devseppala** [comment]
OK, so the configuration variable for the index is out of the question for the time being.

Can you give any estimate of when this skosmos:hasMultilingualProperty configuration variable could be expected to be implemented in skosmos and taken to use in Finto.

**Comment by osma** [comment]
We are currently trying to finish 1.1. Once it is out (expected in a few weeks) we could consider this for the 1.2 cycle. But we will make a separate decision about what to focus on in 1.2 once 1.1 is out. We aim for a one-month release interval but in practice it has often been longer.

**Comment by devseppala** [comment]
I just thought that would it be possible to implement this configuration variable so that it would be  defined in the same ontology file where property itself is defined? I think it might be better to keep the configuration variables together within the ontology/metadata file, than to place them to the top skosmos configuration file.

Like this for example:
<pre>
pto:deprecatedLabel a owl:AnnotationProperty,
            rdf:Property;
      rdfs:domain pto:TskConcept, pto:PaikhakConcept ;
      rdfs:label "hylättävä termi"@fi, "deprecated term"@en, "avrådd term "@sv ;
      rdfs:range xsd:string ;
      <b>skosmos:hasMultilingualProperty "true"</b>;
.
</pre>

**Comment by osma** [comment]
This should still be documented in the wiki

**Comment by henriyli** [comment]
Documentation updated.

**Comment by devseppala** [comment]
There is a disparity between the implementation and the documentation of this functionality.

Wiki documentation tells to use skosmos:hasMultilingualProperty and the code expects skosmos:hasMultiLingualProperty

difference is capital L in
lingual vs.
Lingual

**Comment by devseppala** [comment]
I just can't get this to work, despite of correcting the error mentioned in previous post.
<pre>
vocabularies.ttl:
:pto a skosmos:Vocabulary, void:Dataset ;
        skosmos:hasMultiLingualProperty pto:deprecatedLabel .

pto-skos.ttl:
pto:deprecatedLabel a rdf:Property,
        owl:AnnotationProperty ;
    rdfs:label "deprecated term"@en,
        "hylättävä termi"@fi,
        "avrådd term"@sv ;
    rdfs:domain pto:PaikhakConcept,
        pto:TskConcept ;
    rdfs:range xsd:string .
</pre>

Enabling skosmos:hasMultiLingualProperty for pto:deprecatedLabel just makes the contents of "deprecated term" disappear if the UI language is same with the label language. The section "hylättävä termi" should say "insinööridatumi", now it's just empty (after enabling  skosmos:hasMultiLingualProperty). In addition, it does not show up on other UI languages either.

![deprecatedlabel](https://cloud.githubusercontent.com/assets/11884684/10366549/e4092cf4-6dd3-11e5-89b6-b1aa2c5669a3.png)

**Comment by osma** [comment]
> Wiki documentation tells to use skosmos:hasMultilingualProperty and the code expects skosmos:hasMultiLingualProperty

Good catch, thanks! Fixed the documentation.

About the other problem, we need to investigate...
