### ISSUE TITLE
Random label language shown

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#244]
## At which URL did you encounter the problem?
http://skosmos.dev.finto.fi/agrovoc/en/page/c_33269?clang=ru
http://skosmos.dev.finto.fi/agrovoc/en/page/c_330903?clang=ru

## What steps will reproduce the problem?
1. Look at AGROVOC in Russian

## What is the expected output? What do you see instead?

Some labels in the concept display, hierarchy and breadcrumbs are shown in Spanish, Czech, Turkish, Hungarian, Italian... This happens when there is no Russian label. The labels are then shown in a random language.

It would make sense to fall back to the default language of the vocabulary (English for AGROVOC). Only as a last resort (when there is no label in the default language) should a random language be shown.

**Comment by henriyli** [comment]
Still need to fix the property labels in the concept page.
