### ISSUE TITLE
Hierarchy view does not show narrowers for current concept in some cases

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#246]
## At which URL did you encounter the problem?
http://dev.finto.fi/yso/fi/page/p1302

## What steps will reproduce the problem?
1. Go to above URL

## What is the expected output? What do you see instead?
Expected to see the narrower concepts of the current concept in the hierarchy view also. Those are not visible even though they are included in the rest response.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by henriyli** [comment]
Still fails when the concept has a broader concept that has multiple broaders. We're mildly abusing jstree since it doesn't really support multiple inheritance. I think it might help if we'd use something randomly generated instead of the uri as the parents attribute.

**Comment by osma** [comment]
Good enough for 1.1, postponing to Next Tasks
