### ISSUE TITLE
Better placement for timestamps on concept page

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#247]
Currently the timestamps (created, modified) are shown right in the middle of the concept page. We should find a better place for them. I can see two options:

1. Move them towards the bottom (e.g. just before the URI)
2. Find a completely different place for them, similar to how news articles on the web have the publication date near the headline

I will try to produce mockups of these options...

**Comment by osma** [comment]
Option 1: move lower
![timestamps-lower](https://cloud.githubusercontent.com/assets/1132830/7388708/00063d22-ee70-11e4-9a0e-2a0036d2b34b.png)

**Comment by osma** [comment]
Option 2: separate place (something like this)
![timestamps-alt](https://cloud.githubusercontent.com/assets/1132830/7388788/c4e1b2de-ee70-11e4-9e25-6bd95e4329b3.png)

**Comment by osma** [comment]
Need better mockups for option 2, then decide on layout

**Comment by henriyli** [comment]
Option 2A:
![kissa](https://cloud.githubusercontent.com/assets/1152983/9268130/9147e474-4263-11e5-90f1-0c19ab921470.png)

Option 2B:
![kissa ylanurkka](https://cloud.githubusercontent.com/assets/1152983/9268140/b4518f2e-4263-11e5-85d5-97aaa04e724d.png)

Option 2C:
![kissa alaoikea](https://cloud.githubusercontent.com/assets/1152983/9268145/c347d42a-4263-11e5-9fd1-81cb68e00198.png)

Option 2D:
![kissa alaoikea](https://cloud.githubusercontent.com/assets/1152983/9268149/d078faa2-4263-11e5-9290-3c2d73f39577.png)

**Comment by osma** [comment]
Option 2C chosen

The text should be
"Created XXXXX, modified YYYYY"
"Created XXXXX"
"Modified YYYYY"
