### ISSUE TITLE
Mac & Safari: repeated auto-refreshing related to Group Index and browser back button

### ISSUE THREAD

**Issue by epkeskitalo** [NatLibFi/Skosmos#248]
## At which URL did you encounter the problem?

http://finto.fi/yso/en/groups

## What steps will reproduce the problem?
1. Go to http://finto.fi/yso/en/groups (or another Group Index view)
2. Click any group, e.g. http://finto.fi/yso/en/groups/p26561
3. Click browser's back button. Browser begins to refresh the page repeatedly. 

## What is the expected output? What do you see instead?

Expected: going back to previously viewed page. Instead: Page is displayed correctly but is then refreshed repeatedly. 

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Safari 8.0.5, Mac OS X 10.10.3. In the same OS, the issue does not occur in Chrome or Firefox 31.6.0

**Comment by osma** [comment]
Thank you for the report. Probably related to AJAX page loading and handling of the history buffer.

**Comment by osma** [comment]
I tried to reproduce this using several online iPad emulators, but none of them had a working back button. Oh well, need to borrow a real device.

**Comment by epkeskitalo** [comment]
I'm sorry to say but the issue is still there.

**Comment by henriyli** [comment]
Did you try http://dev.finto.fi/yso/en/groups ? The fix hasn't yet been backported into the production version.

**Comment by epkeskitalo** [comment]
My bad! Dev works fine.
