### ISSUE TITLE
Multiple matching concepts with same label not shown

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#251]
## At which URL did you encounter the problem?
http://dev.finto.fi/yso/en/page/p1780

## What steps will reproduce the problem?
1. Look at the appendix

## What is the expected output? What do you see instead?
Expected to see both lcsh matches, but a programming error causes the second one with the same label to disappear.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by osma** [comment]
Unit test would be nice
