### ISSUE TITLE
Deprecated concepts visible in concept hierarchy

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#255]
## At which URL did you encounter the problem?
http://dev.finto.fi/yso/fi/page/p13419?clang=en

## What steps will reproduce the problem?
1. Look at the three different concepts in the hierarchy view.
2. Two of them are deprecated concepts.

## What is the expected output? What do you see instead?
Deprecated concepts should not be shown in the hierarchy.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by osma** [comment]
This is more of a data issue. There shouldn't be broader/narrower relations in YSO for deprecated concepts. Apparently there still are some.

Moving to Next Tasks for considering whether to try to address this in Skosmos code.

**Comment by osma** [comment]
Moving to Blue Sky. We can reconsider this if this is still a problem *after* the data has been fixed.

**Comment by osma** [comment]
No longer a problem with the current data.
