### ISSUE TITLE
"Any language" selection fails

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#259]
## At which URL did you encounter the problem?
http://finto.fi/yso/fi/

## What steps will reproduce the problem?
1. Go to YSO front page
2. Select "Any language" / "kaikilla kielillä" from the language dropdown

## What is the expected output? What do you see instead?

Expected that the selection would be shown in the dropdown, but the dropdown still shows the previously selected language. It appears that the selection still applies.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by henriyli** [comment]
I cherry-picked the fix to the v1.1-maintenance branch in d1653f9a02c0a5b732320045973e965af98ca971
