### ISSUE TITLE
Random language shown for mapped concepts in external vocabularies

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#262]
## At which URL did you encounter the problem?
Used to be visible here:
http://finto.fi/afo/fi/page/p1197
http://finto.fi/afo/fi/page/p158

## What steps will reproduce the problem?
1. Open a concept with a mapping link to an external multilingual vocabulary (e.g. AGROVOC)
2. Look at the mapping links on the concept page

## What is the expected output? What do you see instead?

In the above cases AFO concepts had mappings to AGROVOC concepts (and AGROVOC is not available in finto.fi/dev.finto.fi so the labels have to be looked up via Linked Data requests). The labels for the matching AGROVOC concepts were shown in a random language, usually Chinese.

The expected outcome would be to see labels for matching external concepts

1. in the current content language, if available
2. any of the content languages of the current vocabulary (English would match in this case)
3. any language

**Comment by osma** [comment]
The practical problem is how to reproduce this, now that AGROVOC links were removed from AFO due to this problem. We would need a test vocabulary that has mapping links to AGROVOC concepts.

It is easy to add the AGROVOC links back to AFO - just edit [filter-afo.sparql](https://github.com/NatLibFi/Finto-data/blob/master/vocabularies/afo/filter-afo.sparql) and remove the row that checks for skos:closeMatch, then recreate the SKOS file (using toskos.sh). I don't want to do this now because of this bug.

**Comment by osma** [comment]
Similar problem, probably caused by the same issue:

In this case the user is using properties from the Organization Ontology. The labels for these properties get looked up (as I understand it, via HTTP requests), but Spanish labels are shown.

```
GENDER 	    male

TRABAJA EN LA SEDE 	    Turun toimisto (fi)

OCUPA 	    toimitusjohtaja (fi)
```

**Comment by osma** [comment]
Here is an example where this actually happens:
http://finto.fi/koko/fi/page/p11794

There is a mapping for a HPMULTI concept which is shown as "Touristen (de)", even though HPMULTI has labels in many languages including Finnish. The Finnish label should be shown here instead.

**Comment by henriyli** [comment]
This would seem to be working correctly now at least in the HPMULTI + KOKO use case. 
http://dev.finto.fi/koko/fi/page/p11794

**Comment by babslgam** [comment]
hi, sorry to comment on this already closed issue, but i think it occurs in our project.
https://vocabs.acdh.oeaw.ac.at/traveldigital_thesaurus/en/page/?clang=de&uri=https%3A%2F%2Fvocabs.acdh.oeaw.ac.at%2Ftraveldigital%2FConcept6005600

in our case if there's no german label available we want to show the english one.
to solve it, a new vocabulary config property like skosmos:defaultLanguageForExternalVocabs could be introduced and looked up here https://github.com/NatLibFi/Skosmos/blob/439a5777545b72a8eaf691b6fe0ce8df9b94bb74/model/ConceptMappingPropertyValue.php#L80

**Comment by osma** [comment]
Thanks for noting this @babslgam , however, I think it would be better to open a new issue.
Just recently we implemented a new configuration property `skosmos:fallbackLanguageOrder` (see #688), do you think the same property could be used in this case as well?
Anyway please open a new issue so we can continue from there.
