### ISSUE TITLE
Support multiple Concept Schemes in hierarchy display

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#263]
Currently Skosmos really only supports one concept scheme per vocabulary. If there are several, one must be set using skosmos:mainConceptScheme and it will be the visible one.

It should be possible to support multiple concept schemes within a vocabulary. Especially I'm thinking of the hierarchy widget. When support for multiple concept schemes is enabled (perhaps via an option in vocabularies.ttl, if not auto-detected from data), the hierarchy should show the concept schemes at the highest level; top concepts for each scheme would be shown below those.

The REST API already mostly supports this: the vocabulary information method (just the vocid itself e.g. [YSO](http://api.finto.fi/rest/v1/yso/)) returns concept schemes and their labels; and the `topConcepts` method takes a `scheme` parameter.

The missing piece is mostly adding support for this in the jsTree-based hierarchy visualization widget.

This would be useful at least for PTVL, maybe also others (e.g. YSO has deprecated concepts and aggregate concepts in separate concept schemes that are currently not visible).

**Comment by osma** [comment]
Also useful for vocabularies managed using VocBench. VB supports multiple Concept Schemes, but not ISO 25964 concept groups. PoolParty is similar AFAIK.

**Comment by osma** [comment]
When implementing this, also NALT can be used as a test case, since it has several concept schemes.

**Comment by henriyli** [comment]
This should now work as expected.

**Comment by osma** [comment]
@henriyli Were there any changes related to this that affected the REST API methods? If they changed, the documentation should be updated.

**Comment by dgbroeder** [comment]
Hi, since this issue was closed I would expect that SKOSMOS would now support multiple concept schemes per vocabulary and show them separately. However I cannot make this work. Is there some special option to set in the configuration file? I note that also when viewing YSO the deprecated and aggregated concept vocabularies (still) remain invisible?
thanks, Daan
