### ISSUE TITLE
Show notations in hierarchy

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#264]
Currently notation codes (e.g. in PTVL and Iconclass) are shown only on the concept page.

For classification-style use, it would be useful to show them also in the hierarchy display. This probably needs an extension to the REST API so that notations are returned alongside labels in the hierarchy-related methods.

**Comment by osma** [comment]
UDC Summary has a good implementation of this: http://www.udcc.org/udcsummary/php/index.php?lang=en

**Comment by henriyli** [comment]
The topconcepts are now too properly displayed thanks to 276bda6b33bfc3c65d444df7da187ee162c09c79

**Comment by henriyli** [comment]
The concept hierarchy doesn't seem to be finding broader siblings. And there is something wrong with the top concepts too. See: http://dev.finto.fi/ptvl/fi/page/?uri=http%3A%2F%2Furn.fi%2FURN%3ANBN%3Afi%3Aau%3Aptvl%3ATT1.1

**Comment by henriyli** [comment]
This should now work. af743b1ed330e2cc95bb5ca426c4615bb1b1768e

**Comment by osma** [comment]
Should document on the [REST API](https://github.com/NatLibFi/Skosmos/wiki/REST-API) wiki page that some of the methods also return notation.

**Comment by henriyli** [comment]
The documentation has been updated.
