### ISSUE TITLE
Sort by notation

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#265]
In many places (apart from the alphabetical index) concepts are sorted alphabetically:

* on concept page, when displaying semantic relations
* in the hierarchy display
* in the group members display

For classification-style usage, it would be better to sort these concept lists by notation values (there should be an option in vocabularies.ttl to enable this).

Probably #264 must be implemented first.

**Comment by osma** [comment]
Should this be configurable?

**Comment by henriyli** [comment]
The notations can now be seen in the sidebar group view ca9d8672ff5c3b350253a24b885559d5fea84240
