### ISSUE TITLE
Installation using a symbolic link as described in doc does not work (HTML base not set correctly)

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#274]
(using code from master branch)
I have followed the documentation at https://github.com/NatLibFi/Skosmos/wiki/Installation to install SKOSMOS, and created a symbolic link from my DocumentRoot to the skosmos source dir.
The base URL in the HTML page is not set correctly, and turns to something like :

http://localhost/skosmos/the/full/path/where/skosmos/lives

which obviously makes every JS and CSS loading fails.

The problem does not appear if I put the source code directly under Apache DocumentRoot without using a symbolic link.

**Comment by osma** [comment]
Thank you for reporting this. Will need to investigate.

**Comment by osma** [comment]
I was able to replicate the problem. 

This seems to have been introduced by changes made to implement #225. The new `guessBaseHref` method in WebController doesn't handle the symlink case. It is based on [this recipe](http://blog.lavoie.sl/2013/02/php-document-root-path-and-url-detection.html) which actually acknowledges that there may be problems with symlinks...

**Comment by tfrancart** [comment]
Hello

I tried to install Skosmos from 1.9-maintenance, and I stumbled upon this problem again. Actually this happens when you use a different directory name than the symlink that is being created, e.g.

/var/lib/skosmos-1.9 and /var/www/html/skosmos

Using /var/lib/skosmos instead of /var/lib/skosmos-1.9 solves the problem.
