### ISSUE TITLE
Group index does not display group collections hierarchy correctly and hides child collections when parent collections are opened

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#276]
(using source from master, jena 1.3.0 but with generic dialect).
I am testing SKOSMOS with the SKOS UNESCO Thesaurus available at http://skos.um.es/unescothes/downloads.php
This thesaurus contains a "header" of 2 levels of collections (micro-thesauri grouped into domains). Micro-thesauri and domains are declared as skos:Collection. 
The "Group index" tab of SKOSMOS displays all the collections in a flat list, while I would expect only the first-level domains to be displayed :

![skosmos-groups-state-1](https://cloud.githubusercontent.com/assets/2728945/9384931/d1ba2f4a-4753-11e5-9654-98225ed7d20d.png)

(note how "Educational administration" is shown at the same level than "Education").

Then when I open the nodes corresponding to the first-level domains, like the node "Education", the child micro-thesauri are removed from the first level of the tree :

![skosmos-groups-state-2](https://cloud.githubusercontent.com/assets/2728945/9384987/1ad62800-4754-11e5-97a3-0e389b0c2859.png)

(note how "Educational administration" is now shown correctly under "Education", and has been removed from the first level of the tree).

So when I have opened all the first-level domains, I have the expected display :

![skosmos-groups-state-3](https://cloud.githubusercontent.com/assets/2728945/9385016/4077d68a-4754-11e5-9af9-d88ff6f6bef0.png)

This last screenshot is what I would expect when browsing the group hierarchy of that thesaurus.

Thanks - Let me know if this is not clear ;-)

**Comment by osma** [comment]
Thanks for reporting. The support for hierarchical groups is a recent feature (#186) and apparently we have only considered collections (or concept groups) nested using the isothes:superGroup feature.

UNESCO Thesaurus uses regular skos:member to link between collections, e.g.

```
unescothes:COL005 a skos:Collection;
   skos:prefLabel "Information and communication"@en;
   skos:prefLabel "Information et communication"@fr;
   skos:prefLabel "Información y comunicación"@es;
   skos:prefLabel "Информация и коммуникация"@ru;
   skos:notation "5";
   skos:inScheme unescothes:CS000;
   skos:member unescothes:COL505;
   skos:member unescothes:COL510;
   skos:member unescothes:COL515;
   skos:member unescothes:COL520;
   skos:member unescothes:COL525;
   skos:member unescothes:COL530;
   skos:member unescothes:COL535;
   skos:member unescothes:COL540;
   skos:member unescothes:COL545.
```

Here all localnames beginning with COL seem to be SKOS Collections.

So we need to adjust at least the SPARQL queries that handle hierarchical collections/groups.

**Comment by tfrancart** [comment]
Hello

Thanks for looking into this - and thanks for building and providing
SKOSMOS, by the way !

2015-08-21 8:49 GMT+02:00 Osma Suominen <notifications@github.com>:

> Thanks for reporting. The support for hierarchical groups is a recent
> feature (#186 <https://github.com/NatLibFi/Skosmos/issues/186>) and
> apparently we have only considered collections (or concept groups) nested
> using the isothes:superGroup feature.
>
> UNESCO Thesaurus uses regular skos:member to link between collections, e.g.
>
> unescothes:COL005 a skos:Collection;
>    skos:prefLabel "Information and communication"@en;
>    skos:prefLabel "Information et communication"@fr;
>    skos:prefLabel "Información y comunicación"@es;
>    skos:prefLabel "Информация и коммуникация"@ru;
>    skos:notation "5";
>    skos:inScheme unescothes:CS000;
>    skos:member unescothes:COL505;
>    skos:member unescothes:COL510;
>    skos:member unescothes:COL515;
>    skos:member unescothes:COL520;
>    skos:member unescothes:COL525;
>    skos:member unescothes:COL530;
>    skos:member unescothes:COL535;
>    skos:member unescothes:COL540;
>    skos:member unescothes:COL545.
>
> Here all localnames beginning with COL seem to be SKOS Collections.
>
Absolutely. And this is perfectly valid SKOS as per SKOS rule S32 (
http://www.w3.org/TR/2009/REC-skos-reference-20090818/#L3312) : "The
rdfs:range of skos:member is the union of classes skos:Concept and
skos:Collection."

> So we need to adjust at least the SPARQL queries that handle hierarchical
> collections/groups.
>
The strange thing is that the correct tree hierarchy is displayed after
opening the first-level domains, so it looks like it almost work. But this
is maybe just a side-effect.
I emphasize that quite a lot of other thesauri are using this
2-levels-of-Collection-header technique to organize their concepts (Eurovoc
and Gemet, at least).

Cheers
Thomas

> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NatLibFi/Skosmos/issues/276#issuecomment-133306889>.
>



-- 

*Thomas Francart* -* SPARNA*
Web de *données* | Architecture de l'*information* | Accès aux
*connaissances*
blog : blog.sparna.fr, site : sparna.fr, linkedin :
fr.linkedin.com/in/thomasfrancart
tel :  +33 (0)6.71.11.25.97, skype : francartthomas

**Comment by henriyli** [comment]
This should now work as expected.

**Comment by tfrancart** [comment]
Thanks !
