### ISSUE TITLE
Links to groups don't show the group hierarchy in context

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#282]
## At which URL did you encounter the problem?
http://dev.finto.fi/metatietosanasto/fi/groups/?uri=http%3A%2F%2Fmetatietosanasto.fi%2Farvonimi

## What steps will reproduce the problem?
1. Go to above URL

## What is the expected output? What do you see instead?

The group information is shown correctly, but the group hierarchy on the left only shows the top level groups, not where we are in the group hierarchy

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by henriyli** [comment]
Still broken at http://dev.finto.fi/metatietosanasto/fi/groups/yhteison_jasen
