### ISSUE TITLE
Hierarchical groups in "belongs to group" no longer working

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#285]
## At which URL did you encounter the problem?
http://dev.finto.fi/metatietosanasto/fi/page/?uri=http%3A%2F%2Fmetatietosanasto.fi%2Fabbedissa

## What steps will reproduce the problem?
1. Go to above URL
2. Look at "Kuuluu ryhmään" (belongs to group)

## What is the expected output? What do you see instead?

Expected to see the group hierarchy, in this case "Henkilö > arvonimi". Instead seeing only "arvonimi".

I think this kind of hierarchical display was implemented in #111 but it has since stopped working. With the latest changes to replace isothes:superGroup support with nested skos:member I noticed that this was not working, but when I tried a previous version (a5ed3b82f472fbc18f13254dc0cee1467afe47be) with the data still containing isothes:superGroup relations, it still didn't work. So I think this has been broken for a while.

In any case I think the code in [Concept.php](https://github.com/NatLibFi/Skosmos/blob/master/model/Concept.php#L454) and view/concept-shared.twig that currently deals with isothes:superGroup should be adapted to look at skos:member relations between groups instead.

**Comment by osma** [comment]
I think that after this issue is done, there should be no mention of `isothes:superGroup` anymore in PHP code or templates.

**Comment by henriyli** [comment]
fixed in 419e9cd88940f7b291f2a345afe6bc10734554e3
