### ISSUE TITLE
PHP warning in RestController.php line 550

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#300]
## What is the expected output? What do you see instead?

Seeing messages like this in the log:
[Fri Sep 18 15:26:38 2015] [error] [client 128.214.223.196] PHP Notice:  Undefined variable: lang in /var/www/finto.fi/controller/RestController.php on line 550

**Comment by henriyli** [comment]
This has now been fixed and backported to v1.2-maintenance.
