### ISSUE TITLE
PHP warning in GenericSparql.php line 1166

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#301]
## What is the expected output? What do you see instead?

Seeing errors like this in the log:

[Fri Sep 18 15:17:43 2015] [error] [client 66.249.78.211] PHP Notice:  Undefined
 variable: preflabel in /var/www/finto.fi/model/sparql/GenericSparql.php on line
 1166, referer: http://finto.fi/kassu/sv/page/s16670519

**Comment by henriyli** [comment]
This has now been fixed and the fix has been backported to the maintenance branch.
