### ISSUE TITLE
Base href detection fails when running on Windows

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#309]
## At which URL did you encounter the problem?
http://localhost/Skosmos/

## What steps will reproduce the problem?
1. Install Skosmos (current master) on Windows (with XAMPP PHP and Apache) under c:\xampp\htdocs\Skosmos
2. Open front page

## What is the expected output? What do you see instead?

The `base href` tag has an invalid value:
```html
<base href="http://localhostC:\xampp\htdocs\Skosmos\controller">
```

This can be worked around by setting BASE_HREF in config.inc.

**Comment by henriyli** [comment]
This fixed the issue on my windows 7 + xampp installation. Should this be backported?
