### ISSUE TITLE
Autocomplete selection fails on IE

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#315]
## At which URL did you encounter the problem?
https://finto.fi/ysa/fi/

## What steps will reproduce the problem?
1. Use Internet Explorer 11
2. Go to YSA front page
3. Enter "aak" in search box
4. Select "Aakenustunturi" from the dropdown

## What is the expected output? What do you see instead?

Expected to get to Aakenustunturi concept page.
Instead getting to URL https://finto.fi/ysa/fi/ysa/fi/page/Y105695 which gives a 404 error

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Internet Explorer 11

**Comment by henriyli** [comment]
Fixed in 9e2fc6a8d174d65a8ab272aa1aa1b8d6ddde3584
