### ISSUE TITLE
Search restriction layout broken in IE

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#316]
## At which URL did you encounter the problem?
https://finto.fi/ysa/fi/search?clang=fi&q=kissa&vocabs=

## What steps will reproduce the problem?
1. Perform search in YSA using IE 11
2. Look at the search results page

## What is the expected output? What do you see instead?

The layout of the restriction dropdowns looks broken. See screenshot.

![ie-rajaus](https://cloud.githubusercontent.com/assets/1132830/10225039/8b6fb26c-6869-11e5-89cd-61b0692c44f1.png)

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Internet Explorer 11

**Comment by henriyli** [comment]
This has been fixed in 452f6aef8384117edcef878e3ac5ff7f076f3f93 , fc453bad950b55cca22c56921342912e81c63e5b and a81c00963265c81165caf8e3d8ca8be24aa637b2
