### ISSUE TITLE
Add French translation

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#330]
A French translation has been started but is currently at just 7%. Anyway it should be added to Skosmos when it's ready.
https://www.transifex.com/national-library-of-finland/dashboard/all_resources/fr_FR/?project=skosmos

**Comment by tfrancart** [comment]
Just translated all the labels. Could the demo website be updated so I can validate the translation ?
Thanks !

**Comment by osma** [comment]
@tfrancart Thanks! The demo site is now updated: http://skosmos.dev.finto.fi/fr/

**Comment by tfrancart** [comment]
Thanks I have reviewed and fixed some french translations

**Comment by osma** [comment]
OK, need to update again

**Comment by osma** [comment]
Also on demo site now.
