### ISSUE TITLE
Group notations is not always shwon in Group index hierarchy

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#331]
http://skosmos.dev.finto.fi/unesco/en/groups/?uri=http%3A%2F%2Fskos.um.es%2Funescothes%2FCOL240

The group tree on the left displays notation only for level-2 groups, but not for the top-level groups.

(not 100% sure this is a bug)

**Comment by osma** [comment]
Thanks for noticing! Looks like a bug to me. Probably happens because top concepts are queried with a separate REST method (topConcepts) than the other parts of the hierarchy.
