### ISSUE TITLE
"Concept count by type" does not give the number of concept groups

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#335]
On http://skosmos.dev.finto.fi/unesco/en/
The thesaurus contains skos:Collection (= Groups).
The "Concept counts by type" section gives only the number of concepts (4408); I expected to see also the number of concept groups here (?)

On another but related subject, on a concept group page like http://skosmos.dev.finto.fi/unesco/en/groups/?uri=http%3A%2F%2Fskos.um.es%2Funescothes%2FCOL003, using the terminology "Concept Type" is a bit odd, since this is not a concept. Using a more geenric term like "Entry type" could be more appropriate (?)

**Comment by osma** [comment]
You're right, it would be logical to show also the number of collections/groups in the same place.

> Using a more geenric term like "Entry type" could be more appropriate (?)
Right, maybe just "type" would be enough. Making this a separate issue.

**Comment by henriyli** [comment]
643fafd isn't related to this in any way.
