### ISSUE TITLE
"X results" translation should use variable substitution

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#338]
The translation for "X results" is done so that only "results" is translated:
https://github.com/NatLibFi/Skosmos/blob/master/view/concept-shared.twig#L4

Instead the message to translate should be "%d results". This would make it easier for translators and perhaps allow more natural expressions in some languages.

Similar to #337.

**Comment by henriyli** [comment]
The actual message was in search-result.twig. I removed the redundant one from concept-shared.twig and fixed the issue in search-result.twig.
