### ISSUE TITLE
Add Norwegian Nynorsk translation

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#340]
Add Nynorsk translation from Transifex that was contributed by @danmichaelo

**Comment by osma** [comment]
Added in 406139e9470acad678c2de9efc32d942368e6464

**Comment by danmichaelo** [comment]
:+1:

**Comment by danmichaelo** [comment]
Can you pull in the updated Bokmål translation as well? I did quite some changes to it.

**Comment by osma** [comment]
@danmichaelo See #342
