### ISSUE TITLE
Update Norwegian Bokmål translation

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#342]
Comment on #340 by @danmichaelo :
> Can you pull in the updated Bokmål translation as well? I did quite some changes to it.

1.3 was just tagged and released but yes, we can put this in master + v1.3-maintenance branch

**Comment by osma** [comment]
(sidenote: we really need to implement #339, managing translations is getting messy)

**Comment by danmichaelo** [comment]
> (sidenote: we really need to implement #339, managing translations is getting messy)

Thanks, seems like a good idea ;)
