### ISSUE TITLE
ConceptGroup page shows empty Hierarchy tab

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#348]
## At which URL did you encounter the problem?
http://dev.finto.fi/metatietosanasto/fi/page/kappaleen_suhteet

## What steps will reproduce the problem?
1. Go to Metatietosanasto
2. Search for "kappaleen suhteet"
3. Open the concept page from the dropdown

## What is the expected output? What do you see instead?

The left sidebar opens the Hierarchy tab, which is empty and just shows a "Loading..." message.

Since this is a ConceptGroup instance, I think it would be better to open the Groups tab.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by henriyli** [comment]
This seems to be broken again.
