### ISSUE TITLE
Support reverse proxy and alternative paths

### ISSUE THREAD

**Issue by jneubert** [NatLibFi/Skosmos#352]
I've installed skosmos dev on Centos 5.11 (good news: your installation description works for Centos5 too. I'm not sure however if the program will work cleanly due to the fairly old PHP 5.3.3).

What I wanted to accomplish is to address the installation with a clean URI such as http://zbw.eu/beta/skosmos. This involves
1. a reverse proxy from our central domain to some obscure IP (which is in place and working) - 1.2.3.4 in the example below.
2. having the installation directory linked from /var/www/html/beta (instead of /var/www/html).

Currently, a basic skosmos page is displayed. However, the CSS files are not found, neither any other resource or vendor lib.

A link to the search button results in a 404 for http://1.2.3.4/opt/skosmos/en/search?clang=en&q=&vocabs=

**Comment by osma** [comment]
Hi Joachim!

Skosmos tries to guess the base URL, but in a reverse proxy setup it will be wrong. You will need to force the base URL with a setting like this in config.inc:

```
define("BASE_HREF", "http://zbw.eu/beta/skosmos/");
```

This should be documented, it's currently mentioned in the `config.inc.dist` but it's not easily findable from there.

If you still have problems, maybe bring them up on the skosmos-users mailing list?

**Comment by jneubert** [comment]
Perfect - thanks!

**Comment by osma** [comment]
I've now documented this on the [ReverseProxy](https://github.com/NatLibFi/Skosmos/wiki/ReverseProxy) page and added a link from the Configuration page.
