### ISSUE TITLE
Language selection seems to break BASE_HREF

### ISSUE THREAD

**Issue by jneubert** [NatLibFi/Skosmos#355]
When selecting another interface language (in the upper right corner), the URL changes. Instead of the reverse proxy path (as described in #352) the IP address behind the proxy becomes part of the URL, with consecutive CORS issues while accessing css and font resources.

**Comment by osma** [comment]
Yes, the code for creating the links (in view/topbar.twig) seems to rely on request.requesturi so it is affected by the server environment.
