### ISSUE TITLE
PHP Error when searching

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#357]
Using SKOSMOS v1.3-maintenance
On http://193.49.36.141/skosmos/demovoc/en/, search for "age" in the search box, and click on "search". You get a blank page due to a PHP error.

PHP error is : 

[Wed Nov 18 13:45:26.932648 2015] [:error] [pid 19665] [client ] PHP Notice:  Undefined property: stdClass::$group in /var/www/html/skosmos/model/sparql/GenericSparql.php on line 1232, referer: http://193.49.36.141/skosmos/demovoc/en/
[Wed Nov 18 13:45:26.932727 2015] [:error] [pid 19665] [client] PHP Fatal error:  Call to a member function getURI() on a non-object in /var/www/html/skosmos/model/sparql/GenericSparql.php on line 1232, referer: http://193.49.36.141/skosmos/demovoc/en/

The RDF data used is downloadable at http://193.49.36.141/skosmos/rest/v1/demovoc/data?format=application/rdf%2Bxml

Something related to skos:Collection I guess. The "Group Index" tab also does not load properly, maybe for the same reason. Did I do something wrong in the SKOS data or is it a special case that SKOSMOS does not handle properly ?

Thanks for your precious help

**Comment by osma** [comment]
Is the site http://193.49.36.141/skosmos/demovoc/en/ supposed to be available? I can't access it.

The error message is a bit strange. At least on current v1.3-maintenance, line 1232 in GenericSparql.php is:
```php
      $group = array('uri' => $row->group->getURI());
```

This obviously would fail if `$row->group` is null, but the SPARQL query has the clause

```
   ?group a <$groupClass> .
```

which should ensure that `?group` is bound and thus non-null.

Do your groups/collections have URIs or are they blank nodes? Are you using up to date v1.3-maintenance code? What is the value of `skosmos:groupClass` in your vocabularies.ttl?

**Comment by tfrancart** [comment]
Ha sorry, there was some kind of IP restriction on the site currently. Unfortunately I can't remove that.

Your answer led me to the solution : my vocabularies.ttl file contained a wonrg skosmos:groupClass parameter (copied from the YSO configuration). I changed it to skos:Collection and now everything is fine.

Thanks very much

**Comment by osma** [comment]
Good that you got it working! I'm still a bit stumped, I don't see how it's possible that you got that error, but since the configuration was wrong anyway I don't think we can consider this a bug.

**Comment by osma** [comment]
I managed to accidentally trigger this myself. It can happen when there are no instances of the specified group class. Then the query returns a single row with ?group not bound, and the PHP code breaks.
