### ISSUE TITLE
Add a dropdown with modification type in the feedback form

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#362]
Hello

It would be nice to have an extra dropdown in the feedback form so that the messages can be associated to a feedback category. Possible categories can be :
- Request for a new concept
- Request for a concept modification (labels, notes, definition)
- Request for a relation modification/creation (broader, narrower, related)
- Request for a concept alignment (exact match, close match)
- Request for a concept deletion/deprecation
- Request for a group modification
- Other feedback

(to be refined)

This could help thesaurus managers breaking down the requests into categories and have a more structured vocabulary management workflow.

**Comment by osma** [comment]
Thanks for the suggestion!

Should the categories be configurable, or just a fixed list?

I think vocabularies may follow different models. These are the two extremes that I could think of, but there may be others:

* main/original publishing location for vocabularies, e.g. YSO in Finto or AGROVOC on the FAO site. There these categories make sense, unless there is another channel for suggestions.
* re-publishing a vocabulary that is already published elsewhere, e.g. Iconclass and Lexvo in Finto. It doesn't make sense to collect requests for modification, because all the maintenance work happens elsewhere

**Comment by tfrancart** [comment]
Good point.
Then maybe an option could be added in the config file to show or hide this
extra combo-box in the feedback form ?
In my idea the catefories needed not to be configurable.

Another idea in the same line could be to enable users to send a feedback
from the concept page directly ("Give feedback *about this concept*"). The
concept on which feedback is given would then be included in the message
sent. Instead of feedback categories, this would be another way for
thesaurus administrators to divide their maintenance work.


2015-11-30 12:48 GMT+01:00 Osma Suominen <notifications@github.com>:

> Thanks for the suggestion!
>
> Should the categories be configurable, or just a fixed list?
>
> I think vocabularies may follow different models. These are the two
> extremes that I could think of, but there may be others:
>
>    - main/original publishing location for vocabularies, e.g. YSO in
>    Finto or AGROVOC on the FAO site. There these categories make sense, unless
>    there is another channel for suggestions.
>    - re-publishing a vocabulary that is already published elsewhere, e.g.
>    Iconclass and Lexvo in Finto. It doesn't make sense to collect requests for
>    modification, because all the maintenance work happens elsewhere
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NatLibFi/Skosmos/issues/362#issuecomment-160608410>.
>



-- 

*Thomas Francart* -* SPARNA*
Web de *données* | Architecture de l'*information* | Accès aux
*connaissances*
blog : blog.sparna.fr, site : sparna.fr, linkedin :
fr.linkedin.com/in/thomasfrancart
tel :  +33 (0)6.71.11.25.97, skype : francartthomas

**Comment by osma** [comment]
Some further specification:
1. The feedback form should remember the concept where the user was
2. The categories should be configurable in vocabularies.ttl
3. It should be possible to turn this on/off per vocabulary

**Comment by osma** [comment]
Contributions welcome!

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
