### ISSUE TITLE
Tutorial documentation

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#364]
Our current installation instructions are not very detailed. It would be good to have a tutorial document with a specific goal, e.g. installing Skosmos (and Fuseki etc.) starting from a plain Ubuntu 14.04 Server machine and loading and configuring a couple of example vocabularies (e.g. UNESCO and STW).

**Comment by osma** [comment]
This is not really tied to Skosmos development versions but I'll set this to be done in the 1.5 cycle, but addressing the 1.4 release (or whatever is the most recent released version at the time).

**Comment by kinow** [comment]
+1 :grin:

**Comment by osma** [comment]
I started writing a tutorial in the wiki: https://github.com/NatLibFi/Skosmos/wiki/InstallTutorial

**Comment by osma** [comment]
We'll finish this after 1.5 is released as it is not a code issue.

**Comment by osma** [comment]
I did some significant work on the [tutorial](https://github.com/NatLibFi/Skosmos/wiki/InstallTutorial), i.e. the section about installing Fuseki 2 which was surprisingly difficult, but overall it's not completely ready yet.

**Comment by osma** [comment]
Also the document is already getting quite long, it should probably be split up. The part about configuring Fuseki overlaps with the older page [InstallFusekiJenaText](https://github.com/NatLibFi/Skosmos/wiki/InstallFusekiJenaText) which, however, is oriented more towards Fuseki 1. I think some restructuring of the wiki is needed here and maybe also a custom table of contents sidebar, since the GitHub wiki namespace (and automatic ToC) is flat and we're already stretching the limits of a flat namespace/ToC.

**Comment by osma** [comment]
[Tutorial document](https://github.com/NatLibFi/Skosmos/wiki/InstallTutorial) is finished. It could still be split up to multiple pages though.

**Comment by osma** [comment]
Asked for feedback on skosmos-users and the Jena users list.

I think this is good enough for now, so closing the issue.
