### ISSUE TITLE
Display the concept hierarchy under the group hierarchy

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#366]
Some thesaurus like UNESCO or EUROVOC are grouping their concepts under domains and micro-thesaurus headers. In that case we have the garantee that, when a top-level concept belongs to a certain group, all the children concepts below it also belong to the same group.

In that case, in the "Groups" pane, it could make more sense to display the concepts in each group as foldable/unfoldable nodes in the tree (just like the hierarchy pane), rather than giving the flat list of all the concepts in the group.
Or this could be done in the "Hierarchy" pane, also. The point is that for these kind of thesauri, there is currently no way in SKOSMOS to view their full hierarchy, starting with the domains and micro-thesaurus levels, and then going down in the concept hierarchy below it.

Expected behavior : at http://skosmos.dev.finto.fi/unesco/en/groups, when unfolding 1. Education, then 1.05 Educational Sciences and Environment, the first concept in the list "Academic Fraud" should not be displayed but rather placed under its broader concept "Educational Environment". 

Either an extra option on the vocabulary can trigger this behavior in SKOSMOS, or a smart SPARQL query can also determine if a vocabulary follows this pattern.

Please let me know if this is unclear.

**Comment by osma** [comment]
Thanks for the suggestion. Indeed this seems sensible at least for UNESCO Thesaurus and EuroVoc. Maybe also STW Thesaurus, which has its own type (Thsys) for these top level concepts but if it switched to another modelling based on ConceptGroups then this would make sense (am I right, @jneubert?).

The way to implement this is two-folded:
1. On the server side, change the SPARQL query for group members to also return the skos:broader information (perhaps based on a configuration option like you suggested)
2. On the client side, in JavaScript code, use the hierarchy information to group the member concepts of a group in a hierarchy.

Step 1 is rather simple, but step 2 may be more difficult. The JS code for creating the hierarchy and groups displays is already quite complicated.

However, I don't think we have a need for this at Finto for any of the vocabularies we currently host. Contributions welcome!

**Comment by jneubert** [comment]
Thanks for pinging me. STW deliberately didn't use skos:Collections for its upper level hierarchy of subject categories. Different from Eurovoc and Unesco with their rather flat two-top-level collection hierarchies, the about 500 STW Thsys concepts build an up to four levels deep hierarchy. In my eyes, it makes sense to treat this hierarchy as an knowledge organization system of its own, not as deeply nested collections. 

Downside is that the skos:broader/narrower relations within one of these knowledge organisation systems (of subtypes [zbwext:Thsys](http://zbw.eu/namespaces/zbw-extensions/Thsys) and [zbwext:Descriptor](http://zbw.eu/namespaces/zbw-extensions/Descriptor)) are currently indistinguishable from the ones between these two. Two concept hierarchies linked by skos:member are forbidden by the disjunctness of skos:Collection (which is the implied domain of skos:member) and skos:Concept. Sadly, I cannot see how isothes: could help here. So my current strategy is to wait what comes up (re. further advantages/disadvantages/proposed solutions). Anyway, to my knowledge STW is the only SKOS thesaurus using such an approach, so it wouldn't make sense trying to incorporate it into Skosmos.

Another thing to consider is that the guarantee imposed in the suggestion - _"when a top-level concept belongs to a certain group, all the children concepts below it also belong to the same group"_ - does not hold in case of the STW (and here I suppose, others too). E.g., the concept [Speculation](http://zbw.eu/stw/descriptor/10021-0) is subordinated to [B.02.02 Corporate financial assets](http://zbw.eu/stw/70036) and [V.05.04 Financial markets](http://zbw.eu/stw/thsys/70187), whereas its narrower concept [Real estate speculation](http://zbw.eu/stw/descriptor/12023-0) is subordinated to [V.11.03 Land economics](http://zbw.eu/stw/thsys/71066) and [W.17 Real estate industry](http://zbw.eu/stw/thsys/70889).

**Comment by osma** [comment]
It's possible that GACS will also adopt this kind of structure.

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
