### ISSUE TITLE
Refactor the config.inc configuration constants access into a class

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#374]
The config.inc has grown with many new configuration options. It would be a good idea to introduce a class for accessing these configuration options. This "GlobalConfig" should provide getters for the options set in config.inc. We probably would like the configuration to be in some other format in the future, but for now we'll settle for introducing the new class.

**Comment by osma** [comment]
All Travis tests now fail with messages like "EError: config.inc file is missing, please provide one." See https://travis-ci.org/NatLibFi/Skosmos/jobs/95328236

**Comment by osma** [comment]
Switching milestone to 1.4 since implementing this has already started on master
