### ISSUE TITLE
Show labels without a language tag

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#375]
## At which URL did you encounter the problem?

No URL currently; we don't have data like this since it wouldn't work anyway. In Finnish Corporate Names, the prefLabels have languages tagged "fi" because of this.
## What steps will reproduce the problem?
1. Look at a concept whose prefLabel has no language tag
## What is the expected output? What do you see instead?

Expected to see the non-language-tagged labels. There are situations where it would be appropriate to give priority to a label without language tag as a secondary choice when there is no label in the current language. For example with authority files (e.g. GND and the Finnish corporate names dataset) this is a common scenario.

Where labels are displayed, the priority should be
1. Show label with the correct language tag, if found
2. Show label without language tag, if found
3. Show label in any language

**Comment by jneubert** [comment]
Another possible use case for this are GND subject headings: Their preferred and alternate labels have no language tags. For displaying them in skosmos, I've added 'de', but this may be actually wrong in some cases.

Same if anybody would add personal names to the mix.

**Comment by osma** [comment]
GACS has for now decided to use the special language tag `zxx` for scientific names, so this is not directly relevant to GACS anymore.

In any case, there are situations where it would be appropriate to give priority to a label without language tag as a secondary choice when there is no label in the current language. For example with authority files (e.g. GND and the Finnish corporate names dataset) this is a common scenario.

**Comment by osma** [comment]
Futher specification:
Where labels are displayed, the priority should be
1. Show label with the correct language tag, if found
2. Show label without language tag, if found
3. Show label in any language

**Comment by osma** [comment]
The GACS example is no longer relevant as stated above. We should find other examples in current vocabularies (e.g. CN, Kassu) that demonstrate this problem.

**Comment by osma** [comment]
To address this, we'd need a test dataset with no language tag (e.g. a version of CN with no language tags).

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
