### ISSUE TITLE
Feedback form not sent

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#378]
(unfortunately URLs cited below are not public)

## Problem 1 ##

The base HREF of the fedback form is defined as

```<base href="http://thesaurus.web.ined.fr/browser/">```

The feedback form is invoked from ```http://thesaurus.web.ined.fr/browser/[thesaurus]/[language]/feedback```

The feedback form submits to "#" :

```<form id="feedback-fields" method="post" action="#">```

, which submits to ```http://thesaurus.web.ined.fr/browser/#``` due to the base HREF declaration. This is not catched by the index.php script, and submitting the form simply redirects to the home page of SKOSMOS, and does not send the feedback e-mail as expected.

## Problem 2 ##

Case 1 : When users click on "Feedback" from the homepage (without selecting a vocabulary first), the feedback form is invoked from ```http://thesaurus.web.ined.fr/browser/[language]/feedback``` (without the [thesaurus] URL component)
Case 2 : When users first chooses a vocabulary, then clicks on feedback, the feedback form is invoked from ```http://thesaurus.web.ined.fr/browser/[thesaurus]/[language]/feedback```

In Case 1 above, the index.php considers there is only 2 parts in the URL and does not correctly invoker the "invokeFeedbackForm" method.

**Comment by osma** [comment]
Thank you for reporting! This is indeed a serious problem and affects also our sites finto.fi and dev.finto.fi. The feedback form simply takes to the home page.

**Comment by henriyli** [comment]
I think the above commit fixed problem 1.

**Comment by osma** [comment]
@tfrancart Still having problems? It's not clear if Problem 2 is actually a separate problem, or just another perspective at the same one.

If all cases work now, this issue could be closed.

**Comment by tfrancart** [comment]
Just tested and it works fine. Problem 2 was actually not a problem (but I couldn't really tell before Problem 1 was fixed).

Thanks very much - again - for your reactivity and the quick fix.
