### ISSUE TITLE
Feedback message includes referer instead of IP address

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#380]
Here is a feedback message received :

...

Debugging information:
Timestamp: Tue, 08 Dec 2015 11:58:14 +0100
User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:42.0) Gecko/20100101 Firefox/42.0
IP address: http://thesaurus.web.ined.fr/navigateur/demovoc/fr/feedback
Referer: http://thesaurus.web.ined.fr/navigateur/demovoc/fr/feedback

As you can see the IP address contains the referer instead.

**Comment by osma** [comment]
Whoops, thanks for reporting!
