### ISSUE TITLE
Suggestion: Obtain prefixes for turtle output from vocabularies.ttl

### ISSUE THREAD

**Issue by jneubert** [NatLibFi/Skosmos#387]
Currently, in a turtle export, prefixes like `ns0:` occur.

Perhaps the user could express her preferred prefixes by adding them to vocabularies.ttl

**Comment by osma** [comment]
We already do this for vocabulary id's, see https://github.com/NatLibFi/Skosmos/blob/master/model/Model.php#L401

I'm not sure how to access the namespace prefixes defined in a particular Turtle file using EasyRdf. If you can investigate and make a PR, it will be very welcome ;)

**Comment by osma** [comment]
The EasyRdf Turtle parser stores namespaces in a protected field and doesn't expose them, so it's rather difficult to access them from outside the parser. At the minimum one would have to subclass TurtleParser (luckily it's a protected field, not a private one) and add a getNamespaces method to the subclass.

**Comment by GO5IT** [comment]
Hello,

I'm just a SKOSMOS user, but I have a question related to this closed issue. When I import SKOS which have proprietary namespaces (ie not included in SKOSMOS data model), it seems all are stored under `xmlns:ns0`. It is OK that they cannot be displayed on the web interface, but just wondering if there is a way to avoid this and see the original namespaces in the downloadable formats like RDF/XML, Turtle and JSON-LD (e.g. `xmlns:example="http://www.example.com"`)? At least I could not find information about this in the documentation. If this is not possible, it wold be a feature request (displaying them as well, if feasible). Thank you!

**Comment by osma** [comment]
@GO5IT I believe that what you describe should already happen. This issue was exactly about that feature, and it was implemented in January 2016, as can be seen above. Of course it's possible that there are some bugs in the implementation - in that case, please open a new issue or report your problems in the [skosmos-users](https://groups.google.com/forum/#!forum/skosmos-users) group.
