### ISSUE TITLE
Alphabetical list loading forever with large vocab

### ISSUE THREAD

**Issue by jneubert** [NatLibFi/Skosmos#389]
With the latest version (https://github.com/NatLibFi/Skosmos/commit/d300eec99cf3e57eab3b7ea6ffe1a1de028373e7), loading the alphabetical list of term takes forever with a large vocabulary (> 130,000 concepts).

With https://github.com/NatLibFi/Skosmos/commit/b3fa4307f2e1fbcc44c64cae725897fa6ae68794, it takes some seconds.

**Comment by osma** [comment]
I assume you are using Fuseki? Which version?
For Skosmos 1.4 we are targeting Jena 3.0.1 (Fuseki 1.3.1/2.3.1) which was just released. Also you need to use the new text index configuration, see [Upgrading](https://github.com/NatLibFi/Skosmos/wiki/Upgrading) and [InstallFusekiJenaText](https://github.com/NatLibFi/Skosmos/wiki/InstallFusekiJenaText)

**Comment by jneubert** [comment]
It's Fuseki - version 1.1.1 (Build date: 2014-10-02T16:36:17+0100)

I'll try to upgrade my beta endpoints asap.

**Comment by osma** [comment]
I assume that this is due to the version mismatch. Please reopen if the problem persists after the Fuseki upgrade.
