### ISSUE TITLE
Restrict search by ConceptScheme

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#391]
We have some support for multiple skos:ConceptSchemes in a single vocabulary, but there is no way to restrict search to a particular concept scheme.

We should add
* a `scheme` parameter to the REST `search` method (similar to `type`)
* a matching UI element to the search result page

**Comment by osma** [comment]
We'll leave this for 1.5.

**Comment by osma** [comment]
I think a lot of work for this actually went into the 1.4 release by accident, but the commits were not tagged with this issue number. Can you check @henriyli ?

**Comment by henriyli** [comment]
The 2947b94 commit slipped the limitations into the ui by accident.
