### ISSUE TITLE
dcterms:subject metadata from vocabulry.ttl file mixes with own thesaurus metadata

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#394]
Hello

SKOSMOS requires that a category is assigned to vocabularies in vocabulary.ttl config file, using a dcterms:subject metadata (otherwise they are not shown). I tend to use category "General" since I don't really need to assign a category to the thesaurus.

This value is shown in the thesaurus page and mixes with the own thesaurus dcterms:subject metadata :

![screenshot-skosmos-dcterms-subject](https://cloud.githubusercontent.com/assets/2728945/11838754/473bd6f0-a3e9-11e5-8549-72d95eecb20d.png)

I don't think the dcterms:subject metadata from vocabularies.ttl should mix with my own metadata. Putting vocabularies in categories only for SKOSMOS display purposes and assigning keywords to my vocabularies in my own data are 2 different things.

Besides, it would be cool if it wasn't mandatory to assign categories to vocabularies in the config file.

Cheers !

**Comment by osma** [comment]
I agree, mixing the category metadata with the vocabulary data is not very good.

There are basically two things here, either or both of which could solve your problem:
1. Remove the category metadata from the vocabulary page
2. Make the categorization in vocabularies.ttl optional so that you don't need to assign a General category

**Comment by tfrancart** [comment]
I take solution 1 as a quick fix if it is easy, but in the long term solution 2 is better I guess.
Thanks

**Comment by osma** [comment]
I'll make the quick fix for version 1.4. I opened a separate issue #406 for making categorization optional.
