### ISSUE TITLE
"Belongs to group" hierarchy is mixed up when groups are polyhierarchical

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#408]
Hello

Using 1.3-maintenance I see the "belongs to group" hierarchy is mixed up when the concept belongs to more that one group. In UNESCO thesaurus, countries concepts under the domain "7 Countries and Country Grouping" are actually members of more than one group (note that this is something you don't have in the UNESCO thesaurus version loaded in the demo site of SKOSMOS, because that thesaurus data is outdated).

Here is what I get for concept "Belgium"

![screenshot-belongs-to-group](https://cloud.githubusercontent.com/assets/2728945/11893339/2d62b7ca-a570-11e5-8fd8-e03dd3fff92b.png)

display is mixed up, and I see the group notation is not displayed either (should it ?)
The expected display would be :

```
7. Countries and country groupings > 7.20 Europe
7. Countries and country groupings > 7.25 Political Groupings
7. Countries and country groupings > 7.30 Economic Groupings
7. Countries and country groupings > 7.45 Linguistic Groupings
```
I can provide the data and config file in a separate private thread if needed.

**Comment by tfrancart** [comment]
Hmmm, thinking twice this might be a problem in my dataset. Probably "Belgium" should not belong to all of these groups. I need to double check.

**Comment by tfrancart** [comment]
There might indeed be a problem in Skosmos when a concept belongs to more than one group, but my data is wrong indeed : "Belgium" should not belong to all of these group, only to "Europe", just like in the version of the thesaurus loaded in the skosmos demo website.

Thanks :-)

**Comment by osma** [comment]
Okay, closing this one for now, please get back if you find a more specific problem.
