### ISSUE TITLE
Advanced search form

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#411]
The current way of searching forces the user to first enter a keyword, and only then allows restricting the results by type, group, parent etc.

This doesn't allow special searches such as "show me all concepts in a certain group having a certain type". Other similar use cases have been mentioned by @mirmaid.

We could design an alternate "advanced search" interface which doesn't force the user to start with a keyword. It would be possible to start with, and combine, any of the existing search options.

**Comment by henriyli** [comment]
Needs to be split into smaller and more specific tasks.

**Comment by kouralex** [comment]
This issue requires tackling or at least a giving a thought for issues #376, #611 #546, #545, #527, #457 #617, #124, #89, #143, #222 and #537 even if not fixing them before this.

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
