### ISSUE TITLE
New front page design

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#412]
The current Skosmos/Finto front page has some problems, including:
- too much space between the top header and the content
- content is off-center
- the search box is quite small
- Twitter feed (on Finto.fi) is too cramped
- the Finto logo gets in the way on a narrow screen

We could design a better front page addressing those problems (and hopefully not creating new ones). The design should be responsive and take into account different usage scenarios such as publishing just one or two vocabularies vs. having many of them.

**Comment by mirmaid** [comment]
New front page design is being developed, comments will be considered.
