### ISSUE TITLE
Increase unit test coverage

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#415]
Unit test coverage has fallen to 76% in Skosmos 1.4.

We should aim for more.

Looking at the coverage report I see that some private/protected methods, such as GenericSparql->generateConceptSearchQueryInner, are marked as not covered although they must have been visited by the unit test for some public method. I think PHPUnit has an option that tells it to cover protected methods as well even though the `@covers` annotation is only for a the public method, we should try that.

Of course there are also really missing unit tests, for example concept searches are not well covered in general and apparently JenaTextSparql is not tested at all, even though the GenericSparql tests could be used to test it as well using a slightly different testconfig.inc.

**Comment by henriyli** [comment]
Coverage is now over 90%.

**Comment by kinow** [comment]
:thumbsup:  :clap:
