### ISSUE TITLE
"The vocabulary does not contain terms beginning with" should use variable substitution

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#417]
It should have a placeholder such as `%letter`.

**Comment by osma** [comment]
It could be changed to the simpler "There are no terms beginning with %letter"

**Comment by osma** [comment]
Or even shorter "No terms beginning with %letter found"

**Comment by henriyli** [comment]
This translation was used for the alphabetical index when the menu could include letters that didn't have any concepts in the vocabulary. That doesn't happen anymore since the first letters are queried from the endpoint.
