### ISSUE TITLE
Filtering a search by type does not work

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#418]
1. Go to http://skosmos.dev.finto.fi/unesco/en
1. Search for "cultural policy" and click on search. There are 2 results : one concept "Cultural policy" and one concept group "3.10 cultural policy and planning"
1. In the search options on the left, filter the search by type by selecting "Concept", and click on "limit search"

The same 2 results are returned.
Expected : only "cultural policy" should be returned, the concept group "3.10 cultural policy and planning" should be filtered out from the search.

Thanks !

**Comment by osma** [comment]
Thanks for reporting!

**Comment by henriyli** [comment]
The two previous commits fix the master branch, but the v1.4-maintenance still needs to be separately fixed.
