### ISSUE TITLE
Provide translations for all dcterms metadata on thesaurus page

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#431]
Hello

Some dcterms metadata labels are not translated on the thesaurus page, while some others are. Here is the list of the metadata to be translated (at least) :

- DC:CONFORMSTO
- DC:FORMAT
- DC:IDENTIFIER
- DC:ISREQUIREDBY
- DC:RIGHTSHOLDER
- DC:TYPE

This makes strange display mixing labels with technical URIs :

![screenshot-dcterms](https://cloud.githubusercontent.com/assets/2728945/12265189/0d720fa8-b93c-11e5-8981-c8964ffddb92.png)

Thanks !

**Comment by osma** [comment]
Thanks for the suggestions. Indeed we don't currently have translations for all the DC Terms properties as there are quite many of them and only some of them are frequently used in thesauri.

This is really simple, they just need to be added to view/extra-msgids.twig and then translated through the normal mechanism (regenerate po files with poedit etc)

**Comment by tfrancart** [comment]
The complete dcterms properties are listed at http://dublincore.org/documents/dcmi-terms/

**Comment by osma** [comment]
These should now all be translatable strings. English/Finnish/Swedish translations are done (except a couple of Swedish translations still need to be checked), remaining languages can be translated on Transifex.
