### ISSUE TITLE
Enforce alphabetical ordering of multiple values in the same property

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#443]
When a property have multiple values, then come with no specific order (it seems). Here in the metadata page of the concept scheme :

![screenshot-skosmos-ordering-values](https://cloud.githubusercontent.com/assets/2728945/12883654/832eb61a-ce59-11e5-8e3b-5293c6d644ec.png)

It would be nice to garantee at least an alphabetical ordering of the values in that case. This would apply also in concept pages.

Thanks !

**Comment by osma** [comment]
I think this only affects the concept scheme metadata. Concept page property values are already in alphabetical order.
