### ISSUE TITLE
Provide translations for all DC 1.1 metadata in the concept scheme page

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#444]
Concept scheme page correctly translates some DC 1.1 metadata (dc11:creator for example), but not all. At least dc11:subject is not translated.
Similarly to https://github.com/NatLibFi/Skosmos/issues/431, it would be nice to check that all simple DC metadata have a corresponding translation.

**Comment by osma** [comment]
Right. Some DC 1.1 properties are still missing from extra-msgids.twig so they don't get translated.

**Comment by osma** [comment]
I think it would make sense to try to use the same translations for DC 1.1 and DC Terms properties of the same name. Otherwise we will end up having to maintain two translations for variants of the same DC property, e.g. dc:language / dc11:language

**Comment by osma** [comment]
All the DC 1.1 properties are now included as translatable strings. Closing this issue.

**Comment by tfrancart** [comment]
Keeping DC 1.1 and DC Terms as separate strings would allow to have different property names to distinguish the 2 (e.g. "subject (DC Terms)" and "subject (DC)")

**Comment by osma** [comment]
@tfrancart You're right, but does it matter to users? We don't currently make the distinction between DC 1.1 and DCTerms in the UI labels.

In the past translators have wondered why they need to translate some DC labels twice, e.g. "Title".

**Comment by tfrancart** [comment]
I have a use case where both dcterms:subject and dc:subject are used to
describe the vocabulary, the former with URIs, the latter with keyword
strings. I may need to distinguish the label of the 2 properties.
This is a minor remark and I could live with the same label for both.

Cheers
Thomas

2016-02-09 8:21 GMT+01:00 Osma Suominen <notifications@github.com>:

> @tfrancart <https://github.com/tfrancart> You're right, but does it
> matter to users? We don't currently make the distinction between DC 1.1 and
> DCTerms in the UI labels.
>
> In the past translators have wondered why they need to translate some DC
> labels twice, e.g. "Title".
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/NatLibFi/Skosmos/issues/444#issuecomment-181742565>.
>



-- 

*Thomas Francart* -* SPARNA*
Web de *données* | Architecture de l'*information* | Accès aux
*connaissances*
blog : blog.sparna.fr, site : sparna.fr, linkedin :
fr.linkedin.com/in/thomasfrancart
tel :  +33 (0)6.71.11.25.97, skype : francartthomas

**Comment by osma** [comment]
I understand. URIs should show up as clickable links while literals are just plain strings, so at least they are displayed differently.

If you have specific requirements related to this, and can suggest a practical solution, please open a new issue. I think generally it is good to avoid putting extra burden on translators due to the DC/DCT split. Also I think that the translations should, when possible, reflect official translations of the DC properties. I think the original English labels of the DC 1.1 elements are the same as those of the corresponding DC Terms properties.
