### ISSUE TITLE
DC 1.1 properties not translated in concept scheme metadata

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#449]
## At which URL did you encounter the problem?
http://dev.finto.fi/yso/fi/

## What steps will reproduce the problem?
1. Go to home page of any vocabulary that has DC 1.1 metadata

## What is the expected output? What do you see instead?

Seeing "DC11:DESCRIPTION", "DC11:PUBLISHER" etc. untranslated property names.

Probably got broken as part of #444

**Comment by henriyli** [comment]
fixed this in 38a5009 , but tagged the wrong issue in the commit message...
