### ISSUE TITLE
Make display of skos:notation values optional

### ISSUE THREAD

**Issue by jneubert** [NatLibFi/Skosmos#452]
Publishers of classification-like vocabularies may have included the skos:notation of a class into the skos:prefLabel to make the latter unique. For such a case, it would be great if the additional display of skos:notation in 

- hierarchical list,
- groups list, 
- single concept display
- (are there other relevant places?)

could be made optional (see also [discussion on skosmos-users](https://groups.google.com/forum/#!search/skosmos$20notation/skosmos-users/B_VtLoNOgQU/Xec19SNuAQAJ)) via an additional vocabulary configuration parameter.

It would be nice if the skos:notation could be still displayed as a seperate field in the single concept display, but I suppose this is not strictly necessary, because a turtle (etc.) dump would include it anyway. 

I'm not sure re. the REST API for the concept and group hierarchies, I can only _suppose_ that for the display of [STW](http://zbw.eu/beta/skosmos/stw/en/) and [JEL](http://zbw.eu/beta/skosmos/jel/en/) it wouldn't make a difference if it's handled on the API or Javascript level.

**Comment by osma** [comment]
Could be a vocabulary-specific option `skosmos:showNotation` which would default to true
