### ISSUE TITLE
Concept display not dividing narrower concepts by thesarus arrays

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#453]
## At which URL did you encounter the problem?
http://finto.fi/tsr/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fyso%2Fp3594

## What steps will reproduce the problem?
1. Look at "vaatteet" in TSR ontology (or MAO/TAO)

## What is the expected output? What do you see instead?

Expect that the narrower concepts would be divided by thesaurus array, as they are in YSO. The ThesaurusArray instances are in the data but for some reason are not used to subdivide narrower concepts.

**Comment by henriyli** [comment]
The vocabulary configuration is missing the line that enables this. "skosmos:arrayClass isothes:ThesaurusArray ;"
