### ISSUE TITLE
Search by notation code

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#456]
Entering a notation code in the search box should give the concept with that notation.
E.g. in UDCS summary entering "=18" in the search box should find Albania.

**Comment by osma** [comment]
I think we could use exact literal matching without a text index in the SPARQL query to implement this. This means that notation code lookups will be case sensitive.

**Comment by osma** [comment]
Doesn't work, searching for =18 in UDCS gives no result

**Comment by osma** [comment]
Also the unit test has a redundant line, there is no method getRawSearchTerm

**Comment by henriyli** [comment]
UDC Summary uses data types in the notations e.g. skos:notation "=..."^^udcs:UDCnotation ; which makes this hard to do efficiently since you'd need a filter for that. Leaving this for a later date.

**Comment by osma** [comment]
Simple case (no datatype) has been implemented, so I'm closing this and opening another issue for the notation with datatype case.
