### ISSUE TITLE
Add support for definition eg. as optional fields parameter in vocabulary specific search api

### ISSUE THREAD

**Issue by amiika** [NatLibFi/Skosmos#459]
Add skos:definition as supported fields parameter to /<vocid>/search API.

Currently any extra information (comment, definition eg.) needs to be queried with /data API, which means 1 /data call for each search result if you want to show the extra information along with the search results. Add support to comment & definition eg. or alternatively fields parameter could be extended to support any predicate that is encoded to field parameter as full uri.

**Comment by osma** [comment]
Implementing this as `fields=definition` makes sense to me.

**Comment by osma** [comment]
This was actually already implemented as part of #432 but the implementation seems to be buggy, it returns definition values as if they were URIs. Reported as #505
