### ISSUE TITLE
Broken dates no longer parsed at all

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#468]
## At which URL did you encounter the problem?
http://dev.finto.fi/juho/fi/page/p6380

## What steps will reproduce the problem?
1. Open url

## What is the expected output? What do you see instead?
Expected to see the incorrect date still parsed somehow or atleast displayed as is. Now only seeing the created/modified strings.

**Comment by osma** [comment]
The data is really broken, the properties dc11:created and dc11:modified do not exist. See http://dublincore.org/documents/dces/

I would suggest reverting this as this is really a problem with the data, not with Skosmos code.

**Comment by osma** [comment]
This was a bug in the Skosify configuration file, it mapped to dc11:modified which doesn't exist. I've now changed it to dct:modified

**Comment by osma** [comment]
I think it works now but the commits should be reverted and then verified that the date is still shown
