### ISSUE TITLE
Reverse proxy setting not respected in certain places

### ISSUE THREAD

**Issue by jneubert** [NatLibFi/Skosmos#471]
Our Skosmos 1.5 installation works behind a reverse proxy. Therefore, we use 

    define("BASE_HREF", "http://zbw.eu/beta/skosmos/");

in the `config.inc`.

However, when I'm e.g. on the page http://zbw.eu/beta/skosmos/stw/en/ and click the link labeled "Auf Deutsch" to switch the interface language, the page is messed up: the requested content is loaded, but CSS files and the like are not, because in the href of the "Auf Deutsch" link the IP address of the server behind the reverse proxy is referenced.

Another possibly related issue: When I search for a value which does not exist (say "xxxx"), the result page shows the message "No vocabularies on the server!" and the links in the header switch to http://zbw.eu for "Vocabularies", http://zbw.eu/about for "About" etc.

**Comment by henriyli** [comment]
It's a bit tricky to test this. I think that it should work now after 4063398 though. Could you pull the latest patch from the v1.5-maintenance branch and check if that fixed the issue?

**Comment by jneubert** [comment]
The links in the header bar work fine now. Thank you for fixing this so quickly!

The search issue mentioned above has changed a bit - I've moved it to #472, in order to make it easier to trace in a separate issue.
