### ISSUE TITLE
Wrong kind of page shown after search for non-existing value

### ISSUE THREAD

**Issue by jneubert** [NatLibFi/Skosmos#472]
When I search for a value which does not exist (say "xxxx"), the result page shows the message "No vocabularies on the server!" and the links in the header switch to http://zbw.eu for "Vocabularies", http://zbw.eu/about for "About" etc.

After the solution of #471 via 4063398, the behaviour changed: E.g. the "Auf Deutsch" link, http://zbw.eu/beta/skosmos/swdskos/de/ before the search for "xxxx", becomes "http://zbw.eu/beta/skosmos/", while the About link, which was http://zbw.eu/beta/skosmos/en/about?clang=de before the search for "xxxx", becomes http://zbw.eu/about.

**Comment by osma** [comment]
It's not just about the links, the whole page is not what it should be.

Compare these two pages, which are both search results for `xxxx` in STW:
http://zbw.eu/beta/skosmos/stw/en/search?clang=en&q=xxxx
http://skosmos.dev.finto.fi/stw/en/search?clang=en&q=xxxx
The latter one works fine.

The major error seems to be the "No vocabularies on the server" message.

It seems to me that Skosmos is not getting the right information from the URL at all. For example, looking at the HTML, I see these javascript variables being set:

```js
<!-- variables passed through to javascript -->
var lang = "";
var content_lang = "";
var vocab = "";
```

If everything worked well, these variables should have been set to `"en"`, `"en"` and  `"stw"`, respectively.

**Comment by osma** [comment]
Not sure if this is relevant at all, but I noticed that there is a problem with global search on the ZBW Skosmos installation:
http://zbw.eu/beta/skosmos/en/search?clang=en&q=xxxx&vocabs=

This gives a (quite graphical!) error about the SPARQL endpoint not being available (apparently generated by Tomcat). I wonder if the DEFAULT_ENDPOINT setting in config.inc is correct? @jneubert could you try fixing DEFAULT_ENDPOINT to see whether it makes a difference?

**Comment by jneubert** [comment]
Hi Osma, obviously, setting the DEFAULT_ENDPOINT to a valid URI value fixed it. I suppose that several issues and maybe fallback mechanisms interfered (the old URI was valid before, and I did not see the Tomcat warning). Anyway, now it works great!
