### ISSUE TITLE
Wiki: Split chapter in Install Tutorial

### ISSUE THREAD

**Issue by jneubert** [NatLibFi/Skosmos#482]
The [Install Tutorial](https://github.com/NatLibFi/Skosmos/wiki/InstallTutorial) for Skosmos contains a very useful chapter on Fuseki installation. I'd like to link to this chapter also from the skos-history project. However, currently the installation of Fuseki in general and the loading of the Skosmos-specific database are covered in the same chapter of the tutorial. Would it be ok to change this?

Currently:

    Install Jena Fuseki and vocabularies
      Install Java 8
      ...
      Make Fuseki start automatically at boot
      Create and configure a database and text index
      Load data

Suggested:

    Install Jena Fuseki
      Install Java 8
      ...
      Make Fuseki start automatically at boot
    Create and load vocabularies database
      Create and configure a database and text index
      Load data

Then, https://github.com/NatLibFi/Skosmos/wiki/InstallTutorial#install-jena-fuseki would precisely link to the general Fuseki install description.

**Comment by osma** [comment]
You're absolutely right. The tutorial is still a work in progress (see #364) and since it has become rather long I had also planned to split it up into several wiki pages. Your solution to split up the Fuseki part also makes sense.

**Comment by osma** [comment]
Done.
