### ISSUE TITLE
Top level class numbers (skos:notation) not shown in hierarchy when switching to the hierarchy tab from the vocabulary info page

### ISSUE THREAD

**Issue by danmichaelo** [NatLibFi/Skosmos#484]
Not sure if the title makes sense, but here's the case:

* If I go to the vocabulary info page https://data.ub.uio.no/skosmos/ddc/nb/ , then switch to hierarchy, class numbers for the top classes are not shown (and consequently the sorting is wrong).
* If I go directly to a concept, like https://data.ub.uio.no/skosmos/ddc/nb/page/1 , they are shown correctly.

![skosmos-test](https://cloud.githubusercontent.com/assets/434495/13676251/52d8eebe-e6e5-11e5-9dad-88343ff29582.gif)

The same behaviour is observed on http://dev.finto.fi/udcs/en/ , but is less prominent there because the top concepts have dummy class numbers ("----" and "-").

**Comment by osma** [comment]
Closing as duplicate of #483, entered just a few minutes ago :)
Nice animation!
