### ISSUE TITLE
Thesaurus arrays show up in wrong context

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#491]
EXample: The concept "sawmills" has two broader concepts one of which is a concept ("production plants") and the other a thesaurus array ("yritykset toimialan mukaan"). This thesaurus array also shows up when viewing the concept "production plants" as a narrower concept even though this is not true.

**Comment by osma** [comment]
Better example: http://finto.fi/yso/en/page/p1251
"pilgrimages" is shown under "matkat teeman mukaan", but this is an inappropriate context for that thesaurus array.

**Comment by osma** [comment]
Should check that all the members of the array are also narrower concepts of the present concept. In other words, there doesn't exist a member of the array that is not a narrower concept of the current concept.
