### ISSUE TITLE
SPARQL requests time out after 10 seconds

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#509]
SPARQL queries performed by Skosmos always time out after 10 seconds and it is not possible to set this except by modifying EasyRdf code. See [discussion on skosmos-users](https://groups.google.com/d/msg/skosmos-users/WhtZwnsxOFs/MtAocr8vDgAJ).

We should make this timeout configurable, probably in config.inc.

**Comment by osma** [comment]
I've had to edit the timeout in EasyRdf (set it to 60 seconds) to be able to get LCSH working on skosmos.dev.finto.fi

**Comment by adrianogoncalves** [comment]
Use setConfig(), from EasyRdf_Http_Client.
