### ISSUE TITLE
Blank page and 500 error when URI contains space

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#513]
## At which URL did you encounter the problem?
http://finto.fi/ysa/fi/page/Y101474%20

## What steps will reproduce the problem?
1. Go to a concept page with an extra space (%20) in the URL

This sometimes happens for example when links are copied and pasted from e-mail.

## What is the expected output? What do you see instead?

Currently you get a blank page. The error code is 500 Internal Server Error but there is no message to the user.

What happens is that the URI with the space included gets passed to the SPARQL endpoint, which then gives a 400 parse error.

Better alternatives:
1. 404 error message, as in other cases where the URL is mistyped
2. 500 error as currently, but with an error message shown to the user
3. Silently working, i.e. stripping whitespace from the URI before using it
4. Noticing that there is an extra space and performing a redirect to the correct URL, without the space (similar to what mod_speling does)

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by henriyli** [comment]
Implemented options 1 and 3.
