### ISSUE TITLE
Add contributing doc and issue template

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#521]
GitHub nowadays supports special files that will help potential contributors:
https://help.github.com/articles/helping-people-contribute-to-your-project/

We should create an ISSUE_TEMPLATE.md file and a CONTRIBUTING.md file.

We already have a sort of issue template encoded in the link URL in the README, but it is not used if you go to the Issues tab directly.

**Comment by henriyli** [comment]
Issue template added in 56231250c1fa440cf4b0883c4067b9c01ef96d37

**Comment by henriyli** [comment]
The contributing doc has now been added.
