### ISSUE TITLE
Display SKOS XL metadata

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#533]
SKOS XL information about labels should be shown in the UI, similar to how metadata of reified definitions (#477) is displayed.

This depends on first having the SKOS XL metadata available from the concept info SPARQL query (#109).

**Comment by osma** [comment]
We've already implemented similar functionality for definitions, and the SPARQL query part is done, so what remains is size=medium.

**Comment by henriyli** [comment]
implemented in: 0f1d785019f9f90b0e8c457e28b07c3d191b35a9 , d3db5dec05537d0483d06934f40e0d219db5f3a0 , 632169aae50e3ec1441cc6b277804350b05e10a9 , f424cd61912b7a2ce8af55787f7272fd90531fbc and 5978fd523ff89471b4556ecf219d10787cc816fd

**Comment by henriyli** [comment]
Skos-xl metadata should now be visible when the (i)-icon appears next to a label. Horrible UX, but we'll have to deal with that later.
