### ISSUE TITLE
Hierarchy doesn't load in IPTC Scene

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#541]
## At which URL did you encounter the problem?
http://dev.finto.fi/iptc-scene/en/page/010300

## What steps will reproduce the problem?
1. Go to any IPTC Scene concept
2. Look at the Hierarchy tab

## What is the expected output? What do you see instead?

Expected to see the concept hierarchy (IPTC Scene is a flat list, so there should be only top concepts).

Instead seeing a Loading... message. The JavaScript console shows this error:

```
TypeError: this.get_container_ul(...)[0] is undefined
..._model.force_full_redraw&&(c.className=this.get_container_ul()[0].className,c.se...
```

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox 46.0 / Ubuntu

**Comment by osma** [comment]
With Chromium behavior is the same, but error message is slightly different:
```
Uncaught TypeError: Cannot read property 'className' of undefined 
```

**Comment by osma** [comment]
I've checked the results of the `hierarchy` REST call and they seem fine.

Also the hierarchy seems to work in other vocabularies in dev.finto.fi, at least the ones I checked.

**Comment by henriyli** [comment]
For some reason the custom scrollbar initialization begins while the jstree is still loading the tree and this causes the error described above.
