### ISSUE TITLE
Order of Enter search results for domain ontologies

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#546]
Domain ontologies consist of two ontologies: a) domain ontology and b) YSO ontology to which the domain ontology is linked. Enter search results are shown in alphabetical order with the YSO concept first and domain ontology concept second in case of identical preferred terms. It would make more sense to show the domain ontology concept first. Or perhaps better still, show all domain ontology concepts first in alphabetical order and after that the YSO concepts in alphabetical order.
## At which URL did you encounter the problem?

http://finto.fi/kauno/fi/search?clang=fi&q=el%C3%A4inten+k%C3%A4ytt%C3%A4ytyminen

**Comment by tpalonen** [comment]
See also issue #222 .

**Comment by osma** [comment]
The search result order is determined by the ORDER BY clause. At that level we don't have knowledge that a particular concept type should be preferred. So I'm not sure how to implement this.

However, with the import facility (#63) the situation might change a bit.

**Comment by kouralex** [comment]
I wonder if this could be a vocabulary specific configuration, e.g., `skosmos:resultOrder` or similar which would then be given as a parameter to the SPARQL query builder.

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
