### ISSUE TITLE
vocabularies.ttl world readable

### ISSUE THREAD

**Issue by semanticfire** [NatLibFi/Skosmos#555]
http://<host>/skosmos/vocabularies.ttl

1. Downloads the vocabularies.ttl when using passwords for endpoint not desired

403 Forbidden, no one needs to see the configuration

adding:

`<Files ~ "\.ttl$">
Order allow,deny
Deny from all
</Files>`

to .htaccess solves this problem

**Comment by osma** [comment]
Thanks for reporting. We haven't had passwords in vocabularies.ttl files, so it didn't occur to us that it would need protection. But you are right, configuration files of web applications should not be world readable.
