### ISSUE TITLE
Alphabetical index is not in natural sort order

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#559]
## At which URL did you encounter the problem?

http://finto.fi/yso/fi/index/T
## What steps will reproduce the problem?
1. Scroll to the bottom of the listing
2. Wait for additional results
## What is the expected output? What do you see instead?

Expected to get a natural sort order for the listing. I'm seeing š-character at the end of the list. For example: tšekin kieli comes after töyhtöhyyppä.
## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by henriyli** [comment]
The sorting is done in the sparql query. Since the results are limited and then offset in the second query sorting the results afterwards isn't really an option.
```sparql
ORDER BY LCASE(IF(BOUND(?alabel), STR(?alabel), STR(?label)))
```
I'm not sure what we should do here. After the results are completely loaded (after the second query) the sorting could be done in javascript but that doesn't fix the first set of results that have been limited.

**Comment by osma** [comment]
I asked about this on the Jena users' mailing list: http://jena.markmail.org/thread/v2bvsnsza5ksl2cv

**Comment by osma** [comment]
This turns out to be difficult. It would require changes to Jena so that it would sort language-specific collation.

**Comment by osma** [comment]
See discussion on Jena users list:  http://markmail.org/message/v2bvsnsza5ksl2cv

**Comment by osma** [comment]
Opened a JIRA issue on the Jena side: https://issues.apache.org/jira/browse/JENA-1313

**Comment by kinow** [comment]
@osma can this one be closed too now? Or do we have to wait for the deployment and confirmation that it's working as expected?

**Comment by henriyli** [comment]
Seems to work very well now. Thanks!
