### ISSUE TITLE
Missing namespace declarations in RDF/XML syntax

### ISSUE THREAD

**Issue by amiika** [NatLibFi/Skosmos#563]
## At which URL did you encounter the problem?
Any RDF/XML export or for example:
http://finto.fi/rest/v1/mts/data?uri=http%3A%2F%2Furn.fi%2FURN%3ANBN%3Afi%3Aau%3Amts%3Am441&format=application/rdf%2Bxml

## What steps will reproduce the problem?
1. Load RDF/XML
2. Validate

## What is the expected output? What do you see instead?
RDF/XML syntax is missing namespaces:
Include <rdf:xml xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" ... ETC. ...

**Comment by osma** [comment]
I don't see the problem. The rdf namespace for example is declared.
Maybe your browser is hiding the namespaces? Check "view source"

**Comment by amiika** [comment]
... right. Nevermind :)
