### ISSUE TITLE
Ontology header not visible on smart phones

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#565]
When browsing ontologies and concepts with smart phones, the ontology header is not shown, ie. users are not told which ontology they are currently browsing. Users can only figure out the ontology from the concept URIs, which is not very user-friendly.

**Comment by henriyli** [comment]
The original design doesn't really work on mobile since all the elements have to fit in a very narrow one row bar. A lazy solution would be to add another element on top of the search bar that would contain the vocabulary name. This new element should only be shown in the mobile layout.
