### ISSUE TITLE
Debug logging of SPARQL queries

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#566]
It is currently difficult to debug problems with individual SPARQL queries. The queries are sent directly to the endpoint but when that fails for some reason (e.g. gives a 400 or 500 error), the errors may not be very informative. The actual query has to be looked up from the logs of the SPARQL endpoint.

It would help to have a logging facility within Skosmos that would capture all the SPARQL queries (and possibly their responses too, in some form).

This should be a setting in `config.inc` which defaults to off, e.g. `SPARQL_LOGFILE` that sets a file name to use as the log file.

Implementing this would be easiest if we add a new method `query` in GenericSparql that wraps the query method of EasyRdf_Sparql_Client and prints to the debug log if it has been enabled. Currently all the methods in GenericSparql use `$this->client->query` directly, so this would be changed everywhere to `$this->query`.

**Comment by osma** [comment]
See [this thread](https://groups.google.com/d/msg/skosmos-users/11ROK0C7NyU/iGv5mL3hCgAJ) on skosmos-users about problems with Virtuoso. It would be easier to sort out problems like this having a debug log.

**Comment by osma** [comment]
@namedgraph see [Configuration](https://github.com/NatLibFi/Skosmos/wiki/Configuration), in particular the settings skosmos:logFileName and skosmos:logBrowserConsole

**Comment by namedgraph** [comment]
That's the thing, I don't want a file :) I just want them part of the main log.

**Comment by osma** [comment]
Ah. Sorry, I don't think that's possible right now (but you can try to see what happens if you use "/dev/stdout" or "/dev/stderr" as the filename).

But what "main log" are you referring to? Apache access.log? error.log? Something else?
