### ISSUE TITLE
empty FROM clause causes errors on Stardog

### ISSUE THREAD

**Issue by semanticfire** [NatLibFi/Skosmos#567]
My SKOS dataset is stored in the default graph.

I have no skosmos:sparqlGraph defined and this resolution results in NULL

The checks in GenericSparql however do not check for null, hence causing issues

**Comment by osma** [comment]
Thanks for reporting. This probably broke with the FROM refactoring in version 1.8 (#534).

**Comment by osma** [comment]
Fixed by merging #568.
