### ISSUE TITLE
different type of fonts in concept page

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Skosmos#584]
## At which URL did you encounter the problem?
http://finto.fi/mts/fi/page/m1241

## What steps will reproduce the problem?
1.
2.
3.

## What is the expected output? What do you see instead?
The font type of the group "esittäjä" under the "KUULUU RYHMÄÄN"-property is different from the other values of the same property

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
firefox

**Comment by osma** [comment]
Screenshot showing problem:

![mts-fonttiongelma](https://cloud.githubusercontent.com/assets/1132830/22820011/9547caee-ef7d-11e6-9de9-6bb284450061.png)
