### ISSUE TITLE
Improve spam blocking in feedback form

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#594]
The feedback form seems to pass through more spam than it used to be. The trick we are using to protect the form (hidden field etc) is not working so well anymore. We should try to come up with better measures. A CAPTCHA would be the ultimate, but I would prefer to avoid that if we can as it's annoying for users.

See [discussion on skosmos-users](https://groups.google.com/d/msg/skosmos-users/velzz0XjinQ/EU0-MQiRDgAJ)

**Comment by kinow** [comment]
I found this field https://github.com/NatLibFi/Skosmos/blob/0b2ba5db4c526b0c921d1f02d39d100043028431/view/feedback.twig#L39

I also prefer honeypots to captchas. The one I've been using in some web sites is this one for Laravel: https://github.com/msurguy/Honeypot

I normally add 4, 5 fields, sometimes required, some times not. Further customization is possible to add randomness to name and value requirements.

Besides checking the fields, the library also discards requests that happen too fast, under a certain threshold that depends on the kind of form.

Perhaps we could try a similar approach?

Hope that helps,
Bruno

**Comment by osma** [comment]
@kinow Thanks a lot for the excellent tips!

**Comment by osma** [comment]
As always, PRs are very welcome...

**Comment by kinow** [comment]
Haven't written any PHP in a while. Sounds like a good exercise (unless someone else beats me :)

**Comment by osma** [comment]
@kinow So, what are your plans? Are you interested in doing this? A contribution would be very welcome! :)

**Comment by kinow** [comment]
@osma, yup. Just releasing some Jenkins stuff, then jump back to Jena and can work on Skosmos in parallel (after all I haven't used it with the latest version of Jena).

**Comment by osma** [comment]
@kinow Great! If you use Skosmos with latest Jena, you should be aware of #562 - some things (concept pages and search result page) may be a bit slow. It's nowhere near as bad now (on the Skosmos `master` i.e. development branch) as it was originally, but still Skosmos is SPARQL queries are not performing as they should. This was apparently caused by changes to ARQ in Jena 3.1.1.

**Comment by kinow** [comment]
Done @osma!

**Comment by henriyli** [comment]
Thank you @kinow!
