### ISSUE TITLE
makeCallbacks js variable parsing is fragile

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#597]
## At which URL did you encounter the problem?
http://dev.finto.fi/hero/fi/page/p2917

## What steps will reproduce the problem?
1. Click on [cadency 5] annulet (en) from the hierarchy tree (or any of the [cadency *] concepts).

## What is the expected output? What do you see instead?
The concept page loads as expected but the plugin on the page doesn't get executed. There is an error in the javascript parameter parsing in the browser console ("SyntaxError: JSON.parse: unterminated string at line 1 column 37 of the JSON data" scripts.js:253). The fragile parameter parsing seems to go wrong because of the angle brackets in the prefLabel. This prevents the plugin callbacks from being called. 

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by kinow** [comment]
There ya go!
https://github.com/NatLibFi/Skosmos/pull/598

**Comment by henriyli** [comment]
Thank you @kinow !  :relaxed:  :thumbsup:
