### ISSUE TITLE
Add REST API method for alphabetical index

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#599]
The data used by the alphabetical index (list of letters + list of concepts whose label start with a given letter) is not exposed via the REST API. We should add API methods that correspond to that functionality.

It shouldn't be difficult since the functionality already exists, we just need to take care of parameter handling and converting the results to JSON-LD + documentation in the Swagger docs.

**Comment by osma** [comment]
Some thoughts on the new REST API method design:

* the method(s) should be called `index` to correspond with the UI paths
* the methods are vocabulary-specific
* at least two methods are needed:
  1. one that returns the letters of the alphabetical index (e.g. ["A", "C", "S", "M"]): requires vocabulary (implicitly, from the path) and language as parameters
  2. one that returns the concepts/terms for a single letter: requires vocabulary (implicitly), language and letter as parameters

I can think of (at least) two options here for how the REST method URLs could look:

## Parameter style

`/rest/v1/vocab/indexLetters?lang=<language>` -> list of letters available in the vocabulary, in the given language
`/rest/v1/vocab/index/<letter>?lang=<language>` -> list of terms/concepts for that letter

Benefits:
* follows the style of the existing methods in the Skosmos REST API
* lang parameter could be optional (defaulting to the default language of the vocabulary)

Downsides:
* not very RESTful - for example, the methods have no obvious relationship on a URL level even though conceptually they are closely related

## Path style

`/rest/v1/<vocab>/index` -> list of languages available in the vocabulary
`/rest/v1/<vocab>/index/<language>` -> list of letters available in the vocabulary, in the given language
`/rest/v1/<vocab>/index/<language>/<letter>` -> list of terms/concepts for that letter

Benefits:
* more RESTful in some sense
* exposes the available languages (though they can be queried also from the vocabulary base URL)

Downsides:
* different from the normal Skosmos REST API method style where `lang` is a parameter
* three methods instead of two: more work to implement, document, understand...

Any comments/preferences? E.g. @kinow , @danmichaelo , @nichtich ?

**Comment by kinow** [comment]
@osma what if option 1 were:

/rest/v1/vocab/index/letters?lang=<language> -> list of letters available in the vocabulary alphabetical index, in the given language
/rest/v1/vocab/index/letter/<letter>?lang=<language> -> list of terms/concepts for that letter in the vocabulary alphabetical index

>    not very RESTful - for example, the methods have no obvious relationship on a URL level even though conceptually they are closely related

This uses the index as parent resource. And letters vs letter, as in GitHub pulls vs pull & issues vs issue. So maybe still RESTful, and approximates the concepts through the common index, and letter/letters?

**Comment by osma** [comment]
Thanks @kinow. While working on this yesterday I came to a similar conclusion, just a bit shorter:

`/rest/v1/<vocab>/index/?lang=<language>` -> list of letters available in the vocabulary alphabetical index, in the given language
`/rest/v1/<vocab>/index/<letter>?lang=<language>` -> list of terms/concepts for that letter in the vocabulary alphabetical index

This way both methods are grouped under `index/`, which functions like a "directory" of letters. The `lang` parameter can be omitted, as always.
