### ISSUE TITLE
Visualizing conceptual schemas (UML)

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#607]
There is a growing need for Skosmos to enable the visualization of UML-type conceptual schemas as an additional way to browse a vocabulary with such properties. Currently, there is at least one terminological dictionary with such needs that is wished to be published on Finto, and several other dictionaries expected to follow later. The conceptual schemas of this aforementioned terminological dictionary are at the moment maintained with Microsoft Vision in .vsdx format.

Some further notions and questions:
- Each schema includes information on several concepts, some of the concepts may be more focal in a given schema, some less so. One concept may be included in several schemas.
- It is wished that these conceptual schemas show at least: the names of concepts, definitions of these concepts and their relations to each other.
- It is wished that the names of concepts would also act as a link to the respective concept page.
- Is it possible to fit this visualization to the current Skosmos layout or should these schemas be shown in a separate window/tab?
- Is it possible to show a given concept's inclusion in a concept schema as a property in the concept page which would also act as a link to the conceptual schema? Property could be called e.g. "Part of concept schema".
- Is it possible to update concept names and definitions to both concept pages and conceptual schemas by editing a single source/file? Or should concept schemas be edited as a separate file?

**Comment by osma** [comment]
Being worked on as a Skosmos plugin.

**Comment by osma** [comment]
The plugin is here: https://github.com/NatLibFi/Skosmos-widget-tieto
Closing this issue as it's not specific to Skosmos code.
