### ISSUE TITLE
REST lookup for term containing single quote fails

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#610]
## At which URL did you encounter the problem?
http://api.dev.finto.fi/rest/v1/yso/lookup?label=women%27s%20culture

## What steps will reproduce the problem?
1. Perform a REST lookup search for a term containing a single quote (e.g. `women's culture` in YSO or `Women's rights` in LCSH)

## What is the expected output? What do you see instead?

Expected to get the matching concept as result. Instead getting this error:

```404 Not Found : Could not find label 'women&#39;s culture'null```

Note also the `null` at the end

**Comment by henriyli** [comment]
this has now been fixed and backported to v1.8-maintenance
