### ISSUE TITLE
Support truncating notation in search

### ISSUE THREAD

**Issue by danmichaelo** [NatLibFi/Skosmos#617]
The search help states that that you can truncate with "*" and that it right-truncates by default. This currently doesn't work for notations though, which are not part of the search index (#456). At least for decimal classification systems it would be quite handy – e.g. if I search for a Dewey number "539.7" to see what classes there are having a number starting with that number.

**Comment by osma** [comment]
Right. It's doable, but would best be implemented using the text index, otherwise performance would be bad. Contributions welcome!

**Comment by osma** [comment]
And sorry that it took so long to respond!

**Comment by osma** [comment]
We need an implementation both for generic and jena-text SPARQL.

Generic implementation:
* change the concept search query: implement the support using e.g. REGEX in the GenericSparql class (which may be slow in case of large classifications, but that's fine)

Jena-text implementation:
* add a field for skos:notation in the jena-text index (and mention this in the wiki docs)
* change the concept search query in JenaTextIndex

**Comment by joelit** [comment]
> We need an implementation both for generic and jena-text SPARQL.
> 
> Generic implementation:
> 
> * change the concept search query: implement the support using e.g. REGEX in the GenericSparql class (which may be slow in case of large classifications, but that's fine)

Looking at the specifications for the classification notations currently in use for Skosmos (YKL, (Dewey-based) HKLJ and UDC (thanks, @jarmosaarikko) ) - I think it is best if a generic regex implemantation would have a configurable property in config.ttl to keep the GenericSparql functionality within sane and testable limits, e.g.:
```
:vocab
    skos:notationIndex "regex-dewey";
```
We'll add rules and documentation for new notations when needed - I'll pick something reasonable to start with.
