### ISSUE TITLE
Proper links in the search autocomplete menu

### ISSUE THREAD

**Issue by danmichaelo** [NatLibFi/Skosmos#622]
User story: As a user, I might want to open several of the autocomplete suggestions in different tabs, but right now I cannot right-click on the suggestions and "open link in new tab" because the items are not proper links. An example of  a menu element:

```html
<div class="tt-suggestion">
  <p class="autocomplete-label" style="white-space: normal;">
    <strong class="tt-highlight">Test</strong>barhet
  </p>
  <span class="concept-type" style="white-space: normal;">Innholdsbeskrivende emne</span>
  <div class="vocab" style="white-space: normal;"></div>
</div>
```` 

Would be great if this could be changed to something like this:

```html
<a class="tt-suggestion" href="//server/lang/page/c012075">
  <p class="autocomplete-label" style="white-space: normal;">
    <strong class="tt-highlight">Test</strong>barhet
  </p>
  <span class="concept-type" style="white-space: normal;">Innholdsbeskrivende emne</span>
  <div class="vocab" style="white-space: normal;"></div>
</a>
```` 

I could try submitting a PR for this if you agree it's a good idea.

**Comment by osma** [comment]
Sounds good in principle. However, we must make sure that usability is not negatively affected by this. The autocomplete widget has been tweaked many times during the development history, and in general we want to preserve those changes. A PR sounds like a good way of moving this forward!

Your HTML code example seems invalid though, I don't think you can put `p` or `div` elements within `a`. The block level elements need to be changed to inline elements if you want to wrap everything in a link.

**Comment by osma** [comment]
Of course, you could, as a user, just press Enter (or click the search button) to get the actual search result page, which contains real links -- and chances are that the necessary information is already there on the result page, or can be configured to appear there using vocabularies.ttl.

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
