### ISSUE TITLE
Show notation for mapped concepts

### ISSUE THREAD

**Issue by danmichaelo** [NatLibFi/Skosmos#623]
A concept can have mappings to multiple classes with the same heading, but different notation. As a user, it would be easier to distinguish between these if the notation were shown.

Example: At http://data.ub.uio.no/humord/c00667 we have mappings to three different Dewey classes with the same class heading, but different notation. Currently, they are pressented in the same way, making it hard to distinguish between them.

**Comment by tfrancart** [comment]
(seems to work properly on latest version, I can see notations next to the mapped concept labels)

**Comment by danmichaelo** [comment]
Cool, it does 🎉  Just updated my instance to master and there's now notations in the original example: http://data.ub.uio.no/humord/c00667

Minor thing: perhaps include the notation in the link? Other places, like in the lists of broader and narrower concepts, notations are included in the links.

**Comment by henriyli** [comment]
Closing as the notations should now be inside the a elements.
