### ISSUE TITLE
Translations in Frensh not displayed by Twig

### ISSUE THREAD

**Issue by mhabsaoui** [NatLibFi/Skosmos#624]
## At which URL did you encounter the problem?
Skosmos Site only available on intranet for now :  http://localhost:1888/skosmos/Art_Archeologie/fr/

## What steps will reproduce the problem?
1. Select all languages in French
2. select one of the vocabularies
3. There you see some fields in English...

## What is the expected output? What do you see instead?

All text shown must be in French, but some fields obviously related to Skosmos are in English...

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
On Firefox/chrome... Non browser related ;)  Under Linux Ubuntu 16.04 LTS.

And as you can see below, fields marked in red squares are in English !

![image](https://user-images.githubusercontent.com/18755135/30646728-3fba4ab0-9e1a-11e7-8f99-e7dd3c2dce4e.png)

Following up leads :
=> Mismatch between OS Locale and Skosmos Translation automation ??

![image](https://user-images.githubusercontent.com/18755135/30649399-7441d482-9e20-11e7-884c-6fe568af38a2.png)

![image](https://user-images.githubusercontent.com/18755135/30648908-73c3c1c4-9e1f-11e7-88f9-953c6f0b90d1.png)

=> Missing "skosmos_fr.mo" next to "skosmos_fr.po", whereas the twig trans is activated in twig template and French translation available ??
![image](https://user-images.githubusercontent.com/18755135/30647073-fbc6d426-9e1a-11e7-92aa-634dbf5222af.png)

![image](https://user-images.githubusercontent.com/18755135/30649228-0718e184-9e20-11e7-9e44-dbd9f04e58b9.png)

![image](https://user-images.githubusercontent.com/18755135/30647361-82cf3d1e-9e1b-11e7-8644-67be23426def.png)

Thanks for help.

**Comment by osma** [comment]
Hi @mhabsaoui , do you have the fr_FR.UTF-8 locale installed? Your screenshot showing `locale -a` output doesn't list it, but maybe it shows only part of the output. Make sure you have that locale installed, then restart Apache.

**Comment by mhabsaoui** [comment]
Thanks, yep in fact have noticed that inside our skosmos docker container the the fr_FR.UTF-8 locale isn't installed, whereas on the host machine it is.

So after generating Fr locale inside container, it's OK and the French fileds are there :+1: 

![image](https://user-images.githubusercontent.com/18755135/30651196-4e910a5a-9e25-11e7-851b-08db1a6f704b.png)
