### ISSUE TITLE
Document how Skosmos handles deprecated concepts

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#630]
## At which URL did you encounter the problem?

https://github.com/NatLibFi/Skosmos/wiki/Data-Model

## What is the expected output? What do you see instead?

This page does not document that Skosmos can handle deprecated concepts, and how it handles them. I suggest adding a section under "Concepts", if I understand correctly the behavior (if not, please amend my suggestion) :

### Deprecated Concepts
Deprecated concepts are concepts that are no more valid but are kept in the vocabulary for backward compatibility. Skosmos can detect deprecated concepts with :
  - an `owl:deprecated true` metadata on the `skos:Concept`;
  - optionnally, the `dcterms:replacedBy` pointing to the (possibly multiple) concepts that replace this one;

Deprecated concepts will not be visible in the alphabetical listing, in the hierarchical view, and cannot be searched. They can still be accessed through their URI.

**Comment by henriyli** [comment]
This would definitely be an improvement to the current documentation. Thank you for your suggestion @tfrancart! I will make the suggested changes to the wiki.

**Comment by henriyli** [comment]
I modified the documentation as you suggested and added a minimal example of what the data of a deprecated concept should look like for Skosmos to work optimally. Closing this for now, but feel free to open this if you have more ideas for improving this part.

**Comment by markusfiebig** [comment]
I would need a clarification in the documentation. I have a vocabulary where [a whole branch in a hierarchy](https://vocabulary.actris.nilu.no/actris_vocab/aerosolparticlefiltersampler) has been deprecated, in favour of [an updated branch](https://vocabulary.actris.nilu.no/actris_vocab/aerosolparticlesampler). However, the deprecated branch stays visible in the hierarchy view of SKOSMOS. Is this normal behaviour? Why?

**Comment by osma** [comment]
@markusfiebig you are right, this is a bug, see issue #1143. There was also some work on a fix in PR #1173, but unfortunately that worked stalled. Now we are focusing our development efforts on Skosmos 3, which means that we cannot spend time fixing problems in Skosmos 2 unless they are really important especially from our perspective (Finto.fi).

For now I think your best bet is modifying the vocabulary data itself if you want to hide the deprecated branch. If you drop the hierarchical relations (skos:broader/skos:narrower) then obviously it won't show up in the hierarchy. This is what we do when we deprecate concepts in YSO and other Finto vocabularies; we also drop their connections to other concepts.
