### ISSUE TITLE
Write missing wiki documentation for collections, arrays and groups 

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#631]
## At which URL did you encounter the problem?
https://github.com/NatLibFi/Skosmos/wiki/Data-Model

## What steps will reproduce the problem?
See bottom of above wiki page.

## What is the expected output? What do you see instead?
The features that Skosmos provides for collections, arrays and groups are undocumented. As the documentation was extended with features regarding deprecated concepts have now been documented, these features should be documented as well.

**Comment by henriyli** [comment]
I've now written initial documentation for groups and collections, but the arrays still need to be documented.

**Comment by osma** [comment]
Not a code change, so not blocking for 2.0.

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
