### ISSUE TITLE
IExplore 11: 404 when switiching from hierarchy to alphabetical and back to hierarchy

### ISSUE THREAD

**Issue by d0rg0ld** [NatLibFi/Skosmos#633]
Hi,

In Internet Explorer (Not in Chrome and not in Firefox, versions see below) I encounter the following problem: 

## At which URL did you encounter the problem?

This happens when using the current SKOSMOS dev snapshot, but can also be reproduced in Finto for example:

http://finto.fi/pto/en/page/?uri=http://paikkatiedot.fi/def/1001002/p678

## What steps will reproduce the problem?
1. Navigate to http://finto.fi/pto/en/page/?uri=http://paikkatiedot.fi/def/1001002/p678
2. Switch to "Alphabetical"
3. Switch back to "Hierarchy"

## What is the expected output? What do you see instead?

The browser should navigate back to http://finto.fi/pto/en/page/?uri=http://paikkatiedot.fi/def/1001002/p678 but tries to open http://finto.fi/pto/en/pto/en/page/?uri=http://paikkatiedot.fi/def/1001002/p678 instead, leading to a 404.

The malformed URL contains one vocab/lang pair ( here pto/en/ ) too much

I suspect that this happens in the context of the call "window.location.replace(encodeURI(redirectUrl));" in resource/js/docready.js:364. 

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

IExplore 11 (11.0.9600.18697)
Windows 7

This problem does *not* appear in Chrome 61.0.3163.100 and Firefox 55.0.3

**Comment by osma** [comment]
Thanks for reporting.
