### ISSUE TITLE
Uncaught EasyRdf_Exception

### ISSUE THREAD

**Issue by mhabsaoui** [NatLibFi/Skosmos#635]
## At which URL did you encounter the problem?
http://localhost:8080/Biodiversit%C3%A9_ARK/fr/

## What steps will reproduce the problem?
1. Select any vocabulary on front page.
2. the error shows up on blank page

## What is the expected output? What do you see instead?

- The  next page showing content of selected vocab

- > Fatal error: Uncaught EasyRdf_Exception: Unable to connect to localhost:3030 (Cannot assign requested address) in /var/www/html/vendor/easyrdf/easyrdf/lib/EasyRdf/Http/Client.php:423 Stack trace: #0 /var/www/html/vendor/easyrdf/easyrdf/lib/EasyRdf/Sparql/Client.php(276): EasyRdf_Http_Client->request() #1 /var/www/html/vendor/easyrdf/easyrdf/lib/EasyRdf/Sparql/Client.php(120): EasyRdf_Sparql_Client->request('query', 'SELECT ?cs ?lab...') #2 /var/www/html/model/sparql/GenericSparql.php(72): EasyRdf_Sparql_Client->query('SELECT ?cs ?lab...') #3 /var/www/html/model/sparql/GenericSparql.php(652): GenericSparql->query('SELECT ?cs ?lab...') #4 /var/www/html/model/Vocabulary.php(210): GenericSparql->queryConceptSchemes('fr') #5 /var/www/html/model/Vocabulary.php(227): Vocabulary->getConceptSchemes() #6 /var/www/html/model/Vocabulary.php(139): Vocabulary->getDefaultConceptScheme() #7 /var/www/html/vendor/twig/twig/lib/Twig/Template.php(680): Vocabulary->getInfo('fr') #8 /tmp/skosmos-template-cache/33/33ee68b76e69dfd64d470b6af94c1e in /var/www/html/view/vocab-shared.twig on line 9

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox, Chrome

PS: 
- the jena-fuseki endoint (http://localhost:3030/ds/sparql) is correctly accessed from YASGUI client even through CORS (http://yasgui.org/). But not from Skosmos...

- I used the docker version of jena-fuseki (https://hub.docker.com/r/stain/jena-fuseki/)

- console logging :

![image](https://user-images.githubusercontent.com/18755135/31546049-07fe92ce-b022-11e7-9830-2cf31046814e.png)

![image](https://user-images.githubusercontent.com/18755135/31546088-2d30b7c0-b022-11e7-9581-eb0612fd51bc.png)

Thanks.

**Comment by mhabsaoui** [comment]
I have also seen this error on Front page reload :

![image](https://user-images.githubusercontent.com/18755135/31548142-2e80ebe2-b02a-11e7-8aa4-fcfabcbdba4d.png)

![image](https://user-images.githubusercontent.com/18755135/31548188-4fd3aaf0-b02a-11e7-92af-66cde78a5d77.png)

Could it be PHP-Apache server related ??

Thanks.

**Comment by mhabsaoui** [comment]
I have checked the requirements for easyrdf on https://packagist.org/packages/easyrdf/easyrdf

Requires
    php: >=5.2.8          ==> php 7.X
    ext-mbstring: *       ==> extension activated in Dockerfile of php : RUN docker-php-ext-install gettext **mbstring**
    ext-pcre: *    ==>  activated by default in php

Also, I had cloned the latest stable branch v1.9-maintenance.

WTH...

**Comment by osma** [comment]
This looks like a socket related networking problem that is basically unrelated to Skosmos or EasyRdf. Search for the error "Cannot assign requested address" for hints. Are you using huge numbers of socket connections in Apache?

Are you using SELinux? Is it possible that Apache cannot connect to port 3030?

**Comment by mhabsaoui** [comment]
> This looks like a socket related networking problem that is basically unrelated to Skosmos or EasyRdf. Search for the error "Cannot assign requested address" for hints.

Thanks for your hint 👍 


> Are you using huge numbers of socket connections in Apache? Are you using SELinux? Is it possible that Apache cannot connect to port 3030?

I don't think so, I'm using official docker image "php:7.0-apache" to which I only add the required extensions (gettext mbstring, rewrite...). 

This container is exposed on "3030:3030" ports ==> As said, YAGUI Tool can perfectly connect to localhost Jena-fuseki TripleStore...

All my development is made on Ubuntu 16.04 LTS, so no SELinux.

Thanks.

**Comment by osma** [comment]
Is the Apache container allowed to make connections to the outside world? Since it's a different container than the Fuseki one, its localhost isn't the same thing. But I have very limited experience with Docker containers.

**Comment by mhabsaoui** [comment]
OK, by modifying the setting "localhost" to "fuseki" on skosmos app container => it seems better now 👍
==> This topic was helpful:  https://github.com/docker-library/php/issues/320

But now,  I've got 2 weird things more to solve: 

- the page showing the sparql endoint content is empty :/
- the names items with no values for language...

![image](https://user-images.githubusercontent.com/18755135/31577974-44244aae-b118-11e7-89e4-1e8bacf7b46e.png)


Thanks for help

**Comment by mhabsaoui** [comment]
Hmm, I've tried the Sparql request made from Skosmos under Yasgui and it seems not be validated
==> dc11 ??
![image](https://user-images.githubusercontent.com/18755135/31579441-c63692f4-b136-11e7-980e-1336552f1351.png)


If I remove that line => I get something but don't know if relevant...

![image](https://user-images.githubusercontent.com/18755135/31579462-344b24f8-b137-11e7-89d4-226fb3de465e.png)

**Comment by kinow** [comment]
I think that's because the dc11 namespace has not been defined.

**Comment by mhabsaoui** [comment]
@kinow Thanks. I've already tried it under Yasgui, adding that prefix makes the sparql requst validated.

OK. Then, I've added this xmlns into my .rdf file and re-uploaded it Fuseki triplestore

![image](https://user-images.githubusercontent.com/18755135/31583169-a567e79e-b195-11e7-9467-d98f58edfc3b.png)

==> the same behaviour : no data returned back from Fuseeki to Skosmos hierarchy view..

PS: As the sparql request is generated by Skosmos app, could it be any setting (for instance language) that maybe makes the Query mal-formed ?

Thanks.

**Comment by mhabsaoui** [comment]
If I check directly the source address (FROM) made by Skomos sparql query ==> 404

![image](https://user-images.githubusercontent.com/18755135/31583459-b9172f64-b19c-11e7-9412-5e8054fe5ee0.png)

On Yasgui, the same...
![image](https://user-images.githubusercontent.com/18755135/31583474-148c9d52-b19d-11e7-9a66-50cb6a12566a.png)

**Comment by mhabsaoui** [comment]
@osma I've downloaded ysa/yso .rdf+xml content

Just wondering how to replace parameters in vocabularies.ttl ??

> void:sparqlEndpoint <http://api.dev.finto.fi/sparql> ;
skosmos:sparqlGraph <http://www.yso.fi/onto/ysa/> .

void:sparqlEndpoint <http://fuseki:3030/ds/sparql> ;
skosmos:sparqlGraph <http://fuseki:3030/ds/data/onto/ysa/> .

Thanks

**Comment by osma** [comment]
@mhabsaoui I have difficulty following what you're trying to accomplish. My suggestion would be that you walk through InstallTutorial in the wiki, in a virtual machine. Then once you have it working you can start changing things one at a time. If things go wrong, it's easy to trace what caused it.

If you start with a completely custom configuration (e.g. both Fuseki abd Apache in Docker and your own vocabulary) it's much more difficult to debug problems.

Also I suggest that you ask for help on the skosmos-users Google group. You might find people there with similar setups. This issue tracker is meant for reporting bugs and it's followed by only a few devs, not the larger community of users.

vocabularies.ttl is just a text file you can edit.

**Comment by mhabsaoui** [comment]
@osma Thanks for your complete report.

> My suggestion would be that you walk through InstallTutorial in the wiki, in a virtual machine.
In fact, we had already got a version of Skosmos running in Docker containers following exactly the  InstallTutorial in the wiki. 

What I'm trying to accomplish is just to make the same, but this time by using already existing official docker images (official php-apache) and just adding necessary modules for php/apache...

Untill now, I solved the access bug to Fuseki on localhost (docker network), and now I'm just trying to understand why Skosmos is getting a "result: 0" on requests made to fuseki.

> But looking at the SPARQL queries you've tried, it seems that you've perhaps mixed up the graph URI with the SPARQL HTTP Graph Store endpoint URI (often something that ends with /data).
If you prefer to use the default graph in Fuseki, then simply omit the skosmos:sparqlGraph setting. That works, but you're limited to a single vocabulary per Fuseki dataset.

About graph/'SPARQL HTTP Graph Store endpoint'  URIs, my vocabulary has a named sparqlGraph (declared in vocabularies.ttl as following). And I upload the .rdf file to Fuseki througn admin interfaçe.

> :Biodiversité_ARK a skosmos:Vocabulary, void:Dataset ;
        dc:title "Biodiversity_ark"@en;
        dc:title "Biodiversité_ark"@fr;
        dc:subject :cat_bio;
        skosmos:language  "en","fr";
        skosmos:defaultLanguage "en";
    	void:uriSpace "http://dx.doi.org/10.5072/vocabs/biodiversite";
        skosmos:showTopConcepts "true";
        skosmos:loadExternalResources "false";
        void:sparqlEndpoint <http://fuseki:3030/ds/sparql> ;
        skosmos:sparqlGraph <http://fuseki:3030/ds/data/Biodiversite_ark> .

So as you can see above, if I'm not wrong:
=> graph URI : http://fuseki:3030/ds/data/Biodiversite_ark
=> Graph Store endpoint URI : http://fuseki:3030/ds/sparql

Thanks.

**Comment by osma** [comment]
@mhabsaoui Right. Your graph URI was confusingly close to the Graph Store endpoint URI.

Are you sure you used exactly this graph URI when you uploaded your data to Fuseki?

I would advise you to upload a vocabulary that is known to work in Skosmos - for example STW Thesaurus is a good test case - into your Fuseki. Use the graph URI and vocabularies.ttl snippet you can find in the [InstallTutorial](https://github.com/NatLibFi/Skosmos/wiki/InstallTutorial), except you  have to adjust your SPARQL endpoint URI (fuseki instead of localhost).

Since you are getting entries in the Fuseki log, it seems that the connection between Apache/PHP/Skosmos/EasyRdf and Fuseki is now working properly. All you should need now is to make sure the graph URIs match.

**Comment by mhabsaoui** [comment]
@osma Yay, your hints did the trick. In fact, when uploading .rdf file I was missing setting the Destination graph name value, letting it to default... 
![image](https://user-images.githubusercontent.com/18755135/31596081-65ddf28e-b240-11e7-8c45-60c643ab8959.png)

With graph naming, it shows all well 👍 

![image](https://user-images.githubusercontent.com/18755135/31596091-80994182-b240-11e7-979a-d12ddd60cf76.png)


Well thanks for your patient support. And if you're interested in a Skosmos-docker or a Skosmos-Fuseki-docker flavor project for the community let me know.

Cheers.

**Comment by osma** [comment]
@mhabsaoui You can use the default dataset/TDB config, but it doesn't have a text index. With larger vocabularies (more than a few thousand concepts), a text index is in practice necessary for good performance.

I'm glad you got it working! One thing that would help is writing a tutorial (in the style of InstallTutorial) for how to use Skosmos with Docker. I think many people are starting to use containers, especially for Fuseki, which is a bit of a hassle to install natively (as shown in InstallTutorial). This could be a page in the Skosmos wiki. What do you think?

**Comment by mhabsaoui** [comment]
Hi,
Yep very good idea, letting those willing to start new fresh and fast hacks through docker containers.

Do I have to make a pull-request, asa I made the Docker way of Tutorial or what ?

**Comment by osma** [comment]
I think the wiki here on GitHub allows anyone to edit pages. You could try creating a page for your tutorial. No need for pull requests, those are used for code contributions.
