### ISSUE TITLE
Make top ConceptSchemes in REST API an Array and not a single value

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#636]
As described in  #634, the query in `GenericSparql->generateQueryConceptSchemesQuery()` makes the assumption that a concept can have at most only one `skos:topConceptOf`.
This needs to be changed if Skosmos is used to display concepts that do belong to multiple concept schemes at the same time.
Note that this will also impact the API format : "top" will hold an array and not a single value anymore.

**Comment by tfrancart** [comment]
Further note : this may have side effects on `GenericSparql->queryTopConcepts`, I am not exactly sure.

**Comment by osma** [comment]
I'm a bit nervous about changing the REST API in an incompatible way, even though it seems necessary in the scenario you mention. I wonder if there's a way of avoiding that. If not, it at least needs to be well documented in the release notes.

**Comment by tfrancart** [comment]
We could make a different JSON key (e.g. "tops" instead of "top") to avoid making backward-incompatible changes ? How does that sound ?

**Comment by osma** [comment]
Right, I was thinking something along those lines. In the JSON-LD context, both keys would be mapped to `skos:topConceptOf`. If we could do it like that, then we wouldn't break the "API contract". But ideally there should be a clear definition of which concept scheme (if there are many) is used for the `top` key. Maybe the default concept scheme of the vocabulary?

**Comment by tfrancart** [comment]
Suggestion : 

1. Use the default concept scheme of the vocabulary if it is provided
2. If none is provided, sort alphabetically the ConceptSchemes URIs and take the first one, in order to garantee that the API will always return a consistent result

**Comment by osma** [comment]
Yes, sounds good. That's basically what Skosmos already does if no default concept scheme is set and there are several in the vocabulary - it tries to pick one using a deterministic sort order.
