### ISSUE TITLE
The "filter by subvocabulary" dropdown in advanced search screen shows URIs instead of labels

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#639]
## At which URL did you encounter the problem?

http://vocabs.sparna.fr/skosmos/irstea-conceptSchemes/fr/search?clang=fr&q=

## What steps will reproduce the problem?
1. Go to provided URL
2. Open the first drop-down "Par sous-vocabulaire" ("By subvocabulary") : the dropdown shows the URI of ConceptSchemes

## What is the expected output? What do you see instead?

The dropdown contains the URI of ConceptSchemes, I would expect to see their labels instead.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by osma** [comment]
Right, thanks for reporting.

Seems to affect also our vocabularies, e.g.
http://finto.fi/iptc/en/search?clang=en&q=100
http://finto.fi/ptvl/fi/search?clang=fi&q=amm
