### ISSUE TITLE
Return altLabels too for REST API  "/vocid/label"

### ISSUE THREAD

**Issue by DGmaps** [NatLibFi/Skosmos#640]
Hi,

I see that in the context of 'Concept-specific methods'  the "/vocid/label" allows you to retrieve the prefLabel of a term starting from the uri.

Is it possible to enrich the response in order to retrieve also the altLabel?

Maybe a query that allows to return prefLabel and altLable from the uri already exists, but I did not find it.

Could you please help?

Thank you

**Comment by osma** [comment]
There is a `data` method that returns all the data for a concept, including both `prefLabel` and `altLabel` but also a lot of other information. Maybe that would solve your problem?

But returning both `prefLabel` and `altLabel`s for the `label` method seems possible too, if you really need it.

**Comment by DGmaps** [comment]
Hi Osma,

thanks for your prompt reply.

As you said, 'data' method allows to return altLabel, but also a lot of other information that make the response not easy to read. It returns an array of values, and just one of them is the real data set that I need. The others are terms 'related' to the target uri.
If there is a way to filter data 'related' to the target uri, in order to exclude them from the response it could be fine, but until now I have not found a proper filter.

Indeed what I need is a simple response like the one provided by 'label'.

Could you please help me to understand how to obtain the altLabel in addition to prefLabel when I call 'label' ?

**Comment by osma** [comment]
Getting the altLabel using the `label` method is not supported at the moment. It should be rather easy to add that functionality. For now we are filing this as an enhancement proposal.
