### ISSUE TITLE
Upgrade EasyRdf

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#643]
There are some changes in EasyRdf `0.10.0-alpha.1` (already a couple of years old), for example content negotiation fixes that should help fix #632.

The challenge is that all EasyRdf classes have been renamed since `0.9.x` so a lot of places in the code need fixing.

**Comment by tfrancart** [comment]
Osma, a great thanks for this migration on the latest EasyRdf.
I have tested against a Virtuoso endpoint, and now the CONSTRUCT query works fine.
I also have tested quickly on a Fuseki endpoint, and everything seems to work fine.

I am now facing another issue with some SPARQL queries using transitive operators that Virtuoso does not like. I will open a separate issue for this.

**Comment by osma** [comment]
Merged the upgrade branch.
