### ISSUE TITLE
URIs with pattern "<void:uriSpace>/something/ID" do not work properly in tree

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#652]
1. void:uriSpace is specified as http://exemple.com/thesaurus/.
1. SKOS data contains collections with URI http://exemple.com/thesaurus/collection/c1
1. In the "Groups" tab, Skosmos generates a link "http://myserver.fr/skosmos/fr/page/collection/c1, which do no work.

In hierarchy.js::getConceptHref(), an extra test should be added to check if the end of the URI does not contain additionnal slashes. If this is the case, default to a "...?uri=..." link.

I will propose a PR.

**Comment by osma** [comment]
Thanks, good catch!
