### ISSUE TITLE
Add a copy to clipboard button

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#661]
## At which URL did you encounter the problem?
Any concept page.

## What is the expected output? What do you see instead?
It would be nice to be able to copy preferred labels or URIs with a single click. There is now a single click highlight functionality, but the user still needs to manually copy the highlighted content to the clipboard.

This could be solved by using something like: https://clipboardjs.com/ or http://www.jstips.co/en/javascript/copy-to-clipboard/

**Comment by kinow** [comment]
Tested on dev.finto.fi/geo/fi/page/GTK2015ID5, and the clipboard icon is working fine on Firefox and Chrome. Tested using Ubuntu Linux LTS. I think this can be closed? 🎉

**Comment by henriyli** [comment]
I agree. Thanks @kinow !
