### ISSUE TITLE
Vocabulary-agnostic page URL

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#668]
We have a situation where Concepts from multiple Vocabularies share the same URI pattern.

Specifically, the same URI pattern "/legal-subject/..." is shared between vocabularies with IDs "legal-subject-theme", "legal-subject-place", "legal-subject-organisation". See http://localhost/tfrancart-skosmos/legal-subject-organisation/fr/page/682, http://localhost/tfrancart-skosmos/legal-subject-theme/fr/page/28 and http://localhost/tfrancart-skosmos/legal-subject-place/fr/page/310.

This makes it impossible to write redirect at the web server level, to redirect from Concept URIs to their corresponding URL in Skosmos, since we don't know in which vocabulary the concept is defined.

Do you think it would be possible to have a vocabulary agnostic page URL in Skosmos (e.g. `.../skosmos/page?uri=<concept-uri>`, that would 1. find the vocabulary in which the concept URI is defined, based on Model::guessVocabularyFromURI() and 2. redirect to the proper vocabulary page of the concept ?

Something like adding an additionnal "elseif" here : https://github.com/NatLibFi/Skosmos/blob/master/index.php#L45

Does this make sense ?
(I will propose a PR if you agree on the idea)

**Comment by osma** [comment]
Does the entity URL help you at all? See https://github.com/NatLibFi/Skosmos/wiki/ServingLinkedData

**Comment by tfrancart** [comment]
Magic. Exactly what I need, and works perfectly; I missed this in the documentation.
Thanks !
