### ISSUE TITLE
On concept page, ordering of narrower concepts is not correct wrt accented characters

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#679]
## At which URL did you encounter the problem?

http://erato.sparna.fr/scolomfr/scolomfr-voc-000-3-2/fr/page/?uri=http%3A%2F%2Fdata.education.fr%2Fvoc%2Fscolomfr%2Fconcept%2Fscolomfr-voc-015-num-099

## What steps will reproduce the problem?
1. Go to above URL
2. In the narrowers section, narrowers starting with "é" are at the end of the list

## What is the expected output? What do you see instead?

narrowers starting with "é" should be placed after narrower starting with "e".

In `ConceptProperty::sortValues()`, strcoll should be used instead of strnatcasecmp in combination with lowercasing to have case-insensitive + locale-based ordering.

PR to follow.

**Comment by osma** [comment]
This caused a regression in PTVL. Previously the classes (concepts) in the classification were ordered numerically by notation code, e.g. P1 comes first and P10 comes after P9:
http://finto.fi/ptvl/fi/page/?uri=http://urn.fi/URN:NBN:fi:au:ptvl:

But after this fix, P10 comes first and P1 is after P19:
http://dev.finto.fi/ptvl/fi/page/?uri=http://urn.fi/URN:NBN:fi:au:ptvl: 

I'm not sure if it's possible to do a correct sort in both cases (accented characters + natural sort for numbers).

**Comment by osma** [comment]
I made a separate issue for the PTVL problem, so this one can be closed.
