### ISSUE TITLE
Document skosmos:showDeprecated in wiki

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#681]
## At which URL did you encounter the problem?

https://github.com/NatLibFi/Skosmos/wiki/Vocabularies

## What steps will reproduce the problem?
Missing documentation for skosmos:showDeprecated
Proposed definition :

`Set to true if you want deprecated concepts to be shown in alphabetical listing, hierarchical tree and full-text search results. See The data model page[https://github.com/NatLibFi/Skosmos/wiki/Data-Model#deprecated-concepts] for more information`

Also, at https://github.com/NatLibFi/Skosmos/wiki/Data-Model#deprecated-concepts, that sentence :

`Deprecated concepts will not be visible in the alphabetical listing, in the hierarchical view, and cannot be found with the search.`

Should be changed to

`Deprecated concepts will not be visible in the alphabetical listing, in the hierarchical view, and cannot be found with the search, unless the option skosmos:showDeprecated is set to true in the vocabularies configuration file.`

**Comment by henriyli** [comment]
I updated the documentation with the changes you suggested. Thanks!
