### ISSUE TITLE
Vocabulary page does not display properly on mobile screens

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#691]
On mobile screen, Safari, the right of the vocabulary page is not visible. See screenshot below.

![skosmos-vocabulaires](https://user-images.githubusercontent.com/2728945/35386863-d32abc64-01cd-11e8-8ac1-21d706583a47.jpg)

It works fine when I use Firefox on a desktop computer and I resize the screen.

**Comment by tfrancart** [comment]
(Screenshot not taken from Safari, most probably Chrome, but I reproduced it on Safari)

**Comment by henriyli** [comment]
It's hopefully bit better now. A smarter solution would be to rewrite the template without a table structure in a similar style as the concept page.

**Comment by kinow** [comment]
Having a look at the latest code, and in Firefox with the mobile mode on (i.e. CTRL + M) I can see the contents in the page fine. But the menu is still a bit confusing. Probably that hamburger icon trick from Bootstrap would be enough for that. Not sure if there's anything else that needs tweaking for mobile.

Perhaps the issue could be renamed to cover all mobile navigation of Skosmos, or closed if it fixed the issue reported, and then we can open a new issue.

![image](https://user-images.githubusercontent.com/304786/35776798-e4764488-0a07-11e8-85fa-d09ca1e51e7d.png)

**Comment by osma** [comment]
Closing as the immediate issue was fixed. Please open new issues for further improvements.
