### ISSUE TITLE
Navigation links do not work on a search result page when the SPARQL query returns a 404 error

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#693]
## At which URL did you encounter the problem?

http://erato.sparna.fr/authority/legal-subject-theme/fr/search?clang=fr&q=this.returns.no.results

## What steps will reproduce the problem?
1. Go to http://erato.sparna.fr/authority
2. Select any vocabulary
3. Make a full text search for a dummy keyword that returns no results
4. Click on any navigation link in the navigation bar (Vocabularies, About, Feedback)

## What is the expected output? What do you see instead?

1.
The links start with "/", like "/about", and are not pointing to the correct path. They sould be prepended by the request language, I think.
It works when the search return some results : http://erato.sparna.fr/authority/legal-subject-theme/fr/search?clang=fr&q=service

However I don't have the same behavior when looking at other skosmos deployments, like vocabularies.unesco.org or finto.fi.

What am I missing ?

**Comment by henriyli** [comment]
Hmm interesting, I think you are correct. The navigation links are indeed missing the request language, which causes the links to break down.

I'll try to figure out why the request languages are missing.

**Comment by henriyli** [comment]
The "Pas de vocabulaires sur le serveur !" text makes me wonder if the vocabularies.ttl parsing fails for some reason. It also seems that the Request object returns "" when language, content language or the vocabulary getters are used.

Are there any clues in the apache error log?

**Comment by tfrancart** [comment]
Actually I am debugging this right now, it seems a SPARQL query in the search fails, which actually causes a 404 error to be returned : https://github.com/NatLibFi/Skosmos/blob/master/controller/WebController.php#L437
Yet however the normal search result template is displayed, but not all the required request properties are present, like the language.

**Comment by osma** [comment]
@tfrancart Is this still a problem or can the issue be closed?

**Comment by tfrancart** [comment]
This should be rephrased as : "Navigation links do not work on a search result page when the SPARQL query returns a 404 error". This is somehow related to the line pointed in the previous comment.
