### ISSUE TITLE
SPARQL search query is referring to ?match in GROUP BY and ORDER BY, while ?match is not in the SELECT clause

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#694]
I can't be 100% sure, but :

At https://github.com/NatLibFi/Skosmos/blob/master/model/sparql/GenericSparql.php#L1015, the GROUP BY clause is grouping on ?match, while ?match is not a variable in the SELECT clause.

At https://github.com/NatLibFi/Skosmos/blob/master/model/sparql/GenericSparql.php#L1016, the ORDER BY clause is ordering on ?match, while ?match is not a variable in the SELECT clause.

**Comment by osma** [comment]
I think `?match` should be coming from the inner query generated by `generateConceptSearchQueryInner`. But need to verify.

Did you find a solution by yourself?

**Comment by osma** [comment]
`?match` is set in a `BIND` statement a dozen or so lines above the `GROUP BY` and `ORDER BY`, currently on line 1008: https://github.com/NatLibFi/Skosmos/blob/master/model/sparql/GenericSparql.php#L1008

Closing the issue as there appears to be no problem here.
