### ISSUE TITLE
EasyRdf_Http_Client only supports the 'http' and 'https' schemes.

### ISSUE THREAD

**Issue by mhabsaoui** [NatLibFi/Skosmos#698]
Hi,

I had a weird issue:

###  At which URL did you encounter the problem?
http://localhost:1888/skosmos/fr/search?clang=fr&q=xxx&vocabs=

###  What steps will reproduce the problem?
1. being on the main vocabularies page
2.  write search term (**existing or not !**)
3. click search button

###  What is the expected output? 
![capture du 2018-02-01 16-45-06](https://user-images.githubusercontent.com/18755135/35687520-48bb15f4-076f-11e8-9c80-596383d3e4c3.png)

###  What do you see instead?
![capture du 2018-02-01 16-41-24](https://user-images.githubusercontent.com/18755135/35687495-30a95db8-076f-11e8-8d3d-6fc24897e7fd.png)

In browser console :  404 Not Found

### What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox, Chrome

Thanks.

**Comment by osma** [comment]
Can you provide more details? What is your vocabularies.ttl and config.inc configuration? Is there a more specific error message in the Apache error.log?

**Comment by mhabsaoui** [comment]
Hi @osma 

And thanks for support ! I was on on another project, and now back on this one with Skosmos...

Well about details on error messages in the Apache error.log => nothing special

> root@ffc6bd509be5:/skosmos# more /var/log/apache2/error.log 
[Thu Feb 01 15:06:00.966211 2018] [mpm_prefork:notice] [pid 46] AH00163: Apache/
2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.22 configured -- resuming normal operations
[Thu Feb 01 15:06:00.966398 2018] [core:notice] [pid 46] AH00094: Command line: 
'/usr/sbin/apache2'


PS: I have a fuseki server with one dataset having No vocabularies at all (empty just for debugging...)

Thanks.

**Comment by osma** [comment]
This error message is triggered when EasyRdf is asked to retrieve a URL that's not `http://` or `https://`. Skosmos uses EasyRdf_Http_Client for two main cases: 1) performing SPARQL queries, and 2) retrieving Linked Data from resources that have been linked to using SKOS mapping relationships. Since this was a global search, I think the problem is with SPARQL.

What's your DEFAULT_ENDPOINT setting in config.inc? That's where global searches are targeted.

**Comment by mhabsaoui** [comment]
Perfect @osma 👍 

We had this in config.inc.template (yes we use a template to set @FUSEKI_QUADS@ dynamically with a 'sed -e ' command during the Docker building of Skosmos in order to be able to deloy skosmos on any host name... )  =>   `define("DEFAULT_ENDPOINT", "@FUSEKI_QUADS@/sparql");`

So the problem came from my partner who used the wrong varibale name...  Solved and of course 👍 


PS1: I'll need your support for a last point : Best practice to Create (pass an assembler/config.ttl to automatically initialize a TDB) / Backup (use of tdbdump/tdbbackup CLI commands to trigger TDB dumps) / Restore on a Fuseki server  ;-)  (already started [here](https://github.com/stain/jena-docker/issues/6) and [here](https://github.com/blankdots/docker-SemanticWebApps/issues/5)). Thanks a lot.

PS2:  You **absolutely** deserve the Docker Section in Skosmos tutorial. I'll take care of it as I am on it 💯
