### ISSUE TITLE
REST API not returning entire vocabulary, despite this being indicated in the docs

### ISSUE THREAD

**Issue by paulwalk** [NatLibFi/Skosmos#702]
According to the [REST API docs](http://api.finto.fi/doc/#!/Vocabulary-specific_methods/get_vocid_data), this URL:
/rest/v1/<VOCAB_ID>/data?format=text/turtle

should return the whole vocabulary

> When no uri parameter is given, the whole vocabulary is returned instead.

However, this actually returns a 404 with the explanation:

> 404 Not Found : No download source URL known for vocabulary <VOCAB_ID>

Having had a look at the sources, I can see that this is returned when there is no URI specified:

```
private function redirectToVocabData($request) {
        $urls = $request->getVocab()->getConfig()->getDataURLs();
        if (sizeof($urls) == 0) {
            $vocid = $request->getVocab()->getId();
            return $this->returnError('404', 'Not Found', "No download source URL known for vocabulary $vocid");
        }
...
```

I'm actually interested in figuring out how to return the whole vocabulary in a machine-readable format, which seems surprisingly difficult to do?

**Comment by osma** [comment]
Skosmos doesn't serve the full data by itself. The general idea is that you should put the full vocabulary data so it's accessible from some URL, and point to that URL using `void:dataDump` in `vocabularies.ttl`. There can be several and Skosmos recognizes the file extension from the URL (I know, ugly...) so it knows how to serve both Turtle and RDF/XML and redirect appropriately.

**Comment by paulwalk** [comment]
Ah - that makes sense! Thanks for explaining - it wasn't entirely clear from the docs :-)
