### ISSUE TITLE
skos:members visible in skos:Collection concept view

### ISSUE THREAD

**Issue by tpalonen** [NatLibFi/Skosmos#705]
Concepts that are members of a skos:Collection are not shown in the concept view of that skos:Collection and are only visible in the hierarchy tab when viewing a skos:Collection. Showing them in the concept view would make them a little easier to browse. 

Cf. Narrower concepts and related concepts are shown in a skos:Concept's concept view so this suggested addition would be in accordance with that.

**Comment by jarmosaarikko** [comment]
the inverse of skos:member is already shown on the member's concept view with title "BELONGS TO GROUP".

**Comment by osma** [comment]
The group members used to be visible (a long time ago) but we felt it was confusing to show them twice on the same page, both in the hierarchy view and in the main concept view.

**Comment by MikkoAleksanteri** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
