### ISSUE TITLE
Missing UI translation for skos:relatedMatch property

### ISSUE THREAD

**Issue by henriyli** [NatLibFi/Skosmos#707]
## At which URL did you encounter the problem?

http://finto.fi/yse/fi/page/Y505846

## What steps will reproduce the problem?

1. Open the concept page

## What is the expected output? What do you see instead?

Expected to see skos:relatedMatch property values that the concept data has. I'm not seeing those since the property skos:relatedMatch does not have a UI label/translation.

**Comment by osma** [comment]
Nowadays the translations exist, but the Finnish one is both wrong and misspelled: "ASSOSIATIIVISET KÄSITTET"

**Comment by osma** [comment]
The current Swedish label is "RELATERADE MOTSVARANDE BEGREPP"
The current English label is "RELATED MATCHING CONCEPTS"

**Comment by MikkoAleksanteri** [comment]
Maybe "LIITTYVÄ KÄSITE" or "LIITTYVÄ KÄSITE TOISESSA SANASTOSSA"

**Comment by MikkoAleksanteri** [comment]
Best translations according to the Finto-team:
fi: "assosiatiivinen käsite toisessa sanastossa" 
sv: "relaterat begrepp i annan vokabulär"
