### ISSUE TITLE
Groups tab shows concepts from the same vocab to have URIs like they are from other vocabularies

### ISSUE THREAD

**Issue by kouralex** [NatLibFi/Skosmos#724]
## At which URL did you encounter the problem?
http://finto.fi/juho/fi/page/p771
## What steps will reproduce the problem?
1. Go to the link provided above (using the Finnish UI)
2. Select "alueellinen yhteistyö" from the Groups tab

## What is the expected output? What do you see instead?
I'd expect the hover URI and address bar URI to be in the form consistent with the vocabulary. Instead, it is now referred to as if it was from another vocab.

Example:
http://finto.fi/juho/fi/page/?uri=http%3A%2F%2Fwww.yso.fi%2Fonto%2Fjuho%2Fp6048
instead of
http://www.yso.fi/onto/juho/p6048
## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by kouralex** [comment]
Actually, now that I noticed the PTO ontology where the URIs are not bound to the http://yso.fi/onto/* naming convention, I understand that the current functionality is a good default and works for every kind of URI. 

However, I think we should, when applicable, try to form consistent URIs within a vocabulary (that is, in the example provided).

**Comment by osma** [comment]
Yes, we should try to use the short form when possible. In this case the link is generated via JavaScript; the code should check whether the URI is within the current `uriSpace` and use the short form if it is.

**Comment by osma** [comment]
In this case the short form of the link should be http://finto.fi/juho/fi/page/p6048
