### ISSUE TITLE
Update documentation for InstallationTutorial

### ISSUE THREAD

**Issue by kouralex** [NatLibFi/Skosmos#736]
Need to update InstallTutorial wiki page as well as check that other wiki pages are up-to-date.

**Comment by osma** [comment]
The docs could of course be updated any time, but it would be especially good to do this at the time of the 2.0 release. The base system should be Ubuntu 16.04 (with systemd) instead of the old 14.04.

**Comment by kinow** [comment]
Maybe we could use 18.04 as base system, as it's now the new [LTS Release](https://wiki.ubuntu.com/Releases)

**Comment by joelit** [comment]
Updated and tested the installation guide to reflect changes for Ubuntu 18.04 running Skosmos 2.2, Jena 3.13.1 & Varnish 5.2.1.
