### ISSUE TITLE
Error when typing quotation mark in the search box

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Skosmos#742]
## At which URL did you encounter the problem?
finto.fi (frontpage or any vocabulary page)

## What steps will reproduce the problem?
1. type "-mark in the seach box and press enter
2.
3.

## What do you see?
When using the frontpage searchbox: _404 Error: The page /search/ cannot be found._
When using search box in vocabulary like YSO: Service jumps to frontpage and gives the notice: _Ei sanastoja palvelimella! Ei hakutuloksia._

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by osma** [comment]
This is similar to #763 and should be fixed by PR #764.

**Comment by osma** [comment]
FIxed by PR #764
