### ISSUE TITLE
concept not loading

### ISSUE THREAD

**Issue by aturbati** [NatLibFi/Skosmos#744]
## What steps will reproduce the problem?
1. install Skosmos  v1.10-maintenance
2. download agrovoc from https://bitbucket.org/aims-fao/agrovoc/downloads/agrovoc_2018-03-01_ld.nt.zip
3. try open the first concept in A: A horizons (which is c_47a98f68)

## What is the expected output? What do you see instead?
all concept information as it done with almost all other concepts (the same problem is with other concepts as well), nothing appears, it keeps loading. With v1.09-maintenance there seems to be no error.
The logger has this error:

Uncaught Exception: Invalid
constructor parameter given to DataObject. in /home/agrovoc/skosmos/skosmos_agrovoc/Skosmos/model/DataObject.php:29\nStack trace:\n#0 /home/agrovoc/skosmos/skosmos_agrovoc/Skosmos/model/VocabularyDataObject.php(22): DataObject->__construct(Object(EasyRdf\\Literal\\DateTime), NULL)\n#1 /home/agrovoc/skosmos/skosmos_agrovoc/Skosmos/model/ConceptPropertyValueLiteral.php(15): VocabularyDataObject->__construct(Object(EasyRdf\\Literal\\DateTime), 'dc:created', NULL)\n#2 /home/agrovoc/skosmos/skosmos_agrovoc/Skosmos/model/ConceptPropertyValue.php(127): ConceptPropertyValueLiteral->__construct(Object(EasyRdf\\Literal\\DateTime), 'dc:created')\n#3 /home/agrovoc/skosmos/skosmos_agrovoc/Skosmos/vendor/twig/twig/lib/Twig/Template.php(677): ConceptPropertyValue->getReifiedPropertyValues()\n#4 /tmp/skosmos-template-cache/8a/8a4ec420e321029f4eb58ad08f05852f0e69f774e03763e6be914b72aa0e50f4.php(429): Twig_Template->getAttribute(Object(ConceptPropertyValue), 'reifiedProperty...', Array)\n#5 /home/agrovoc/skosmos in /home/agrovoc/skosmos/skosmos_agrovoc/Skosmos/view/concept-shared.twig on line 84, referer:

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox, Chrome

**Comment by osma** [comment]
@aturbati Thanks for the report. The bug should now be fixed both on the master branch and the v1.10-maintenance branch. Can you please verify?

**Comment by aturbati** [comment]
@osma Now Skosmos seems to be able to load all concepts. Thank you for the fix

**Comment by osma** [comment]
@aturbati Thanks for confirming!
