### ISSUE TITLE
Missing language tags for concept labels on concept page

### ISSUE THREAD

**Issue by kouralex** [NatLibFi/Skosmos#750]
## At which URL did you encounter the problem?
http://finto.fi/koko/en/page/p32712
## What steps will reproduce the problem?
1. Go to above link
2. Look at "Narrower concepts"

## What is the expected output? What do you see instead?
I would expect to see (fi) after Finnish terms. The same problem arises also for other matches (skos:broaderMatch etc.).

**Comment by osma** [comment]
Cannot replicate
