### ISSUE TITLE
Default Skosmos language based on locale ?

### ISSUE THREAD

**Issue by mhabsaoui** [NatLibFi/Skosmos#753]
## At which URL did you encounter the problem?
http://www.yso.fi/onto/allars/Y51873

## What steps will reproduce the problem?
1. open a new **private** navigation browser tab (simulate first acces on URL)
2. paste and go to the URL
3. check which default language is set for Skosmos

## What is the expected output? 
User OS / Browser locale language set by default

## What do you see instead?
default language set by Skosmos ??

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox, Chrome

![capture du 2018-04-03 16-40-12](https://user-images.githubusercontent.com/18755135/38256451-9736c95c-375e-11e8-8483-b77dc6105586.png)

On left window, Skosmos with user preferred language already previously set. 
On right one, Skosmos with default language set automatically on first time site acess (following which rules ?)...

How does Skosmos deals with locale language detection on first site acces : 

- is it the OS' language locale (On Windows, setlocale(LC_ALL, '') sets the locale names from the system's regional/language settings (accessible via Control Panel). ) 

- or the web Browser (accept-language) once that is taken into account ??

PS: I understand that the [setLocale](http://php.net/manual/en/function.setlocale.php) php command is used to generate [locale/language](https://github.com/NatLibFi/Skosmos/blob/6eab8899d90c1e697fb6fb673eb9464879a116fc/controller/Controller.php#L52)  from an array previously populated from config.inc ($this->model->getConfig()->getLanguages() as $langcode => $locale)

Cheers.

**Comment by osma** [comment]
The logic is implemented and documented with comments here in the guessLanguage function:
https://github.com/NatLibFi/Skosmos/blob/master/controller/WebController.php#L130

In the case of Allärs that you chose as example, the default (and only) language of the vocabulary is Swedish, so the UI also defaults to Swedish.

If the first access is for the front page or some other non-vocabulary-specific page then the default is to use the web browser language setting (Accept-Language).
