### ISSUE TITLE
Warning: Unsupported language 'en', not setting locale in /var/www/html/Skosmos/controller/Controller.php on line 54

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#772]
## At which URL did you encounter the problem?
http://localhost/Skosmos/en/

## What steps will reproduce the problem?
1. Open Skosmos front page

## What is the expected output? What do you see instead?

The vocabularies are not displayed normally. Instead I get the error:

( ! ) Warning: Unsupported language 'en', not setting locale in /var/www/html/Skosmos/controller/Controller.php on line 54
--

1 | 0.0000 | 361456 | {main}(  ) | .../index.php:0
2 | 0.0043 | 822136 | WebController->invokeGenericErrorPage(  ) | .../index.php:54
3 | 0.0043 | 822136 | Controller->setLanguageProperties(  ) | .../WebController.php:581
4 | 0.0043 | 822216 | trigger_error (  ) | .../Controller.php:54

Seems to be a consequence of PR #769, something about the locale configuration is not working. FYI @kinow, I'm trying to figure out and fix this.

**Comment by osma** [comment]
It seems related to the `emptyns` prefix trick...I think something more robust is needed here.

**Comment by osma** [comment]
I decided to use `rdfs:label` and `rdf:value` for the properties, instead of relying on `emptyns`.

**Comment by kinow** [comment]
Thanks for fixing it, and sorry for forgetting to mentionabout the `emptyns`. Calling it a trick is kindness, it was a - not very elegant - hack, that deserved at least a `// TODO`.
