### ISSUE TITLE
Accidental selection from autocomplete list using mouse + enter press

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#773]
## At which URL did you encounter the problem?
http://dev.finto.fi/allars/sv/

## What steps will reproduce the problem?
1. Go to Allärs home page (or any other vocabulary)
2. Make sure the search box has focus
3. Position the mouse below the search box
4. Enter "kaffe"
5. Wait for the autocomplete suggestions to appear
6. Press enter

## What is the expected output? What do you see instead?

Expected to get the search results page for "kaffe" showing 7 results.
Instead going directly to one of the suggested concepts, e.g. "kaffekokare" (depending on mouse position)

![peek 2018-06-06 16-46](https://user-images.githubusercontent.com/1132830/41042547-9bd16494-69aa-11e8-9ba7-21ee0209ac48.gif)

The same problem can also be found in Finna.fi, but for example Google search is immune (if you press enter, you will get search results for the word you actually typed into the box, not the suggestion the mouse happens to hover over)

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

Firefox

**Comment by osma** [comment]
It's possible that this is a problem with the typeahead.js widget we are using, which unfortunately is no longer maintained.

**Comment by kinow** [comment]
I think this could be a feature... from what I can tell, there is one function used when the mouse is over, and also when you press key up/down. Disabling one may disable the other as well.

Issue in the library related to this: https://github.com/twitter/typeahead.js/issues/884

side note: if you read typeaheads code, search _hacks. Must be quite hard to maintain a JS library.

**Comment by kinow** [comment]
Thought also about finding a workaround in the current version, but this could mean that once someone else upgraded this library, then they would have to upgrade & try these other workarounds anyway.

Does this seem like a good way to fix this issue @osma , or do you have any other idea?

**Comment by kinow** [comment]
> If the upgrade turns out to be a lot of work, we may have to reconsider.

+1
