### ISSUE TITLE
Update skosmos-docker installation doc to reflect #769

### ISSUE THREAD

**Issue by rowanbrownlee** [NatLibFi/Skosmos#777]
In skosmos-docker installation, config.ttl now replaces vocabularies.ttl & config.inc.  (#769).  [Skosmos-docker installation tutorial](https://github.com/NatLibFi/Skosmos/wiki/Install-Skosmos-with-Fuseki-in-Docker) refers to config.inc.dist & vocabularies.ttl

Unsure whether this issue is covered by #736

**Comment by kinow** [comment]
I'd say this is covered by #736, but thanks for the reminder, had slipped my mind updating the documentation. Will try to work on it in the next days 👍

**Comment by osma** [comment]
Not critical for the 2.0 release as it doesn't affect the codebase, only the wiki

**Comment by kinow** [comment]
+1 @osma , and easier to do once we have everything sorted out with the new config, migration tools, and everything ready for 2.0 (otherwise it may need another update...)

**Comment by osma** [comment]
@kinow I think this could be finished off now that 2.x has been out for some time and the new config format seems stable?

**Comment by kinow** [comment]
Yes, that's right. I will try to update it and send the pull request tomorrow :)

**Comment by kinow** [comment]
Done!

https://github.com/NatLibFi/Skosmos/wiki/Install-Skosmos-with-Fuseki-in-Docker/_compare/e1237ce2c9c16105e5e4967305f587437400aaf7

**Comment by osma** [comment]
Great work @kinow!
