### ISSUE TITLE
Skosmos not showing SKOS concepts of my vocabularies

### ISSUE THREAD

**Issue by charlycou** [NatLibFi/Skosmos#779]
## At which URL did you encounter the problem?
http://localhost/Skosmos/en/

## What steps will reproduce the problem?
1. Install Skosmos using [InstallTutorial](https://github.com/NatLibFi/Skosmos/wiki/InstallTutorial) and upload SKOS vocabularies. stw.ttl following the InstallTutorial and theia_categories.ttl. Both files are attached.
2. Update vocabularies.ttl:
```
@prefix void: <http://rdfs.org/ns/void#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix dc: <http://purl.org/dc/terms/> .
@prefix foaf: <http://xmlns.com/foaf/0.1/> .
@prefix wv: <http://vocab.org/waiver/terms/norms> .        
@prefix sd: <http://www.w3.org/ns/sparql-service-description#> .
@prefix skos: <http://www.w3.org/2004/02/skos/core#> .
@prefix skosmos: <http://purl.org/net/skosmos#> .
@prefix isothes: <http://purl.org/iso25964/skos-thes#> .
@prefix : <#> .


:categories_theia a skosmos:Vocabulary, void:Dataset ;
	dc:title "Categories of Theia in-situ information system"@en;
	void:uriSpace "http://in-situ.theia-land.fr/vocabularies/theia_categories";
	skosmos:groupClass skos:ConceptScheme;
	skosmos:language "en";
	skosmos:shortName "Theia in-situ categories";
	skosmos:showChangeList "true" ;
	skosmos:showTopConcept "true" ;
	void:sparqlEndpoint <http://localhost:3030/skosmos/sparql> ;
	skosmos:sparqlGraph <http://in-situ.theia-land.fr/vocabularies/theia_categories> .

:categories a skos:ConceptScheme;
	skos:prefLabel "Skosmos Vocabulary Categories"@en .

:cat_general a skos:Concept ;
	skos:topConceptOf :categories ;
	skos:inScheme :categories ;
	skos:prefLabel "Yleiskäsitteet"@fi, 
		"Allmänna begrepp"@sv,
		"General concepts"@en .

:stw a skosmos:Vocabulary, void:Dataset ;
     dc:title "STW Thesaurus for Economics"@en ;
     skosmos:shortName "STW";
     dc:subject :cat_general ;
     void:uriSpace "http://zbw.eu/stw/";
     skosmos:language "en", "de";
     skosmos:defaultLanguage "de";
     void:sparqlEndpoint <http://localhost:3030/skosmos/sparql> ;
     skosmos:sparqlGraph <http://zbw.eu/stw/> .
```

## What is the expected output? What do you see instead?
1. I expect to see both of my vocabularies in Skosmos front page. Instead I only see "STW Thesaurus for Economics". 
The REST API using http://localhost//Skosmos/rest/v1/vocabularies?lang=en is returning the two vocabularies. 
```
{
	"@context": {
		"rdfs": "http:\/\/www.w3.org\/2000\/01\/rdf-schema#",
		"onki": "http:\/\/schema.onki.fi\/onki#",
		"title": {
			"@id": "rdfs:label",
			"@language": "en"
		},
		"vocabularies": "onki:hasVocabulary",
		"id": "onki:vocabularyIdentifier",
		"uri": "@id"
	},
	"uri": "",
	"vocabularies": [{
		"uri": "categories_theia",
		"id": "categories_theia",
		"title": "Categories of Theia in-situ information system"
	}, {
		"uri": "stw",
		"id": "stw",
		"title": "STW Thesaurus for Economics"
	}]
}
```

2. I can't see any concept of the vocabulary while clicking in the General concept link. I don't get any ERROR or WARN in Fuseki log file.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

I use Firefox 61.0.1 (64 bits). 
I also faced issues while installing dependencies using Composer and composer.phar file.  I had to remove development dependencies and everything went well.
```
  "require-dev": {
    "phpunit/phpunit": "4.8 - 5.1",
    "umpirsky/twig-gettext-extractor": "1.1.*",
    "phpdocumentor/phpdocumentor": "2.*",
    "codeclimate/php-test-reporter": "^0.2.0"
},
```
This makes me realize that the repository I cloned is not the latest stable version. I'll have another try with the latest maintenance version and let you know how it goes.

**Comment by charlycou** [comment]
I ran into the same procedure using v1.10-maintenance repository. 

- I don't have trouble anymore with dependencies intallation. 
- I can see my two vocabularies on Skosmos front page.

**I'm still facing issues:**

1.  I can't see STW vocabulary. The server return error 500 and I get the following exception in apache2 error.log.
```
[Fri Jul 13 08:02:26.351229 2018] [:error] [pid 3817] [client 192.168.51.1:58975] PHP Fatal error:  Uncaught EasyRdf\\Http\\Exception: HTTP request for SPARQL query failed in /var/www/html/Skosmos/vendor/easyrdf/easyrdf/lib/Sparql/Client.php:247\nStack trace:\n#0 /var/www/html/Skosmos/vendor/easyrdf/easyrdf/lib/Sparql/Client.php(128): EasyRdf\\Sparql\\Client->request('query', 'SELECT ?cs ?lab...')\n#1 /var/www/html/Skosmos/model/sparql/GenericSparql.php(72): EasyRdf\\Sparql\\Client->query('SELECT ?cs ?lab...')\n#2 /var/www/html/Skosmos/model/sparql/GenericSparql.php(664): GenericSparql->query('SELECT ?cs ?lab...')\n#3 /var/www/html/Skosmos/model/Vocabulary.php(209): GenericSparql->queryConceptSchemes('en')\n#4 /var/www/html/Skosmos/model/Vocabulary.php(226): Vocabulary->getConceptSchemes()\n#5 /var/www/html/Skosmos/model/Vocabulary.php(139): Vocabulary->getDefaultConceptScheme()\n#6 /var/www/html/Skosmos/vendor/twig/twig/lib/Twig/Template.php(679): Vocabulary->getInfo('en')\n#7 /tmp/skosmos-template-cache/64/64c6365a6f6e6f4ec7f756c2f7dffe8d1f52fdb84ea44ece4545c121eda5c8ef.php(33): Twig_Template->getAttribute(Object(Vocabu in /var/www/html/Skosmos/view/vocab-shared.twig on line 9, referer: http://192.168.51.51/Skosmos/en/
```
2. I can see the page of my second vocabulary (title, description...) but I can't see any of the concept of my vocabulary. 
![image](https://user-images.githubusercontent.com/22495652/42680739-2a1281b4-8686-11e8-900b-1c8ca15b0e3a.png)

The .ttl file of  my vocabulary (with .txt extension in order for GitHub to take it into account).
[categories_theia.ttl.txt](https://github.com/NatLibFi/Skosmos/files/2191877/categories_theia.ttl.txt)

Any idea ?

**Comment by osma** [comment]
I think you need to add the `dc:subject` information. The front page of Skosmos uses categories and needs to know under what category to display each vocabulary, using the `dc:subject` information.

Try adding
```
     dc:subject :cat_general ;
```

for your vocabulary.

**Comment by charlycou** [comment]
Thank you very much for your answer. I managed to install Skosmos successfully and I could display remote vocabularies. 
I'm not going any further with my vocabulary for the moment since it is not published on the web.

By chance, do you know any guideline on how serving semantic data on the web? What was your approach for Finto?
