### ISSUE TITLE
Support vocabulary downloads in multiple formats

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#78]
Support for multiple formats would require
- having the RDF files available both as (e.g.) RDF/XML and Turtle
- being able to point to many formats in the vocabularies.ttl file
- when there are several versions available, make multiple download links on the vocabulary home page
- make the REST API data method redirect to the appropriate format

**Comment by mhabsaoui** [comment]
Hi,

it would be interesting to consider other formats too such as PDF (Apache™ FOP (Formatting Objects Processor), N-Triples/Quads,...  Just like SKOSPLAY does (http://labs.sparna.fr/skos-play/convert).
