### ISSUE TITLE
Change of default skosmos:sparqlEndpoint in config.ttl.dist doesn't work

### ISSUE THREAD

**Issue by rwalkerands** [NatLibFi/Skosmos#786]
It seems that the change made in commit 854520f doesn't work. That commit changed `config.ttl.dist` thus:

```
-    skosmos:sparqlEndpoint "http://localhost:3030/ds/sparql" ;
+    #skosmos:sparqlEndpoint "http://localhost:3030/ds/sparql" ;
+    # use the dev.finto.fi endpoint where the example vocabularies reside
+    skosmos:sparqlEndpoint <http://api.dev.finto.fi/sparql> ;
```

"Out of the box" (i.e., using the updated `config.ttl.dist` as `config.ttl`), the API method `/rest/v1/types` still tries to connect to `http://localhost:3030/ds/sparql`, even though it should connect to `http://api.dev.finto.fi/sparql`.

Note that the value `"http://localhost:3030/ds/sparql"` is a _literal_, but the value  `<http://api.dev.finto.fi/sparql>` is a _resource_.

The method `GlobalConfig::getDefaultEndpoint` says:

```
        return $this->getLiteral('skosmos:sparqlEndpoint', 'http://localhost:3030/ds/sparql');
```

Since the value `<http://api.dev.finto.fi/sparql>` isn't a _literal_, the `getLiteral()` method falls back to the default value of `'http://localhost:3030/ds/sparql'`.

The `getDefaultEndpoint` method is different from `Vocabulary::getEndpoint`, which has this instead:

```
        return $this->resource->get('void:sparqlEndpoint')->getUri();
```

Either change `config.ttl.dist` to say:

```
     skosmos:sparqlEndpoint "http://api.dev.finto.fi/sparql";
```

or change `GlobalConfig::getDefaultEndpoint` to match `Vocabulary::getEndpoint`.

**Comment by osma** [comment]
Thanks, good catch and excellent analysis! I think the endpoint should be given as a resource not a literal for consistency - have to change the code as you say and also the migration script.

**Comment by kinow** [comment]
Excellent analysis indeed! I'm degugging #781 right now @osma . Let me know if you need any help with this one :+1:
