### ISSUE TITLE
Request to api.dev.finto.fi blocked by Virus/Spyware blocker?

### ISSUE THREAD

**Issue by rwalkerands** [NatLibFi/Skosmos#787]
I think this issue is about the firewall configuration of api.dev.finto.fi, which is used in the sample configuration `config.ttl.dist`.

## At which URL did you encounter the problem?

I'm trying out the sample config as given in `config.ttl.dist`, which points to the two vocabulary SPARQL endpoints at `<http://api.dev.finto.fi/sparql>`. I can see the top level of a vocabulary, but selecting a concept doesn't work.

It seems that clicking on a concept (which sends an request for a URL of the form `http://...../skosmos/ysa/fi/page/Y108584`, for YSA "A-vitamiini") generates two requests. The first is sent as a POST, and that succeeds. Then a second request is sent as a GET, and that fails.

Here is the URL of the GET request as generated inside `EasyRdf\Sparql\Client`:

`http://api.dev.finto.fi/sparql?query=PREFIX+skos%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2004%2F02%2Fskos%2Fcore%23%3E%0ASELECT+%2A+FROM+%3Chttp%3A%2F%2Fwww.yso.fi%2Fonto%2Fysa%2F%3E%0AWHERE+%7B%0A++SELECT+%3Fobject+%3Flabel+%28GROUP_CONCAT%28STR%28%3Fdir%29%3Bseparator%3D%27+%27%29+as+%3Fdirect%29%0A++WHERE+%7B%0A++++%3Chttp%3A%2F%2Fwww.yso.fi%2Fonto%2Fysa%2FY108584%3E+a+skos%3AConcept+.%0A++++OPTIONAL+%7B%0A++++++%3Chttp%3A%2F%2Fwww.yso.fi%2Fonto%2Fysa%2FY108584%3E+skos%3Abroader%2A+%3Fobject+.%0A++++++OPTIONAL+%7B%0A++++++++%3Fobject+skos%3Abroader+%3Fdir+.%0A++++++%7D%0A++++%7D%0A++++OPTIONAL+%7B%0A++++++%3Fobject+skos%3AprefLabel+%3Flabel+.%0A++++++FILTER+%28langMatches%28lang%28%3Flabel%29%2C+%22fi%22%29%29%0A++++%7D%0A++++OPTIONAL+%7B+%3Fobject+skos%3AprefLabel+%3Flabel+%7D%0A++%7D%0A++GROUP+BY+%3Fobject+%3Flabel%0A%7D%0ALIMIT+1000`

The response that comes back is:

```
<html>
    <head>
        <title>Virus/Spyware Download Blocked</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <META HTTP-EQUIV="PRAGMA" CONTENT="NO-CACHE">
        <meta name="viewport" content="initial-scale=1.0">
        <style>
  #content {
    border:3px solid#aaa;
    background-color:#fff;
    margin:1.5em;
    padding:1.5em;
    font-family:Tahoma,Helvetica,Arial,sans-serif;
    font-size:1em;
  }
  h1 {
    font-size:1.3em;
    font-weight:bold;
    color:#196390;
  }
  b {
    font-weight:normal;
    color:#196390;
  }
</style>
    </head>
    <body bgcolor="#e7e8e9">
        <div id="content">
            <h1>Virus/Spyware Download Blocked</h1>
            <p>Download of the virus/spyware has been blocked in accordance with company policy. Please contact your system administrator if you believe this is in error.</p>
            <p>
                <b>File name:</b> sparql
            </p>
        </div>
    </body>
</html>
```

I note that the page http://finto.fi/ysa/fi/page/Y108584 works perfectly! (SPARQL endpoint on a different server?)

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)

The above response is what comes back _internally_ in the EasyRdf library, but you can get the same response by entering the above (very long) URL into a browser or into Postman.

**Comment by osma** [comment]
Wow, that's a strange response! I don't think it's coming from Finto servers - we don't have any software that performs virus/malware scanning for incoming HTTP requests. Is it possible it is being generated locally? Can you try using a different network?

I tested the long URL myself in a browser, and got back SPARQL results.

**Comment by rwalkerands** [comment]
Sorry for the noise. Yes, it seems you are probably right: there may be some local interference happening. Closing.
