### ISSUE TITLE
Placement of help widget

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#79]
The current place for the help widget is problematic, as it's part of the concept display area but actually relates to other UI elements as well. Should find a new place for it.

**Comment by mhabsaoui** [comment]
Hi,

just wanted to know if it's possible to format the the help text : say we want spaces, new lines returns...
I don't know if there are keywords for skosmos_**.po files to make this.

Thanks.

**Comment by mhabsaoui** [comment]
Hi,

Another cool thing about  the help text bubble, would be to make appear/disapper toggling on click, not hovering, so we can read while writing in the search filed...
