### ISSUE TITLE
New labels for classification concept views

### ISSUE THREAD

**Issue by jarmosaarikko** [NatLibFi/Skosmos#806]
## At which URL did you encounter the problem?
e.g. http://dev.finto.fi/udcs/en/page/018549

UDC uses the term "Caption" for the skos:prefLabel which would apply to any classification.
skos:notation is the "UDC number (notation)" 

## What steps will reproduce the problem?
1. View a concept (class) for any classification 

## What is the expected output? What do you see instead?

For classification hierarchies the fields in the main concept view should be re-labeled as these are often hierarchical complex "classes" not single "concepts":
**property  CURRENT LABEL ==> NEW LABELS**
skos:notation  NOTATION ==> NOTATION{en} - NOTATION{sv} - NOTAATIO{fi}
skos:prefLabel  PREFERRED  TERM ==>  CAPTION{en} - KLASS{sv} - LUOKKA{fi}
skos:broader BROADER CONCEPT ==> BROADER CLASS{en} - BREDARE KLASS{sv} - YLÄLUOKKA{fi}
skos:narrower NARROWER CONCEPTS ==> NARROWER CLASSES{en} - UNDERAVDELNINGAR{sv} - ALALUOKAT{fi}
IN OTHER LANGUAGES{en} -  PÅ ANDRA SPRÅK{sv} - MUILLA KIELILLÄ{fi}
RELATED CONCEPT  ==>  SEE ALSO{en} -- SE ÄVEN{sv}  - KATSO MYÖS{fi}
 
## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Chrome

**Comment by osma** [comment]
One option would be to use subproperties (e.g. `udc:caption rdfs:subPropertyOf skos:prefLabel`) with the labels we want. Skosmos already supports this for basic properties (e.g. subproperties of skos:altLabel and skos:related) where it hides the superproperty if a subproperty is used with the same value. This mechanism does not extend to skos:prefLabel currently.

**Comment by osma** [comment]
Another option would be to make it possible to override the displayed label for SKOS properties e.g. prefLabel in vocabulary-specific configuration.

**Comment by jarmosaarikko** [comment]
Some classifications use altLabel  for glossary terms which guide the user to the correct class.  These terms are now show in the concept view under  label "OHJAUSTERMIT"@fi "HÄNVISNINGSTERMER"@sv "ENTRY TERMS"@en and in italic black text.  
For classifications these labels should be changed to "HAKEMISTON TERMIT" "INDEX TERMER"  "GLOSSARY TERMS" to separate from the actual prefLabels of concepts in other languages.    
example: https://finto.fi/ykl/en/page/?clang=sv&uri=37.1

**Comment by kouralex** [comment]
> @osma option1
> 
> One option would be to use subproperties (e.g. `udc:caption rdfs:subPropertyOf skos:prefLabel`) with the labels we want. Skosmos already supports this for basic properties (e.g. subproperties of skos:altLabel and skos:related) where it hides the superproperty if a subproperty is used with the same value. This mechanism does not extend to skos:prefLabel currently.

I was just wondering if this is currently supported in the search?


> @osma option2
> 
> Another option would be to make it possible to override the displayed label for SKOS properties e.g. prefLabel in vocabulary-specific configuration.

This would require all the translations to be listed in the `config.ttl` instead of external translation file. I don't know if that is wanted. However, this would beat the case where existing `skos:prefLabel` translation is incorrect, as in this use case. But I think this solution would not scale (for other properties) that easily?

**Comment by osma** [comment]
After some discussions today, I think that overriding property labels in config.ttl would be the most feasible way to implement this. The configuration could look something like this:

```
:udc skosmos:propertyLabelOverride
  [ skosmos:property skos:prefLabel ; rdfs:label "Caption"@en, "Luokka"@fi, "Klass"@sv ],
  [ skosmos:property skos:notation ; rdfs:label "UDC number"@en, "UDC-numero"@fi, "UDC-nummer"@sv ] .
```
