### ISSUE TITLE
Dynamic (AJAX style) loading of mappings

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#817]
## At which URL did you encounter the problem?
http://finto.fi/yso-paikat/fi/page/p147997

## What steps will reproduce the problem?
1. Open a concept page with mappings to Wikidata (and/or LCSH)

## What is the expected output? What do you see instead?

The page loads rather slowly the first time it is accessed. The problem is that Skosmos does a lookup to Wikidata (and/or LCSH) which may take some time to complete (or to time out if the remote endpoint is down), and the page will display only after this is done. Users may see page load delays of 5-10 seconds or even more in some cases. Subsequent loads of the same page (by any user) are faster because Skosmos usually caches the result using the PHP APCu cache.

To make this work better, we could change into a model where the page load doesn't wait for the remote request to complete. We need:

* A REST API method for retrieving mappings of a concept (including the data retrieved from the remote endpoint - perhaps optionally). We have an open PR #803 which could probably serve as a starting point for this.
* The bottom part of the concept page that displays mapping information should be changed so that it loads the data to display using an AJAX style request (it could display just the URIs while waiting for data, and/or show an AJAX spinner to indicate that more information is being loaded).
* Any widgets such as the Wikidata/Wikipedia widget need to be notified when the AJAX request completes so that they can display data based on the mappings.

The benefit of this way of loading (as opposed to loading the mappings directly from e.g. Wikidata on the browser side) is that Skosmos gets an opportunity to cache the remote data so that for subsequent users, the AJAX request should complete very quickly.

**Comment by kinow** [comment]
FWIW, doing a few tests today, noticed that it takes between 1 and 2 seconds to load the page without the mappings. And over 20 seconds with the mappings.

**Comment by osma** [comment]
Fixed in PR #846, closing this issue.
