### ISSUE TITLE
Support tooltips for custom properties

### ISSUE THREAD

**Issue by nqminh188** [NatLibFi/Skosmos#824]
The tooltips is only available for the properties recognized by Skosmos (i.e. definition, broader concept,...). 
It would be nice if it is supported for custom properties such as: Is Hosted By, See Also,... in the picture below.

![image](https://user-images.githubusercontent.com/11029190/49814460-f6465d00-fd69-11e8-829e-241ae1063476.png)

**Comment by osma** [comment]
Thanks for the suggestion. In practice, the tooltip could be read from the `rdfs:comment` for the property, just like the property label is read from the `rdfs:label` value of the property.

**Comment by osma** [comment]
In addition to `rdfs:label`, we could support `skos:definition` since it's used in the RDA vocabularies. SKOS leaves the domain of `skos:definition` open so it can be used even for non-concept-like resources such as properties.
