### ISSUE TITLE
Tediously long property lists for concepts in certain classification systems

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#833]
## At which URL did you encounter the problem?
http://dev.finto.fi/ykl/fi/page/38.55

## What steps will reproduce the problem?
When viewing a model of a large classification system in Skosmos, one might get hundreds of labels for the same property for one concept, in each language of the model. This crowds the concept view quite a lot.

## What is the expected output? What do you see instead?
Preferably the model would have been structured in a way that avoids situations where a concept has 400+ labels in various languages.

But when it happens, one solution would be adding a check in the relevant Skosmos twig template if there's a list of e.g. over 30 statements with the same property, the corresponding `<li>` element would have `max-height: 500px; overflow-y: scroll;` added to it. Of course, the maximum allowed number of statements without a scrollable list should depend on the font size.

**Comment by joelit** [comment]
Large amounts of altLabels also make the search results for such concepts difficult to view:

http://dev.finto.fi/hklj/fi/search?clang=fi&q=Ranskankieliset

**Comment by MikkoAleksanteri** [comment]
Suggestion from FSD: some properties like altLabels and related concepts could be hidden by default and only opened if user so wants. Example from CESSDA's ELLST:

![image](https://user-images.githubusercontent.com/8804680/57132641-e119ab80-6da8-11e9-9ac2-63501c769ab6.png)

Difficulty with this is how to make sure that a random user realizes the existence of relations.

**Comment by MikkoAleksanteri** [comment]
One possibility could also be to show for example the first ten narrower concepts and then an option to open the rest if the user chooses to do so.
