### ISSUE TITLE
AltLabels in other languages are not sorted alphabetically

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#835]
## At which URL did you encounter the problem?
http://dev.finto.fi/ykl/fi/page/71.3

It's easy to see in a vocabulary with lots of altLabels per concept. Here the Swedish altLabels happen to be the exact same ones as in Finnish - the labels for the selected language are sorted, whereas the labels for the other languages are not.

**Comment by osma** [comment]
Better example: http://dev.finto.fi/yso/fi/page/?clang=sv&uri=p9459
"sähköinen liiketoiminta" is out of place
