### ISSUE TITLE
Use subproperty of prefLabel for concept page headline

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#854]
## At which URL did you encounter the problem?
http://finto.fi/cn/en/page/218139A
http://finto.fi/cn/fi/page/218139A

## What steps will reproduce the problem?
1. Look at any CN concept page

## What is the expected output? What do you see instead?

The main headline for the page says 

    PREFERRED TERM: Sanoma Media Finland

Lower down we have

    HAS PREFERRED NAME FOR THE CORPORATE BODY: Sanoma Media Finland

This is unnecessary duplication. Also in this case the entity is a corporate body so the heading "preferred term" is a bit misleading.

What we could do here is to notice that the RDA property for "name of corporate body" is a sub-property of skos:prefLabel and 

- use the label of the subproperty instead of "preferred term" next to the headline
- hide the subproperty elsewhere to avoid repetition

**Comment by kouralex** [comment]
Do you mean that the headline would still stay at the "Preferred term" or to be changed to this "HAS PREFERRED NAME FOR THE CORPORATE BODY" in some form? This is a bit related to #878 and especially to #806.

**Comment by osma** [comment]
Yes that was what I tried to state above. When there is a subproperty of skos:prefLabel, with the same value for the current concept, and an existing label in the current UI language, then the PREFERRED TERM label should be changed to the label of the subproperty.
