### ISSUE TITLE
Font update Issue

### ISSUE THREAD

**Issue by iltzortz** [NatLibFi/Skosmos#855]
There is an issue with greek letter **κ** that is displayed like the latin character **k** . 
Replacing the fonts of folder `Skosmos/resource/fonts/ ` with their newer version from 
https://github.com/mozilla/Fira/tree/4.202 resolved this issue.

Perhaps you consider an update to the repository fonts copy or provide a relevant dependency.

**Comment by osma** [comment]
Thank you for the report!

Is it possible for you to do a pull request?

**Comment by osma** [comment]
Fixed via #856
