### ISSUE TITLE
Swagger/OpenAPI documentation for mappings method

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#862]
Currently, we have concept-specific methods for most relations presented in the YSO data model in the Skosmos API. We're still missing a way to query skos:exactMatches and skos:closeMatches.

**Comment by kouralex** [comment]
There exists `mappings` REST method for asking all kinds of relations. It is, however, missing documentation.

**Comment by osma** [comment]
Changed the title to better reflect the issue.
