### ISSUE TITLE
Support Last-Modified and 304 for RDF responses

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#864]
PR #859 implemented support for Last-Modified headers (#574) and 304 responses (#575) for concept pages, but not RDF responses that are handled by RestController.

RDF serializations (Turtle, RDF/XML, JSON-LD, N-Triples...) of concepts should also come with Last-Modified headers generated in the same way as for HTML responses (concept pages). If the client sends an If-Modified-Since header and the timestamp is unchanged, the server should generate a 304 response.

**Comment by kinow** [comment]
>and the timestamp is unchanged

I think this part is the only trick one. What happens when we have a collection of elements? In #859 the controller is specifically searching for the modified date of a Concept.

Or are we going to use only the `.git` directory modified date and the `config.ttl` modified date? Or are there endpoints that will require special care?

**Comment by osma** [comment]
One possibility here would be to check whether the Collection has a timestamp, but that's unlikely. I don't recall seeing any vocabulary where Collections have timestamps.

I think the concept scheme timestamp should be used here, together with git  and `config.ttl` modified dates, as is done for Concepts which don't have a timestamp.

**Comment by kinow** [comment]
>I think the concept scheme timestamp should be used here, together with git and config.ttl modified dates, as is done for Concepts which don't have a timestamp.

Roger that! Thanks @osma !

**Comment by osma** [comment]
This was implemented long ago in PR #869 (and released in 2.6) but we forgot to close this issue.
