### ISSUE TITLE
Composer warning: Package phpunit/phpunit-mock-objects is abandoned

### ISSUE THREAD

**Issue by kinow** [NatLibFi/Skosmos#865]
## At which URL did you encounter the problem?

No URL, running `composer install`

## What steps will reproduce the problem?
1. Run `composer install` after checking out the project
2. Search the output for

```
$ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Downgrading twitter/typeahead.js (v0.11.1 => v0.10.5): Downloading (100%)         
Package phpunit/phpunit-mock-objects is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files

```
## What is the expected output? What do you see instead?

Normal output, without warnings.

**Comment by osma** [comment]
Thanks, I saw the same warning. I wonder how easy it is to fix this. Some unit tests use mock objects and I guess this package is used to implement them.

**Comment by henriyli** [comment]
I fixed it by upgrading the PHPUnit to a newer version. The dependency was in PHPUnit itself.
