### ISSUE TITLE
Links to YSO Places not shown correctly on YSO concept pages

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#868]
Found while testing PR #851 

## At which URL did you encounter the problem?
http://localhost/Skosmos/yso/fi/page/p25064

## What steps will reproduce the problem?
1. Use a version of YSO where the `dct:spatial` links have been changed to point to YSO Places instead of the currently used YSA geographical concepts
2. Go to the concept page for [Saint John's Church (Helsinki)](http://www.yso.fi/onto/yso/p25064)

## What is the expected output? What do you see instead?

Expected to see the "spatial coverage" shown as "Helsinki (YSO Places)"
Instead it is shown as "ysopaikat:p94137 (YSO - General Finnish ontology)":

![image](https://user-images.githubusercontent.com/1132830/56584410-5edcfa80-65e4-11e9-83fc-4f2dd769d600.png)

The problem is probably that both YSO and YSO Places share the same URI space. The concept page tries to look up the URI from within YSO (and fails) instead of YSO Places where it is really defined.

**Comment by osma** [comment]
I tried to debug this a bit. There are at least two problems:

1. Concept.getProperties [calls guessVocabularyFromUri()](https://github.com/NatLibFi/Skosmos/blob/master/model/Concept.php#L600) using the current vocabulary ID (here `yso`) as the preferred vocabulary ID, leading to the conclusion that the YSO Places URI is within YSO, which it is not, and a ConceptPropertyValue is constructed instead of a ConceptMappingPropertyValue. This problem was introduced in PR #851.
2. Even if the above change from PR #851 is reverted, guessVocabularyFromURI is called in many places from within ConceptMappingPropertyValue again setting the current vocabulary ID (`yso`) as the preferred vocabulary ID. Again the invalid conclusion is that the URI exists within YSO, not YSO Places.

There should be some form of double-checking to see whether the vocabulary disambiguation was actually succesful...but I'm unsure whether it should be done from within guessVocabularyFromURI (where it could introduce additional overhead) or in the calling code (which means the fix should be done in many places).

**Comment by osma** [comment]
Tried to add an additional check to disambiguateVocabulary (called from guessVocabularyFromUri) but it does introduce significant additional overhead even with some additional caching for the queryLabel method: YSO search result page response time for the query "aut" goes from 1.1 seconds to 1.9 seconds and the number of SPARQL queries from 5 to 158.

**Comment by kinow** [comment]
>and the number of SPARQL queries from 5 to 158

:eyes: that's quite an overheard! When I saw the seconds thought it would be OK, but this amount of queries looks dangerous :disappointed:

**Comment by osma** [comment]
Yes, it's a bit frustrating - this would be backtracking on the progress made in #851 (though not all the way).
