### ISSUE TITLE
Need for a configurable general message plugin

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#874]
Plugins for Skosmos are registered in a case-by-case manner for each vocabulary. It is common that the function of the plugin is to display a message for the users about the state of the vocabulary. In such cases, there's not much point creating a separate plugin (and a separate GitHub project) for every message plugin.

Instead, the config.ttl should define a message plugin for a vocabulary in a manner something like this:
skosmos:usePLugin "complicatedPluginName1", "actualPluginName3", [ name "messagePlugin" ; message "This vocabulary is still under construction"@en, "Tämä' sanasto on vielä kehitysvaiheessa"@fi, "Denna vokabulär befinner sig ännu i ett utvecklingsstadium"@sv ] ;

This should be within the syntax for turtle and the result is a blank node which contains the name of the generic message plugin and the messages it should return in different languages.

**Comment by kouralex** [comment]
This would indeed be a very useful feature! The syntax or maybe even new `skosmos` predicate should probably be thoroughly thought, though. I guess that, for example, @osma might have some good tips for this?
