### ISSUE TITLE
Concept hierarchy fails to load for some concepts

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#876]
## At which URL did you encounter the problem?
https://finto.fi/koko/fi/page/p34344

## What steps will reproduce the problem?
1. The hierarchy tree won't load for this concept page
2. If you navigate to the broader concept http://finto.fi/koko/fi/page/p35587 and then select "interest groups (associations)" from the hierarchy below
3. You get a different kind of issue where the concept hierarchy will load only titles without the tree menu

**Comment by osma** [comment]
Is there a cycle in the hierarchy?

**Comment by joelit** [comment]
I looked and didn't find one. Even weirder, I cannot reproduce the bug on the installation on my local computer but it will happen on both finto.fi and dev.finto.fi.

**Comment by osma** [comment]
I see this in the JS console:

    TypeError: this.get_container_ul(...)[0] is undefined      jstree.min.js:3:1000

**Comment by joelit** [comment]
Hmm. I also see following error messages in the browser console:

Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at Object.success (widget.js:56)
    at i (jquery.min.js:2)
    at Object.fireWith [as resolveWith] (jquery.min.js:2)
    at z (jquery.min.js:4)
    at HTMLScriptElement.c (jquery.min.js:4)
    at HTMLScriptElement.dispatch (jquery.min.js:3)
    at HTMLScriptElement.r.handle (jquery.min.js:3)

Uncaught TypeError: Cannot read property 'className' of undefined
    at a.jstree.plugins.sort._redraw (jstree.min.js:3)
    at a.jstree.plugins.sort.redraw (jstree.min.js:3)
    at a.jstree.plugins.sort.j (jstree.min.js:2)
    at a.jstree.plugins.sort.<anonymous> (jstree.min.js:2)
    at Worker.f (jquery.min.js:2)

So there must be something fishy in the data that crashes the JS tree.

**Comment by kouralex** [comment]
I have now investigated this a bit further, and it seems like the [finna widget](https://github.com/NatLibFi/Skosmos-widget-finna) is causing this by raising an unhandled error, which in return means that it must be fixed there (I just installed the plugin and it stopped working on my local installation, before that it was working fine). Therefore this is not a Skosmos issue per se and I suggest closing this issue.

Any thoughts on that, @joelit ?

**Comment by osma** [comment]
Created [this issue](https://github.com/NatLibFi/Skosmos-widget-finna/issues/7) for the Finna widget. Closing this one.
