### ISSUE TITLE
Limit search by parent: restrict to actual parents of query results

### ISSUE THREAD

**Issue by MikkoAleksanteri** [NatLibFi/Skosmos#89]
It is possible to limit one's search results by "type", "group" or "parent", see for example http://dev.finto.fi/yso/en/search?lang=&q=oikeus ("Search options").

With the "parent"-limit one can choose any concept from the vocabulary, even if limiting would result to zero hits.

It would be better if one could choose the limiting parent from the actual parents of the query result concepts.

**Comment by osma** [comment]
Closing and archiving issue due to lack of activity. Please reopen if there are concrete reasons for reconsidering.
