### ISSUE TITLE
Showing notation in the alphabetical listing for classifications

### ISSUE THREAD

**Issue by jarmosaarikko** [NatLibFi/Skosmos#896]
## At which URL did you encounter the problem?
http://dev.finto.fi/ykl/fi/index
or any concept view.

## What steps will reproduce the problem?
1. The alphabetical listing shows 10 equal captions. This is a problem with numerical classifications. the same caption may be used several times in different branches. This produces a problem for browsing the alphabetical listing which is not easy to solvel.
2.Aasia
Aasia
Aasia
Aasia
etc.
3.

## What is the expected output? What do you see instead?
One possible solution: on the **alphabetical view** always show the **skos:notation**  in parenthesis AFTER the caption (skos:prefLabel).  
---  in principal, almost the same way as the skos:notation (class="tree-notation") is shown BEFORE the caption in the **hierachical view**.
Aasia (26.1)
Aasia (48.1)
Aasia (70.981)
Aasia (72.981)
Aasia (73.981)
etc.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Chrome

Related issue: https://github.com/NatLibFi/Skosmos/issues/264

**Comment by osma** [comment]
This is also analoguous to #587 (show broader concept information) and #587 (show concept scheme information) - a similar approach should be used for all these

**Comment by osma** [comment]
Suggestion: The configuration mechanism for this and the similar qualifiers should be generic, even though the implementation may not initially support all options. Something like this, in config.ttl:

```
:ykl skosmos:alphabeticalListQualifier skos:notation .
```

Other options for the value in the future would be `skos:broader` (#587) and `skos:inScheme` (#588) but they are out of scope for this issue.
