### ISSUE TITLE
Downloading a large vocabulary crashes the browser tab

### ISSUE THREAD

**Issue by kouralex** [NatLibFi/Skosmos#901]
## At which URL did you encounter the problem?
http://finto.fi/rest/v1/yso/data?format=application/rdf%2Bxml
## What steps will reproduce the problem?
1. Go to http://finto.fi/yso/en
2. Click the RDF/XML link at the Download this vocabulary as SKOS/RDF:

## What is the expected output? What do you see instead?
I expect to download the vocabulary. Instead of that I get a crashed tab.

## What browser did you use? (eg. Firefox, Chrome, Safari, Internet explorer)
Firefox

**Comment by kouralex** [comment]
The issue seems to be related to the browser behavior: it tries to open the file in browser, crashing it.

I think it should suggest downloading the vocabulary instead of showing it. I am not sure if this is browser-related issue (do user preferences affect this?) or a general one. If there is a way to force the browser to ask what to do with the file, it should be implemented.

**Comment by osma** [comment]
You can use a HTTP header (Content-Disposition) to indicate that a resource is intended to be downloaded, but this would have to be done in Apache (or whatever web server is used to serve the actual vocabulary files), outside Skosmos.

Another option is to use the `download` attribute on the link tag. This could be done in the Skosmos HTML template code, though I don't know if it's widely supported or not.

Source for both: https://www.designedbyaturtle.co.uk/how-to-force-the-download-of-a-file-with-http-headers-and-php/

**Comment by osma** [comment]
I'm also unsure whether the `download` attribute plays well with the redirection that happens when you click the link.

**Comment by kouralex** [comment]
Just checked, seems like the easy way of setting the `download` attribute does not play well with the redirection.

**Comment by osma** [comment]
I added this snippet to the Apache VirtualHost configuration:

        # set Content-Disposition header for RDF and MARCXML downloads
        # so that browsers don't try to render them
        <IfModule mod_headers.c>
            <FilesMatch "\.(ttl|rdf|mrcx)$">
                Header set Content-Disposition "attachment"
            </FilesMatch>
        </IfModule>

Also, the `headers` Apache module needs to be enabled.

**Comment by kouralex** [comment]
Ok, so this leaves open only the documentation part. Can you do that @osma (in addition to closing this)?

**Comment by osma** [comment]
I added documentation about this to the Serving Linked Data wiki page:

https://github.com/NatLibFi/Skosmos/wiki/ServingLinkedData#serving-vocabulary-data-files
