### ISSUE TITLE
Self-contained Docker image for trying out Skosmos

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#910]
The current [Docker support](https://github.com/NatLibFi/Skosmos/wiki/Install-Skosmos-with-Fuseki-in-Docker) is based on the idea that the Docker image provides an environment where Skosmos can run, but Skosmos itself isn't included within the image. Dependencies must be installed outside the container and the result bind-mounted to the container.

This isn't ideal for a new user that just wants to try out Skosmos. I think it should be possible to make a more self-contained Docker image that includes the Skosmos codebase, all dependencies etc. It wouldn't have to be fully production-ready, because local requirements are likely to be slightly different each time, but at least the installation should be enough to get started. Fuseki would still be outside the image, I think.

What do others think? @kinow?

**Comment by kinow** [comment]
+1, maybe keep this one either in the repository, or somewhere else for developers? (It was quite useful for me.)

Then we can have other images like `skosmos-alpine-v123`, or include the php version, etc.

**Comment by kinow** [comment]
Hi,

I started implementing a Dockerfile for this issue: https://github.com/kinow/skosmos-docker

The base image is Ubuntu, and I'm installing things like PHP, Composer, locale, curl, git, etc. We could use the php base images instead, which would simplify it, but at the moment it looks quite like the tutorial (the php images use debian as base image).

I am planning to add instructions to load a config.ttl, which should allow users to either run the image as-is, and get the same as in the tutorial, or to give it another config.ttl. One issue, however, is that if the user chooses a vocabulary in, say, Chinese, the language/locale would not be installed. So I **think** PHP would fail to display the vocabulary?

Once I finish following the tutorial to create that Skosmos image, I will add a `docker-compose.yml` so users can try it with `docker-compose up`, and get the Skosmos container with the tutorial configuration, and another Fuseki container with the dataset loaded.

Cheers
Bruno

**Comment by osma** [comment]
> I started implementing a Dockerfile for this issue: https://github.com/kinow/skosmos-docker

Great! Now you've started a separate git repo for this, but I think that eventually the Dockerfile could live in the main Skosmos repo, alongside the current [Dockerfile](https://github.com/NatLibFi/Skosmos/blob/master/Dockerfile). We just have to think about how to name them since there is more than one...

> The base image is Ubuntu, and I'm installing things like PHP, Composer, locale, curl, git, etc. We could use the php base images instead, which would simplify it, but at the moment it looks quite like the tutorial (the php images use debian as base image).

OK. I wouldn't mind switching to the Debian based PHP base images, if that makes things simpler. But of course it's good to align with the tutorial so maybe stick to that approach for now.

> I am planning to add instructions to load a config.ttl, which should allow users to either run the image as-is, and get the same as in the tutorial, or to give it another config.ttl. One issue, however, is that if the user chooses a vocabulary in, say, Chinese, the language/locale would not be installed. So I think PHP would fail to display the vocabulary?

Locales are indeed a potential issue. However, the locale is only important for the UI languages. Content languages (i.e. languages of SKOS labels and the like) are still supported without having to install the locale.

Maybe the Dockerfile could install the locales for all the supported [UI languages](https://github.com/NatLibFi/Skosmos/tree/master/resource/translations)? There are currently 14 of those (some are not very up to date though).

> Once I finish following the tutorial to create that Skosmos image, I will add a docker-compose.yml so users can try it with docker-compose up, and get the Skosmos container with the tutorial configuration, and another Fuseki container with the dataset loaded.

Excellent!

**Comment by kinow** [comment]
>Great! Now you've started a separate git repo for this, but I think that eventually the Dockerfile could live in the main Skosmos repo, alongside the current Dockerfile. We just have to think about how to name them since there is more than one...

That was the plan. I was using the Dockerfile from [JupyterHub](https://github.com/jupyterhub/jupyterhub/tree/master/dockerfiles). They keep it under the same repo as the code, but in a directory `./dockerfiles`. Should we also move the current Dockerfile + docker-compose there (maybe `Dockerfile.development` and `docker-compose-dev.yml`, or under another subdirectory?)?

 >OK. I wouldn't mind switching to the Debian based PHP base images, if that makes things simpler. But of course it's good to align with the tutorial so maybe stick to that approach for now.

:+1: 

>Locales are indeed a potential issue. However, the locale is only important for the UI languages. Content languages (i.e. languages of SKOS labels and the like) are still supported without having to install the locale.
>
>Maybe the Dockerfile could install the locales for all the supported UI languages? There are currently 14 of those (some are not very up to date though).

Oh, good idea! I don't think adding a new language adds a lot of space (but will check).

Thanks Osma! More to come in the next days :-)

**Comment by osma** [comment]
> That was the plan. I was using the Dockerfile from JupyterHub. They keep it under the same repo as the code, but in a directory ./dockerfiles. Should we also move the current Dockerfile + docker-compose there (maybe Dockerfile.development and docker-compose-dev.yml, or under another subdirectory?)?

Creating a `dockerfiles` directory sounds good. There are already way too many files in the root directory...
