### ISSUE TITLE
Test failures on PHP 7.4

### ISSUE THREAD

**Issue by osma** [NatLibFi/Skosmos#920]
## At which URL did you encounter the problem?
See the Travis build log: https://travis-ci.org/NatLibFi/Skosmos/jobs/645471054

## What steps will reproduce the problem?
1. Try to run Skosmos tests using PHP 7.4

## What is the expected output? What do you see instead?

The build fails with warnings like this:

    Error: implode(): Passing glue string after array is deprecated. Swap the parameters

There might be other errors as well but this was by far the most prominent.
Found while attempting to upgrade PHP, see #919

**Comment by osma** [comment]
Not sure if the `implode` warning is the real issue here. According to the [PHP 7.4 deprecated features](https://www.php.net/manual/en/migration74.deprecated.php) list, it's deprecated, but in my understanding should just print a warning. In any case, I couldn't find any `implode` calls with invalid parameter order within the Skosmos code base, though they might be in some library we depend on.

**Comment by osma** [comment]
[This EasyRdf PR](https://github.com/njh/easyrdf/pull/311) fixes a number of `implode` calls. It was merged to EasyRdf `master` in November 2019 but it's not yet in any released version.

**Comment by kouralex** [comment]
There exists [a new fork of EasyRdf](https://github.com/sweetyrdf/easyrdf) that aims to address maintenance issues of that project.

What do you think @osma about switching to using it? It would fix this issue straightaway.

**Comment by osma** [comment]
Good catch @kouralex ! The fork looks good but it seems that the final outcome is not yet resolved - it looks possible that the original EasyRdf repo could move to the newly created [easyrdf organization](https://github.com/easyrdf) account. See [this comment](https://github.com/njh/easyrdf/issues/320#issuecomment-637885500) in particular. Maybe wait at least a few more days for the dust to settle?

**Comment by k00ni** [comment]
Hi, i am the owner of the EasyRdf fork you mentioned.

It would be helpful if you could post a comment in discussion at https://github.com/njh/easyrdf/issues/320 and tell us what parts of EasyRdf you use and how you think about the whole situation.

**Comment by osma** [comment]
Update on current PHP 7.4 status:

@aturbati wrote on skosmos-users:
> I completely 
> removed all traces of php and installed only php 7.4 with all the 
> required modules and now everything seems to be working fine. I'll do 
> some more tests and, if everything is ok, I'll upgrade the Skosmos 
> version on the AGROVOC server as well.

So it seems Skosmos is now working on PHP 7.4!

But Travis CI tests on PHP 7.4 are not working, see e.g. [this build log](https://travis-ci.com/github/NatLibFi/Skosmos/jobs/483799550)

**Comment by osma** [comment]
We are using PHPUnit 7.4.20 which is obsolete and does not support PHP 7.4:
https://phpunit.de/supported-versions.html
This could be at least part of the problem.
