### ISSUE TITLE
Invalid character in SMTP headers

### ISSUE THREAD

**Issue by j-dornbusch** [NatLibFi/Skosmos#936]
This line of code 
https://github.com/NatLibFi/Skosmos/blob/master/controller/WebController.php#L366 
        $headers = "MIME-Version: 1.0″ . '\r\n";
introduces an invalid quote that can cause SMTP servers to crash, as explained here :
https://groups.google.com/forum/#!topic/skosmos-users/2d6xTLNx4vg
 It should be : 
        $headers = "MIME-Version: 1.0" . "\r\n";

**Comment by osma** [comment]
Thanks, good catch! Looking at git history, this bug has been in Skosmos since the project transitioned from SVN in 2014, so it's pretty ancient.
