### ISSUE TITLE
Search test failures and test config endpoint need fixing after recent merges

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#953]
* Due to configuration errors Skosmos's test fuseki config after merge, ModelTest/testSearchConceptsWithOneVocabSearchLangOtherThanLabellang() was run incorrectly. 
* Search lang was handled incorrectly but this wasn't caught in the tests.

I'll put both fixes under this issue.

**Comment by osma** [comment]
FIxed by #954. (Please use "Fixes" or "Closes" statements in commit messages or PR notes to automatically close related issues!)
