### ISSUE TITLE
"counts" table in vocabulary page is missing class="table"

### ISSUE THREAD

**Issue by tfrancart** [NatLibFi/Skosmos#955]
## At which URL did you encounter the problem?

http://erato.sparna.fr/skosmos-ar/thesaurus/en/

## What steps will reproduce the problem?
  - Go to a vocabulary page.
  - In the HTML code, look for the `<table id="counts"` 
  - it is missing the class="table"

This has a side-effect when displaying in Arabic, RTL.

## What is the expected output? What do you see instead?

The table should have class="table", but also have a max-width=450px just like the table id="statistics" below it.

**Comment by osma** [comment]
Thanks for the report. I tested the suggested change. Some other adjustments are needed as well, but those are doable. We're just about to release 2.4 but this is a relatively straightforward fix so I think it could go in...
