### ISSUE TITLE
Bad layout of preferred term

### ISSUE THREAD

**Issue by mirmaid** [NatLibFi/Skosmos#963]
## At which URL did you encounter the problem?

http://finto.fi/yso/fi/page/p23265

![atk](https://user-images.githubusercontent.com/10060845/77519432-2abf2900-6e88-11ea-9ee8-2ac062598999.png)

**Comment by mirmaid** [comment]
Myös http://finto.fi/yso/fi/page/p3792

**Comment by tpalonen** [comment]
See also: http://finto.fi/yso/fi/page/p5473
![finto-käytettävä-termi-näyttää-oudolta](https://user-images.githubusercontent.com/8860719/78028984-8a29a700-7368-11ea-97ac-42d52208797a.jpg)
