### ISSUE TITLE
Need for a static version number in the project

### ISSUE THREAD

**Issue by joelit** [NatLibFi/Skosmos#965]
Currently, Skosmos generates the version information for the about page with git describe. This has the problem that it's assumed Skosmos is always deployed in an initialized git repository, otherwise the version is displayed as 'unknown'.

The version information could be stored in a separate file in a static manner, that is kept up to date with a git pre-commit hook. This way the version tag could be displayed no matter how Skosmos is deployed.

**Comment by kinow** [comment]
We had a similar problem in a project I am currently working on. The version would come from a Python file, then the git tag or commit would be appended. But if you deployed it without the git information it would fail.

Now it's only in Python, the same place where we get the value used in `setup.py` and uploaded to PYPI.

It also got a new frontend, in JS. The version is in the `package.json` file, and should match the tag once released. In the UI, there is a fixed place where we display the UI version too, which is useful when comparing screenshots or deploying a new version.

+1

**Comment by osma** [comment]
This was implemented in PR #1308 released as part of Skosmos 2.15, but we forgot to close this issue.
